"""
Master Data Builder: Assembles the entire 40-Week / 200-Day Cybersecurity Curriculum
into `curriculum.json` with all 9 phases, complete day metadata, tools, topics, and objectives.
"""

import json
from pathlib import Path

phases = []

# Load Phase 1 & 2 from generate_curriculum_part1.py
with open(r"d:\RED TEAMING\generate_curriculum_part1.py", "r", encoding="utf-8") as f:
    code = f.read()

# Execute code to get Phase 1 and 2
local_vars = {}
exec(code, {}, local_vars)
phases = local_vars["phases"]

# PHASE 3: Privilege Escalation + Internal Security (Weeks 13–18, Days 061–090)
phases.append({
    "phase_num": 3,
    "phase_id": "phase-03-internal-security",
    "phase_title": "Privilege Escalation + Internal Security",
    "weeks_range": "Weeks 13–18",
    "days_range": "Days 061–090",
    "objective": "Master local privilege escalation on Linux and Windows, Active Directory architecture and attack paths, Kerberos abuse, credential harvesting, and lateral movement.",
    "skills": ["Linux privesc enumeration & GTFOBins", "Container breakouts & Linux capabilities", "Active Directory architecture & LDAP querying", "Kerberos abuse (Kerberoasting, AS-REP, Tickets)", "BloodHound graph analysis & AD CS exploitation", "Windows privesc (Services, Tokens, UAC)", "Credential dumping & lateral movement"],
    "tools": ["LinPEAS", "WinPEAS", "GTFOBins", "BloodHound", "SharpHound", "PowerView", "Rubeus", "Mimikatz", "Impacket", "evil-winrm", "CrackMapExec / NetExec", "Certify", "Coercer"],
    "project_id": "project-03-corporate-ad-lab",
    "project_title": "Corporate Active Directory Lab (Domain Controller + Member Servers + Linux Client + BloodHound Attack Paths)",
    "weeks": [
        {
            "week_num": 13,
            "week_id": "week-13-linux-privesc-foundations",
            "week_title": "Linux Privilege Escalation Foundations",
            "objective": "Master system enumeration, SUID exploitation via GTFOBins, Sudo privileges, capabilities, and automated cron exploitation.",
            "tools": ["LinPEAS", "linWinPwn", "GTFOBins", "getcap", "find", "sudo", "crontab"],
            "major_concepts": ["System Enumeration", "GTFOBins Execution", "Sudoers Misconfigurations", "Linux Capabilities Model", "Cron Wildcard Injection"],
            "weekly_lab": "Linux Privilege Escalation Lab: Exploit vulnerable SUID binaries, misconfigured sudo rules, and high-privilege capabilities to obtain root.",
            "deliverable": "Linux Privilege Escalation Playbook & GTFOBins Cheatsheet",
            "days": [
                {"day_num": 61, "title": "Linux Enumeration Methodology — LinPEAS & Manual Discovery", "topics": ["Automated enumeration scripts: LinPEAS, linux-smart-enumeration, LinEnum", "Manual host enumeration checklist: OS version, kernel release, users, network sockets, mounted drives", "Analyzing output without triggering defense alerts", "Identifying interesting writable files and unmounted disks", "Checking for cleartext credentials in configuration files and history files (.bash_history)"], "objectives": "Execute thorough manual and automated Linux host enumeration to spot privilege escalation vectors.", "lab": "Run LinPEAS and manual discovery commands on a target Linux VM to identify all misconfigurations and potential escalation paths.", "interview_q": "Why is running automated enumeration scripts like LinPEAS sometimes risky during stealth red team operations, and what manual commands would you prioritize instead?"},
                {"day_num": 62, "title": "SUID/SGID Binary Exploitation & GTFOBins Tradecraft", "topics": ["Understanding the SUID execution context and real vs effective UID", "GTFOBins repository usage and categories (shell, file read, file write, SUID)", "Exploiting common SUID binaries: find, vim, cp, bash, nmap, base64", "Shared library hijacking in SUID binaries (strace analysis of missing .so files)", "Remediation: Removing unnecessary SUID bits across the filesystem"], "objectives": "Identify non-standard SUID binaries and use GTFOBins techniques to achieve root command execution.", "lab": "Configure test SUID permissions on `find` and a custom C program; use strace to identify missing shared libraries and inject a malicious .so file.", "interview_q": "How does `find` with SUID permissions allow a local attacker to spawn a root shell, and what is the exact syntax?"},
                {"day_num": 63, "title": "Linux Sudo Rights Misconfigurations & Environmental Overrides", "topics": ["The `/etc/sudoers` file syntax, user specifications, and NOPASSWD directives", "Auditing current user sudo permissions (`sudo -l`)", "Exploiting specific binary sudo privileges via GTFOBins (less, more, awk, python, tar)", "Environmental preservation vulnerabilities: `env_keep += LD_PRELOAD` and `env_reset` bypass", "Sudo version vulnerabilities (CVE-2021-3156 Baron Samedit overview)"], "objectives": "Analyze sudoer configurations and leverage legitimate administrative binaries to break out into a root shell.", "lab": "Exploit `sudo -l` permissions permitting execution of `less` and `tar` to spawn a shell; configure an `LD_PRELOAD` privilege escalation exploit.", "interview_q": "Explain how the `env_keep += LD_PRELOAD` directive in `/etc/sudoers` allows any user with a single sudo command to gain instant root access."},
                {"day_num": 64, "title": "Linux Capabilities Exploitation (getcap / setcap)", "topics": ["Linux capabilities model: Granular privilege assignment replacing monolithic root permissions", "Enumerating capabilities: `getcap -r / 2>/dev/null`", "Dangerous capabilities: `cap_setuid`, `cap_net_raw`, `cap_dac_read_search`, `cap_sys_admin`", "Exploiting python/perl/tar with `cap_setuid+ep`", "Remediation: Auditing and revoking excessive capabilities with `setcap -r`"], "objectives": "Discover and exploit process capabilities granted to system binaries to elevate privileges.", "lab": "Assign `cap_setuid+ep` to a test Python3 binary and write a one-liner to elevate execution to UID 0.", "interview_q": "What are Linux capabilities, and why is `cap_setuid+ep` on an interpreter like Python just as dangerous as setting the SUID bit?"},
                {"day_num": 65, "title": "Exploiting Cron Jobs, Wildcard Injections & World-Writable Services", "topics": ["Scheduled task enumeration: `/etc/crontab`, `/etc/cron.d/`, `/var/spool/cron/crontabs/`", "Monitoring process creation in real-time with `pspy` to catch recurring cron scripts", "World-writable scripts and path hijacking in cron jobs", "Tar wildcard injection (`--checkpoint=1 --checkpoint-action=exec=sh exploit.sh`)", "Writable systemd timer units and service files"], "objectives": "Detect hidden cron jobs using process snooping and exploit script permissions or wildcard expansion to gain root.", "lab": "Deploy `pspy64` to detect a hidden background cron job, identify a wildcard in its tar command, and exploit it to spawn a reverse root shell.", "interview_q": "Explain how wildcard expansion in commands like `tar *` can be weaponized by creating specially named files on the disk."}
            ]
        },
        {
            "week_num": 14,
            "week_id": "week-14-linux-privesc-advanced",
            "week_title": "Advanced Linux PrivEsc & Container Security",
            "objective": "Exploit Linux kernel vulnerabilities, NFS shares, shared libraries, container escapes, and establish persistent footholds.",
            "tools": ["HackTricks", "Dirty COW / PwnKit PoCs", "Docker", "deepce", "ssh-keygen", "chattr"],
            "major_concepts": ["Kernel Race Conditions", "NFS Root Squash", "Shared Object Hijacking", "Container Breakouts (docker.sock)", "Linux Persistence Mechanisms"],
            "weekly_lab": "Container Escape & Kernel Lab: Break out of a privileged Docker container via mounted host socket and establish root persistence.",
            "deliverable": "Container Security Audit Checklist & Linux Rootkit/Persistence Analysis",
            "days": [
                {"day_num": 66, "title": "Weak File Permissions, PATH Hijacking & Library Loading", "topics": ["Writable `/etc/passwd` exploitation: Generating password hashes with `openssl passwd -1` and adding root user", "Writable `/etc/shadow` file exploitation", "PATH variable manipulation: Relative vs absolute binary execution paths in scripts", "Shared library hijacking: RPATH/RUNPATH exploitation and `/etc/ld.so.conf.d/` inspection", "Security best practices for secure application compiling and packaging"], "objectives": "Exploit insecure file permissions on critical system configuration files and hijack search paths.", "lab": "Exploit a world-writable `/etc/passwd` file by appending an entry with UID 0; create a binary that calls an unqualified command and hijack it via PATH.", "interview_q": "If you discover that `/etc/passwd` is writable by your low-privileged user, what is the exact procedure to add a new root account?"},
                {"day_num": 67, "title": "Network File System (NFS) Misconfigurations — no_root_squash", "topics": ["Network File System (NFS) architecture and configuration (`/etc/exports`)", "The `root_squash` security control: Mapping remote root requests to `nobody`", "The `no_root_squash` misconfiguration and attack vector", "Mounting remote NFS shares locally as root: Creating an SUID binary and executing it on the target host", "Auditing NFS shares with `showmount -e <target_ip>`"], "objectives": "Identify NFS shares exported with `no_root_squash` and weaponize them to plant SUID executables.", "lab": "Enumerate an NFS export on a target VM, mount it locally, compile a C shell with SUID permissions, and execute it on the target to obtain root.", "interview_q": "What does the `no_root_squash` option in an NFS `/etc/exports` file mean, and how does an attacker leverage it for root privilege escalation?"},
                {"day_num": 68, "title": "Linux Kernel Exploitation — Dirty COW, PwnKit & Kernel Auditing", "topics": ["Kernel architecture, memory corruption, and race conditions in Linux", "Historical kernel exploits review: Dirty COW (CVE-2016-5195), PwnKit (CVE-2021-4034), Dirty Pipe (CVE-2022-0847)", "Kernel exploit triage: Matching kernel version (`uname -a`) against known CVE databases", "Risks of kernel exploits in operational environments (kernel panics, system crashes)", "Mitigations: Kernel Live Patching, disabling unprivileged user namespaces"], "objectives": "Safely evaluate and compile kernel exploits in isolated test environments while understanding system stability risks.", "lab": "Deploy a vulnerable kernel VM in an isolated network, compile and run the PwnKit (CVE-2021-4034) exploit, and inspect the resulting root shell.", "interview_q": "Why are kernel exploits considered a measure of last resort during authorized red team engagements, and what operational risks do they carry?"},
                {"day_num": 69, "title": "Docker & Container Breakouts — Mounted Docker Socket & Privileged Mode", "topics": ["Containerization fundamentals: Linux namespaces (PID, NET, MNT, UTS, IPC, USER) and Cgroups", "Assessing if you are inside a container: `/.dockerenv`, `/proc/1/cgroup` indicators", "The dangerous `/var/run/docker.sock` mount: Using the Docker API to spawn a container mounting the host root filesystem", "Privileged containers (`--privileged`): Exploiting host device access (`/dev/sda1`) and cgroups release_agent", "Auditing containers with `deepce`"], "objectives": "Determine container confinement and execute container breakout techniques to compromise the underlying host.", "lab": "Escape a container with access to `/var/run/docker.sock` by launching a privileged Alpine container mounting host root `/` and reading `/etc/shadow`.", "interview_q": "Why is giving a user access to the Docker group or mounting `/var/run/docker.sock` equivalent to granting full root access on the host system?"},
                {"day_num": 70, "title": "Linux Post-Exploitation & Persistence Mechanisms", "topics": ["Maintaining root access: Backdoored SSH keys (`~/.ssh/authorized_keys`), SSH user config", "Adding persistent root accounts and hiding accounts", "Systemd service persistence and timer units", "Shell profile backdoors (`/etc/profile`, `~/.bashrc`, `/etc/bash.bashrc`)", "Detecting and cleaning Linux persistence artifacts"], "objectives": "Establish durable, low-profile persistence across reboots on compromised Linux hosts.", "lab": "Configure three distinct persistence mechanisms on a Linux target (SSH key, systemd service, and cron job); practice forensic artifact removal.", "interview_q": "Name three different locations in Linux where an attacker can establish persistence that will trigger when an administrator logs in."}
            ]
        },
        {
            "week_num": 15,
            "week_id": "week-15-active-directory-foundations",
            "week_title": "Active Directory Architecture & Authentication",
            "objective": "Understand enterprise Active Directory architecture, LDAP querying, Kerberos protocol handshakes, NTLM authentication, and Kerberoasting.",
            "tools": ["PowerView", "AD Module", "SharpHound", "Rubeus", "hashcat", "Impacket (GetNPUsers, GetUserSPNs)"],
            "major_concepts": ["Forest & Domain Architecture", "Kerberos Handshake (AS/TGS)", "NTLMv2 vs Kerberos", "Active Directory LDAP Queries", "Service Principal Names (SPNs)", "Kerberoasting"],
            "weekly_lab": "Active Directory Enumeration & Kerberoasting Lab: Query domain objects via LDAP, identify service accounts with SPNs, extract TGS tickets, and crack them offline.",
            "deliverable": "Active Directory Architecture Blueprint & Kerberos Attack Playbook",
            "days": [
                {"day_num": 71, "title": "Active Directory Architecture — Forests, Domains, OUs & Global Catalog", "topics": ["Active Directory Domain Services (AD DS) components: Domain Controllers (DC), Forests, Trees, Domains", "Organizational Units (OUs), Groups (Security vs Distribution, Global vs Universal vs Domain Local)", "Active Directory Schema, Global Catalog (GC), and Flexible Single Master Operation (FSMO) roles", "Group Policy Objects (GPO) architecture and replication (SYSVOL)", "Default AD containers and built-in administrative groups (Domain Admins, Enterprise Admins, Schema Admins)"], "objectives": "Map enterprise AD hierarchies and understand the security boundaries of forests, domains, and trusts.", "lab": "Set up a test Active Directory Domain Controller in a virtual lab; create OUs, user accounts, and security groups to simulate an enterprise domain.", "interview_q": "Why is the Active Directory Domain boundary NOT considered a true security boundary, whereas the Forest boundary is?"},
                {"day_num": 72, "title": "Kerberos Authentication Protocol Deep Dive", "topics": ["Kerberos entities: Client, Key Distribution Center (KDC: Authentication Server + Ticket Granting Server)", "The 6-step Kerberos authentication process: AS-REQ, AS-REP, TGS-REQ, TGS-REP, AP-REQ, AP-REP", "Ticket Granting Ticket (TGT) structure, KRBTGT account role, and encryption keys", "Service Tickets (TGS) and Privilege Attribute Certificate (PAC) validation", "Kerberos error codes: KDC_ERR_PREAUTH_REQUIRED, KDC_ERR_C_PRINCIPAL_UNKNOWN"], "objectives": "Trace every step of the Kerberos authentication dance in Wireshark and explain ticket issuance and cryptographic verification.", "lab": "Capture and inspect raw Kerberos traffic in Wireshark during domain user login; identify AS-REQ, AS-REP, and TGS-REQ packet fields.", "interview_q": "Walk through the Kerberos authentication process from initial user login to accessing a network file share, explaining the roles of TGT and TGS tickets."},
                {"day_num": 73, "title": "NTLM Authentication Architecture & Protocol Mechanics", "topics": ["NTLM authentication overview: LM, NTLMv1, NTLMv2 hashes and NetNTLM challenge-response", "NTLM 3-way handshake: Type 1 (Negotiate), Type 2 (Challenge / Server Challenge), Type 3 (Authenticate)", "Where NTLM hashes are stored: SAM database (local accounts) and NTDS.dit (domain accounts)", "NetNTLMv1/v2 hash capture vs NTLM password hash extraction", "Why NetNTLM hashes cannot be used directly in Pass-the-Hash attacks"], "objectives": "Differentiate between an NTLM password hash stored in NTDS.dit and a NetNTLM challenge-response hash captured over the network.", "lab": "Use Responder in an isolated lab to capture a NetNTLMv2 challenge-response hash; examine the captured hash format and crack it using hashcat.", "interview_q": "What is the critical difference between an NTLM hash and a NetNTLMv2 hash, and which one can be utilized in a Pass-the-Hash attack?"},
                {"day_num": 74, "title": "Active Directory Enumeration — LDAP, PowerView & SharpHound", "topics": ["Lightweight Directory Access Protocol (LDAP) querying fundamentals", "Using native PowerShell commands: Get-ADUser, Get-ADComputer, Get-ADGroupMember", "PowerView (PowerSploit) syntax: Get-DomainUser, Get-DomainComputer, Find-LocalAdminAccess", "SharpHound data collection: Gathering sessions, local admins, group memberships, and object ACLs", "OPSEC considerations when running SharpHound in production environments"], "objectives": "Enumerate Active Directory domain objects, privileged memberships, and active user sessions using LDAP and SharpHound.", "lab": "Run PowerView and SharpHound collection against the test domain; export data and verify domain controller LDAP query logging.", "interview_q": "How does SharpHound collect user session data from domain computers, and what network ports and protocols does it interact with?"},
                {"day_num": 75, "title": "Service Principal Names (SPNs) & Kerberoasting Exploitation", "topics": ["What is a Service Principal Name (SPN) and why service accounts require them", "Kerberoasting attack theory: Any authenticated domain user can request a TGS for any SPN", "Extracting TGS tickets: TGS is encrypted with the service account's password hash", "Tools: Impacket `GetUserSPNs.py`, Rubeus `kerberoast`, PowerView", "Cracking TGS hashes offline with hashcat (`hashcat -m 13100`) and defensive mitigations (gMSAs, long passwords)"], "objectives": "Execute a complete Kerberoasting attack from SPN enumeration to offline hash cracking.", "lab": "Create an SPN for a service account with a weak password, request the TGS ticket using Rubeus, extract the hash, and crack it with hashcat.", "interview_q": "Why does Kerberoasting not require administrative privileges on the domain, and what is the primary defensive mitigation against it?"}
            ]
        },
        {
            "week_num": 16,
            "week_id": "week-16-active-directory-attacks",
            "week_title": "Active Directory Attack Paths & Delegation",
            "objective": "Master AS-REP Roasting, BloodHound graph analysis, Active Directory Certificate Services (AD CS) exploitation, delegation attacks, and DCSync.",
            "tools": ["BloodHound", "Neo4j", "Certify", "Certipy", "Rubeus", "Impacket (secretsdump, GetNPUsers)", "CrackMapExec"],
            "major_concepts": ["AS-REP Roasting", "Attack Path Graph Theory", "AD CS Misconfigurations (ESC1-ESC8)", "Kerberos Delegation (Unconstrained/Constrained/RBCD)", "DCSync & DRSUAPI"],
            "weekly_lab": "Active Directory Attack Path Lab: Ingest SharpHound data into BloodHound, map shortest path to Domain Admin, exploit AD CS ESC1, and execute DCSync.",
            "deliverable": "BloodHound Attack Path Analysis & Domain Escalation Matrix",
            "days": [
                {"day_num": 76, "title": "AS-REP Roasting — Targeting Accounts Without Pre-Authentication", "topics": ["Kerberos Pre-Authentication mechanics and replay attack prevention", "The `DONT_REQ_PREAUTH` user account control flag", "AS-REP Roasting theory: Requesting AS-REP directly from KDC without knowing the password", "Extracting encrypted AS-REP blobs with Impacket `GetNPUsers.py` and Rubeus `asreproast`", "Offline cracking of AS-REP hashes (`hashcat -m 18200`) and defensive auditing"], "objectives": "Identify domain accounts configured without Kerberos pre-authentication and crack their passwords offline.", "lab": "Configure a test domain user with 'Do not require Kerberos preauthentication', extract the AS-REP blob using GetNPUsers.py, and crack it.", "interview_q": "What security protection does Kerberos Pre-Authentication provide, and what happens when it is disabled on a domain user account?"},
                {"day_num": 77, "title": "Graph Theory in AD — BloodHound & Attack Path Analysis", "topics": ["Active Directory permissions as a directed graph: Nodes (Users, Computers, Groups) and Edges (Permissions)", "Setting up BloodHound and Neo4j graph database", "Ingesting SharpHound JSON output into BloodHound", "Analyzing critical edges: GenericAll, WriteDacl, GenericWrite, ForceChangePassword, MemberOf", "Finding the Shortest Paths to Domain Admins and High-Value Targets"], "objectives": "Visualize complex Active Directory trust and permission relationships using BloodHound to discover hidden escalation paths.", "lab": "Import SharpHound telemetry into BloodHound; run Cypher queries to discover indirect group memberships and ACL abuse paths to Domain Admin.", "interview_q": "Explain what the `GenericAll` permission over a domain user object allows an attacker to do according to BloodHound's edge definition."},
                {"day_num": 78, "title": "Active Directory Certificate Services (AD CS) Exploitation", "topics": ["Public Key Infrastructure in Active Directory: AD CS role and Certificate Templates", "The Certified Pre-Owned research: Certificate template misconfigurations", "ESC1 exploitation: Client Authentication EKU + Enrollee Supplies Subject (SAN) + Low-priv enrollment", "Tools: Certify.exe and Certipy for certificate enumeration and enrollment", "Requesting a certificate as Domain Administrator and authenticating via PKINIT to obtain a TGT"], "objectives": "Enumerate vulnerable certificate templates in Active Directory and escalate privileges to Domain Administrator via ESC1.", "lab": "Deploy AD CS in the lab, configure an ESC1-vulnerable template, request a certificate impersonating Administrator with Certipy, and request a TGT.", "interview_q": "Explain the root conditions that make an Active Directory Certificate Services template vulnerable to the ESC1 privilege escalation attack."},
                {"day_num": 79, "title": "Kerberos Delegation — Unconstrained, Constrained & RBCD", "topics": ["Kerberos delegation concepts: Impersonating users across multi-tier applications (Web -> DB)", "Unconstrained Delegation: Harvesting stored TGTs from compromised computer memory", "Constrained Delegation: S4U2Self and S4U2Proxy extensions and abusing protocol transition", "Resource-Based Constrained Delegation (RBCD): Writing to `msDS-AllowedToActOnBehalfOfOtherIdentity`", "Tools: Rubeus `s4u`, Impacket `rbcd.py`"], "objectives": "Differentiate between delegation types and exploit Resource-Based Constrained Delegation to take over domain assets.", "lab": "Configure Resource-Based Constrained Delegation on a target computer account and execute a Rubeus S4U attack to obtain a service ticket as Administrator.", "interview_q": "How does Resource-Based Constrained Delegation (RBCD) differ from traditional Constrained Delegation, and what attribute controls it?"},
                {"day_num": 80, "title": "Domain Dominance — DCSync Attack (`DRSUAPI`), Golden & Silver Tickets", "topics": ["Replication architecture in Active Directory: Directory Replication Service Remote Protocol (DRSUAPI)", "The DCSync attack: Requesting password hashes using `DS-Replication-Get-Changes-All` permissions", "Executing DCSync with Mimikatz `lsadump::dcsync` and Impacket `secretsdump.py`", "Golden Tickets: Forging TGTs using the KRBTGT NTLM hash or AES key (lifetime, PAC claims)", "Silver Tickets: Forging service-specific TGS tickets without KDC interaction"], "objectives": "Execute a DCSync attack to dump all domain password hashes and forge persistence tickets.", "lab": "Execute `secretsdump.py` with Domain Admin credentials to DCSync the `krbtgt` account hash, then construct a Golden Ticket using Rubeus.", "interview_q": "What specific Active Directory permissions are required to successfully execute a DCSync attack, and what does the attack actually do?"}
            ]
        },
        {
            "week_num": 17,
            "week_id": "week-17-windows-privesc",
            "week_title": "Windows Privilege Escalation",
            "objective": "Master local Windows privilege escalation: Service misconfigurations, unquoted service paths, registry autostarts, token impersonation, and UAC bypasses.",
            "tools": ["WinPEAS", "Seatbelt", "SharpUp", "PowerUp", "PrintSpoofer", "GodPotato", "Process Hacker", "AccessChk"],
            "major_concepts": ["Unquoted Service Paths", "Weak Service Permissions", "Registry Autostarts", "Token Impersonation (SeImpersonate)", "UAC Bypass Mechanics"],
            "weekly_lab": "Windows Privilege Escalation Lab: Identify and exploit unquoted service paths, hijack modifiable service binaries, and abuse SeImpersonatePrivilege to reach SYSTEM.",
            "deliverable": "Windows Privilege Escalation Triage Matrix & Exploit Walkthroughs",
            "days": [
                {"day_num": 81, "title": "Windows Local Enumeration — WinPEAS, Seatbelt & LOLBAS", "topics": ["Automated Windows enumeration tools: WinPEAS, Seatbelt, SharpUp, PowerUp", "Manual Windows host enumeration: `systeminfo`, `wmic`, `reg query`, `net user`, `sc query`", "Auditing permissions with Sysinternals `accesschk.exe`", "Living-off-the-land techniques (LOLBAS) for enumeration without uploading foreign tools", "Identifying missing security patches and build versions (`wmic qfe`)"], "objectives": "Conduct systematic local enumeration on Windows hosts to discover exploitable configurations.", "lab": "Execute manual enumeration commands and WinPEAS against a Windows VM; catalog all services, file permissions, and installed applications.", "interview_q": "Why is running `whoami /all` or `net localgroup administrators` immediately upon landing on a Windows host an OPSEC risk, and what quieter alternatives exist?"},
                {"day_num": 82, "title": "Windows Service Exploitation — Unquoted Paths & Weak Permissions", "topics": ["How Windows parses unquoted service executable paths with spaces (e.g. `C:\\Program Files\\My App\\service.exe`)", "Exploiting unquoted paths: Planting an executable at `C:\\Program.exe` or `C:\\Program Files\\My.exe`", "Weak service DACLs: `SERVICE_CHANGE_CONFIG` and `SERVICE_ALL_ACCESS` permissions", "Modifying service binary paths (`binpath=`) using `sc.exe config`", "Service restart privileges: `SERVICE_START` and `SERVICE_STOP`"], "objectives": "Identify and exploit unquoted service paths and services with modifiable configurations to gain SYSTEM access.", "lab": "Configure a vulnerable unquoted service on Windows; plant a malicious payload binary, restart the service, and verify a SYSTEM shell.", "interview_q": "Explain step-by-step how the Windows operating system searches for an executable when an unquoted service path with spaces is registered in the SCM."},
                {"day_num": 83, "title": "Registry Exploitation — AlwaysInstallElevated & Autostart Keys", "topics": ["The `AlwaysInstallElevated` registry policy (`HKCU` and `HKLM` policies)", "Generating malicious MSI packages with msfvenom (`msfvenom -p windows/x64/shell_reverse_tcp ... -f msi`)", "Modifiable Registry service keys (`HKLM\\SYSTEM\\CurrentControlSet\\Services`)", "Startup folders and Run / RunOnce registry keys", "Auditing registry ACLs for write permissions granted to standard users"], "objectives": "Elevate privileges using policy misconfigurations like AlwaysInstallElevated and writable registry service definitions.", "lab": "Enable AlwaysInstallElevated in local group policy; craft a weaponized MSI installer, execute it with msiexec, and capture an elevated shell.", "interview_q": "What two registry keys must be set to `1` for the AlwaysInstallElevated privilege escalation technique to work?"},
                {"day_num": 84, "title": "Token Impersonation Privileges — SeImpersonate & SeAssignPrimaryToken", "topics": ["Understanding Windows Token privileges: Why service accounts hold token privileges", "The `SeImpersonatePrivilege` and `SeAssignPrimaryTokenPrivilege` rights", "The history of Potato exploits: RottenPotato, JuicyPotato, SweetPotato, PrintSpoofer, GodPotato", "Abusing named pipes and DCOM to coerce SYSTEM authentication to a local rogue pipe", "Executing commands as `NT AUTHORITY\\SYSTEM`"], "objectives": "Escalate from service accounts (e.g. IIS / SQL Server) to full SYSTEM access using named pipe impersonation.", "lab": "Configure a test web service running as `NETWORK SERVICE` with SeImpersonatePrivilege; execute PrintSpoofer / GodPotato to spawn a SYSTEM shell.", "interview_q": "How does PrintSpoofer / GodPotato abuse `SeImpersonatePrivilege` to trick a privileged Windows process into authenticating to a named pipe controlled by the attacker?"},
                {"day_num": 85, "title": "User Account Control (UAC) Bypass Techniques & DLL Hijacking", "topics": ["UAC integrity levels: Low, Medium, High, System", "Auto-elevating Windows binaries (binaries with `autoElevate = true` manifest)", "UAC bypass techniques: Mock trusted directories, DLL hijacking in auto-elevating binaries, Fodhelper, ComputerDefaults", "DLL search order hijacking on Windows (`KnownDLLs`, application directory, system32)", "Remediation: Setting UAC slider to 'Always Notify'"], "objectives": "Bypass User Account Control to escalate from Medium integrity to High integrity without user interaction prompts.", "lab": "Demonstrate a UAC bypass using the Fodhelper registry hijacking method to elevate a medium-integrity PowerShell session to High integrity.", "interview_q": "Why does setting the UAC slider to 'Always Notify' prevent silent auto-elevate UAC bypass techniques from succeeding?"}
            ]
        },
        {
            "week_num": 18,
            "week_id": "week-18-lateral-movement",
            "week_title": "Lateral Movement & Internal Pivoting",
            "objective": "Harvest credentials with Mimikatz, perform Pass-the-Hash/Ticket, execute remote commands via SMB/WMI/WinRM, and coerce authentication.",
            "tools": ["Mimikatz", "nanodump", "CrackMapExec / NetExec", "Impacket (psexec, wmiexec, smbexec)", "evil-winrm", "Coercer", "PetitPotam", "Responder"],
            "major_concepts": ["LSASS Memory Protection", "Pass-the-Hash (PtH)", "Pass-the-Ticket (PtT)", "Remote Execution Mechanics", "Authentication Coercion", "NTLM Relaying"],
            "weekly_lab": "Deliverable 3 Lab: Build multi-node AD lab, capture beachhead, dump LSASS, pass hash to secondary server, coerce DC auth, and claim domain compromise.",
            "deliverable": "Deliverable 3: Corporate Active Directory Lab & Compromise Path Documentation",
            "days": [
                {"day_num": 86, "title": "Credential Harvesting — Mimikatz, LSASS Memory Dumping & DPAPI", "topics": ["LSASS architecture and credential caching: WDigest, Kerberos tickets, NTLM hashes in memory", "Dumping LSASS memory: Mimikatz `sekurlsa::logonpasswords`", "Defense evasion LSASS dumping: `nanodump`, Sysinternals `procdump.exe`, Task Manager minidump", "Windows Protected Process Light (PPL) and Credential Guard overview", "Data Protection API (DPAPI): Decrypting browser passwords and stored credentials using `dploot`"], "objectives": "Extract cleartext passwords, NTLM hashes, and Kerberos tickets from memory and decrypt DPAPI blobs.", "lab": "Dump the LSASS process on a test workstation using procdump to evade basic AV; parse the minidump file offline using pypykatz on Kali.", "interview_q": "What is RunAsPPL (Protected Process Light) for LSASS, and how does it prevent standard administrative tools from opening handles to LSASS memory?"},
                {"day_num": 87, "title": "Pass-the-Hash (PtH), Overpass-the-Hash & Pass-the-Ticket (PtT)", "topics": ["Pass-the-Hash (PtH) theory: Using NTLM hashes directly in NTLM authentication without cracking", "Overpass-the-Hash (Pass-the-Key): Exchanging an NTLM hash for a valid Kerberos TGT (Rubeus `asktgt`)", "Pass-the-Ticket (PtT): Injecting captured/forged Kerberos tickets into the current logon session (Rubeus `ptt`)", "Executing PtH with CrackMapExec / NetExec and Impacket", "Mitigations: Restricted Admin mode for RDP, disabling NTLM, Protected Users group"], "objectives": "Pivot across network systems using extracted password hashes and tickets without knowledge of the cleartext password.", "lab": "Use CrackMapExec with an extracted NTLM hash to authenticate to multiple domain workstations; inject a Kerberos ticket into a session with Rubeus.", "interview_q": "Why does Pass-the-Hash work against remote services, and what change does adding a user to the 'Protected Users' Active Directory group make?"},
                {"day_num": 88, "title": "Remote Execution Protocols — SMB (PsExec), WMI & WinRM", "topics": ["PsExec mechanics: Uploading a service binary, creating a service over RPC, connecting to named pipe (EID 7045)", "Smbexec mechanics: Executing commands via cmd.exe echo output redirection without service binaries", "WMI / DCOM remote execution (`wmiexec.py`, `wmic`): Creating processes via Win32_Process.Create", "WinRM and PowerShell Remoting: TCP port 5985/5986 and `evil-winrm` shell", "Comparing detection footprints and artifacts of PsExec vs WMI vs WinRM"], "objectives": "Execute remote commands across network targets using SMB, WMI, and WinRM while analyzing the forensic footprints generated.", "lab": "Connect to a target server using `evil-winrm`, execute remote commands via `wmiexec.py`, and inspect Sysmon Event ID 1 on the destination.", "interview_q": "Compare the forensic artifacts left on a target machine by PsExec versus WmiExec. Which is quieter and why?"},
                {"day_num": 89, "title": "Authentication Coercion & NTLM Relay Attacks", "topics": ["Authentication coercion concept: Forcing a remote Windows server to authenticate back to the attacker", "Coercion protocols: MS-EFSRPC (PetitPotam), MS-RPRN (PrinterBug), MS-DFSNM", "NTLM Relay attacks: Relaying captured authentication to SMB (requires SMB signing disabled) or LDAP/HTTP", "Relaying coerced machine accounts to AD CS HTTP enrollment endpoints (ESC8) to obtain domain admin certificates", "Tools: `Coercer`, `PetitPotam.py`, `ntlmrelayx.py`"], "objectives": "Coerce machine authentication from remote domain controllers and relay the credentials to compromise services.", "lab": "Set up ntlmrelayx targeting an AD CS web enrollment endpoint; trigger PetitPotam against a test server to relay machine auth and receive a certificate.", "interview_q": "Why does SMB signing prevent NTLM relay attacks against SMB servers, and why is SMB signing often disabled on workstations by default?"},
                {"day_num": 90, "title": "Phase 3 Capstone Deliverable — Corporate Active Directory Lab", "topics": ["Finalizing the multi-node corporate Active Directory lab environment", "Documenting the complete attack chain: Initial low-priv host compromise -> Local PrivEsc -> Mimikatz dump -> Lateral Movement -> AD CS ESC1 / Delegation -> Domain Admin", "Verifying detection opportunities: Event IDs generated at each step of the compromise path", "Authoring the comprehensive Deliverable 3 lab documentation and network diagram", "Restoring snapshots and establishing automated reset procedures for future testing"], "objectives": "Complete and document Deliverable 3: A fully functional Corporate Active Directory Lab with validated end-to-end attack paths.", "lab": "Execute the entire attack chain from an unprivileged domain account to Domain Admin in the lab, capturing screenshots and logs for Deliverable 3.", "interview_q": "If you had to recommend the top three most impactful Active Directory hardening measures to an enterprise, which would you choose and why?"}
            ]
        }
    ]
})

print(f"[*] Added Phase 3. Total phases: {len(phases)}. Proceeding to Phase 4-9...")
