"""
Curriculum Generator Part 4:
Defines Phase 6 (Blue Team / SOC), Phase 7 (Malware & DFIR),
Phase 8 (Security Programming & Rust), and Phase 9 (Purple Team & Capstone).
"""

phases_6_9 = [
    # PHASE 6 (Weeks 28-32, Days 136-160)
    {
        "phase_num": 6,
        "phase_id": "phase-06-blue-team",
        "phase_title": "Blue Team + SOC + Threat Hunting",
        "weeks_range": "Weeks 28–32",
        "days_range": "Days 136–160",
        "objective": "Master security operations, enterprise telemetry collection, SIEM deployment and log normalization, detection engineering with Sigma and MITRE ATT&CK, hypothesis-driven threat hunting, and incident response triage.",
        "skills": ["Windows Security & Sysmon telemetry", "Linux auditd & system logs", "SIEM architecture & deployment (Wazuh/Elastic)", "Writing Sigma detection rules & pipeline conversion", "Threat hunting hypotheses & IOC/IOA pivoting", "Incident response triage & containment strategies"],
        "tools": ["BlueTeam-Tools", "Wazuh", "Sysmon", "Elasticsearch / Kibana", "Sigma / pySigma", "Atomic Red Team", "Zeek", "Suricata", "Velociraptor", "Wireshark"],
        "project_id": "project-06-soc-detection-lab",
        "project_title": "SOC & Detection Engineering Lab (Wazuh SIEM + Sysmon Telemetry + Custom Sigma Rules + Atomic Validation)",
        "weeks": [
            {
                "week_num": 28,
                "week_id": "week-28-security-monitoring-telemetry",
                "week_title": "Security Telemetry & Endpoint Visibility",
                "objective": "Collect and analyze endpoint security telemetry from Windows Security logs, Sysmon events, Linux auditd, and network monitors.",
                "tools": ["Sysmon", "auditd", "Zeek", "Suricata", "Event Viewer", "PowerShell"],
                "major_concepts": ["Windows Event Log Channels", "Sysmon Configuration Schema", "Linux Audit Framework", "Network Flow & DNS Telemetry", "Telemetry Gap Analysis"],
                "weekly_lab": "Telemetry Ingestion Lab: Configure advanced Windows auditing, deploy customized Sysmon schema, and configure Linux auditd rules for process monitoring.",
                "deliverable": "Enterprise Telemetry Baseline & Collection Blueprint",
                "days": [
                    {"day_num": 136, "title": "Windows Event Logging Architecture & Channel Configuration", "topics": ["Windows Event Log internals: Windows Event Forwarding (WEF), subscriptions, and collectors", "Critical Windows Security Log Event IDs: 4624 (Logon Types 2, 3, 7, 10), 4625 (Failed Logon), 4672, 4720 (User Created), 4728 (Group Member Added)", "Object access auditing: File system SACLs, Registry SACLs, and Event ID 4663", "PowerShell auditing: Script Block Logging (4104), Transcription, Module Logging (4103)", "Configuring group policies for centralized audit logging"], "objectives": "Configure comprehensive Windows audit policies and interpret critical authentication and process events.", "lab": "Configure Windows Advanced Audit Policies; simulate user logon, account creation, and script execution, and verify event generation.", "interview_q": "What is the difference between Windows Logon Type 2 (Interactive) and Logon Type 3 (Network), and which one indicates SMB/network share access?"},
                    {"day_num": 137, "title": "Sysmon Deep Dive — Process, Network & Memory Telemetry", "topics": ["Sysmon architecture, kernel-mode driver, and user-mode service", "Sysmon Event ID 1: Process Creation (CommandLine, ParentCommandLine, ParentImage, Hashes)", "Sysmon Event ID 3: Network Connection (Destination IP, Port, Process)", "Sysmon Event ID 7: Image Loaded (DLLs loaded into processes)", "Sysmon Event ID 10: Process Access (TargetProcess, GrantedAccess masks - detecting LSASS dumping)", "Sysmon Event ID 11: File Create (Detecting dropped executables)"], "objectives": "Analyze process relationships, DLL injections, and memory access attempts using Sysmon event logs.", "lab": "Analyze Sysmon logs generated when dumping LSASS with Task Manager; identify Event ID 10 with `GrantedAccess: 0x1010`.", "interview_q": "How does Sysmon Event ID 10 (ProcessAccess) help a SOC analyst detect credential dumping attacks targeting the LSASS process?"},
                    {"day_num": 138, "title": "Linux System Auditing — auditd, rules & ausearch", "topics": ["The Linux Audit Framework (auditd, auditctl, ausearch, aureport)", "Configuring `/etc/audit/auditd.conf` and writing custom `/etc/audit/rules.d/audit.rules`", "Monitoring file modifications: Watching `/etc/passwd`, `/etc/shadow`, and `/etc/sudoers`", "Monitoring system calls: Tracking `execve` to log all command executions with full arguments", "Analyzing audit records: Mapping `uid`, `euid`, `cwd`, and `comm` in `ausearch`"], "objectives": "Configure the Linux audit framework to record unauthorized file modifications and sensitive system calls.", "lab": "Author custom auditd rules to monitor `/etc/shadow` access and all `execve` syscalls; test unauthorized access and parse results with `ausearch`.", "interview_q": "How do you configure an auditd rule to monitor any modifications made to the `/etc/sudoers` file and what key fields are generated?"},
                    {"day_num": 139, "title": "Network Telemetry & DNS Logging — Zeek & Suricata", "topics": ["Network Security Monitoring (NSM) vs Endpoint Detection and Response (EDR)", "Zeek (formerly Bro) architecture: Protocol parsers, connection logs (`conn.log`), HTTP (`http.log`), DNS (`dns.log`), SSL (`ssl.log`)", "Suricata signature-based intrusion detection engine (IDS) and rule syntax", "Detecting DNS anomalies: High query volume, long domain names (DNS tunneling), NXDOMAIN spikes", "Correlating endpoint telemetry with network connections"], "objectives": "Analyze Zeek network connection logs and write Suricata rules to detect suspicious outbound communications.", "lab": "Run Zeek on a PCAP containing C2 beaconing traffic; inspect `dns.log` and `conn.log` to identify the command-and-control channel.", "interview_q": "What specific log fields in Zeek's `conn.log` and `dns.log` provide immediate evidence of a malware infection on an internal endpoint?"},
                    {"day_num": 140, "title": "Endpoint Visibility Assessment & Telemetry Gap Analysis", "topics": ["Evaluating detection coverage: Identifying blind spots across operating systems", "Mapping available telemetry against the MITRE ATT&CK Matrix", "Assessing log retention policies, disk consumption, and transmission bandwidth", "Handling event volume: Filtering high-volume noise without losing security signals", "Developing a corporate endpoint logging standard"], "objectives": "Conduct a structured gap analysis to identify blind spots in endpoint telemetry.", "lab": "Execute 5 distinct attack techniques (LOLBAS download, privilege escalation, user creation); verify which events were captured in logs and which were missed.", "interview_q": "How do you balance the requirement for deep endpoint visibility (such as Sysmon ImageLoad logging) against system performance and log storage constraints?"}
                ]
            },
            {
                "week_num": 29,
                "week_id": "week-29-siem-log-analytics",
                "week_title": "SIEM Architecture & Log Analytics",
                "objective": "Deploy and operate an enterprise SIEM (Wazuh / Elastic), configure log ingestion pipelines, normalize data schemas, and design monitoring dashboards.",
                "tools": ["Wazuh", "Elasticsearch", "Kibana", "Logstash / Filebeat", "BlueTeam-Tools"],
                "major_concepts": ["SIEM Architecture", "Wazuh Agent/Manager Model", "Elastic Common Schema (ECS)", "Custom Decoders & Rules", "SOC Dashboard Design"],
                "weekly_lab": "SIEM Deployment Lab: Deploy Wazuh Manager and agents across Windows and Linux targets, ingest Sysmon and auditd logs, and build an alert dashboard.",
                "deliverable": "SIEM Deployment Blueprint & Custom Decoder Repository",
                "days": [
                    {"day_num": 141, "title": "SIEM Architecture — Wazuh & Elastic Stack Overview", "topics": ["The role of a Security Information and Event Management (SIEM) system in the modern SOC", "Wazuh architecture: Wazuh Manager, Wazuh Indexer, Wazuh Dashboard, Wazuh Agents", "The Elastic Stack (ELK): Elasticsearch indexing, Logstash parsing, Kibana visualization", "Agent communication protocols: Encrypted TLS transport, registration, and health monitoring", "Event ingestion flow: Endpoint -> Agent -> Manager -> Analysis Engine -> Indexer -> Dashboard"], "objectives": "Deploy and configure a centralized open-source SIEM infrastructure for enterprise log aggregation.", "lab": "Deploy a Wazuh single-node manager in a virtual environment; access the web dashboard and verify indexer health.", "interview_q": "Explain the architectural components of a modern SIEM platform and how data flows from an endpoint event to a SOC analyst alert."},
                    {"day_num": 142, "title": "Deploying & Configuring Wazuh Agents Across Endpoints", "topics": ["Wazuh Agent deployment on Windows: Silent MSI installation, manager IP assignment, registration keys", "Wazuh Agent deployment on Linux: DEB/RPM repositories and agent configuration (`/var/ossec/etc/ossec.conf`)", "Configuring log collection channels (`localfile` blocks): Windows Event Channels, Sysmon, Linux `/var/log/auth.log`", "File Integrity Monitoring (FIM / `syscheck`): Real-time directory monitoring and hash checking", "Rootcheck and vulnerability detection module configuration"], "objectives": "Enroll Windows and Linux lab machines into Wazuh and verify active log forwarding.", "lab": "Install Wazuh agents on a Windows VM and a Linux VM; configure log ingestion for Sysmon and auditd, and verify agent connectivity.", "interview_q": "How does File Integrity Monitoring (FIM) in an agent like Wazuh detect unauthorized modifications to critical system binaries?"},
                    {"day_num": 143, "title": "Log Ingestion, Normalization & Elastic Common Schema (ECS)", "topics": ["The challenge of heterogeneous log formats: Syslog, JSON, XML, EVTX, CEF", "Data normalization principles: Field mapping, type casting, timestamp synchronization (UTC)", "The Elastic Common Schema (ECS): Standardized field naming conventions (`process.name`, `source.ip`, `user.name`)", "Parsing logs with Logstash / Ingest Pipelines / Wazuh Decoders", "Writing Grok patterns for custom application log parsing"], "objectives": "Normalize disparate log formats into standardized schema fields to enable cross-platform correlation.", "lab": "Write a custom Logstash / Wazuh Grok pattern to parse an unformatted web proxy log into standardized ECS fields.", "interview_q": "Why is data normalization to a standard schema like ECS or CEF essential before attempting to write correlation rules in a SIEM?"},
                    {"day_num": 144, "title": "Writing Custom Wazuh Decoders & Detection Rules", "topics": ["Wazuh analysis engine: Decoders (`/var/ossec/etc/decoders/local_decoder.xml`) and Rules (`local_rules.xml`)", "XML rule syntax: `<rule id=\"...\" level=\"...\">`, `<if_sid>`, `<match>`, `<regex>`, `<field>`", "Alert severity levels (Level 0: Ignored, Level 5: User generated, Level 10: Attack detected, Level 15: Critical)", "Writing parent-child rules: Correlating multiple events within a time window (`timeframe`, `frequency`)", "Testing custom rules with `wazuh-logtest`"], "objectives": "Author custom Wazuh decoders and correlation rules to detect novel threat patterns.", "lab": "Use `wazuh-logtest` to write and test a custom Wazuh rule alerting when a user attempts 5 failed SSH logins within 60 seconds.", "interview_q": "How does the `wazuh-logtest` utility allow detection engineers to validate custom decoders and rules before deploying them to production?"},
                    {"day_num": 145, "title": "SIEM Dashboard Engineering — Visualizing SOC Operations", "topics": ["Designing intuitive, actionable SOC dashboards in Kibana / Wazuh Dashboard", "Key visualizations: Authentication success vs failure trends, top targeted usernames, process creation outliers", "Geographic mapping of inbound external connections", "Filtering out benign enterprise noise: Creating persistent dashboard exclusion filters", "Building saved searches and alert review queues for Tier-1 SOC analysts"], "objectives": "Build professional, real-time security monitoring dashboards to visualize threat telemetry.", "lab": "Create a customized SOC operations dashboard displaying failed logon spikes, suspicious PowerShell executions, and top destination IPs.", "interview_q": "What key metrics and visualizations should be front-and-center on a Tier-1 SOC analyst's primary monitoring dashboard?"}
                ]
            },
            {
                "week_num": 30,
                "week_id": "week-30-detection-engineering",
                "week_title": "Detection Engineering with Sigma & ATT&CK",
                "objective": "Design, write, test, and automate detection rules using the open-source Sigma standard mapped to the MITRE ATT&CK framework.",
                "tools": ["Sigma", "pySigma", "Atomic Red Team", "Wazuh", "Sysmon", "BlueTeam-Tools"],
                "major_concepts": ["Sigma Rule Architecture", "pySigma Translation Pipeline", "Detecting LOLBAS Execution", "Detecting Credential Access", "Atomic Testing Validation"],
                "weekly_lab": "Detection Engineering Lab: Write Sigma rules for PsExec service creation and LSASS access; translate to Wazuh/Elastic; validate with Atomic Red Team.",
                "deliverable": "Sigma Detection Rule Suite (Rules, ATT&CK mapping, and validation logs)",
                "days": [
                    {"day_num": 146, "title": "Introduction to Sigma Rules — The Universal Detection Standard", "topics": ["The problem of vendor lock-in with proprietary SIEM query languages (KQL, SPL, Lucene, SQL)", "Sigma architecture: Open-source, vendor-agnostic signature format for log events written in YAML", "Sigma rule structure: Title, ID, Status, Description, References, Author, Date, Logsource, Detection, Condition, Level, Tags", "Mapping to MITRE ATT&CK: Using `attack.t1059.001` taxonomy tags", "Translating Sigma rules with pySigma CLI to Elasticsearch, Splunk, and Wazuh queries"], "objectives": "Author standardized, vendor-agnostic detection rules using the Sigma YAML specification.", "lab": "Write a Sigma rule that detects `certutil.exe` downloading files via the command line; convert it to an Elasticsearch query using pySigma.", "interview_q": "What problem does the Sigma rule standard solve for detection engineering teams operating across heterogeneous or migrating SIEM platforms?"},
                    {"day_num": 147, "title": "Detecting Execution Techniques — LOLBAS & Command Line Bypasses", "topics": ["Analyzing adversary execution techniques (MITRE ATT&CK T1059, T1218)", "Writing Sigma rules for living-off-the-land binaries (certutil, mshta, regsvr32, rundll32, bitsadmin)", "Detecting encoded PowerShell commands (`-enc`, `-EncodedCommand`, base64 string padding)", "Parent-child process anomalies: Office applications (word.exe) or web servers (w3wp.exe) spawning cmd.exe or powershell.exe", "Tuning false positives: Handling legitimate administrative scripts"], "objectives": "Construct high-fidelity detection rules targeting malicious process execution and suspicious command-line flags.", "lab": "Write a Sigma rule detecting suspicious parent-child process relationships (e.g. `winword.exe` spawning `powershell.exe`); test against simulated logs.", "interview_q": "Why is alerting on `powershell.exe` execution alone ineffective in corporate environments, and how do parent process filters solve this?"},
                    {"day_num": 148, "title": "Detecting Credential Access — LSASS Dumping & SAM Secrets", "topics": ["Analyzing credential dumping behaviors (MITRE ATT&CK T1003)", "Writing detection rules for LSASS handle access: Sysmon Event ID 10 with `GrantedAccess` masks (0x1010, 0x1F0FFF, 0x1410)", "Detecting SAM and SYSTEM registry hive saves via `reg.exe save`", "Detecting comsvcs.dll MiniDump exports (`rundll32.exe comsvcs.dll, MiniDump`)", "Alerting on volume shadow copy creation for NTDS.dit theft (`vssadmin create shadow`)"], "objectives": "Engineer detection logic to alert on LSASS memory access, minidump creation, and registry credential dumping.", "lab": "Author a Sigma rule targeting comsvcs.dll LSASS minidump command lines; convert and deploy to your SIEM.", "interview_q": "Explain how the `rundll32.exe comsvcs.dll, MiniDump` command dumps LSASS memory, and what detection logic captures it without relying on process names."},
                    {"day_num": 149, "title": "Detecting Lateral Movement — SMB, PsExec & Remote WMI", "topics": ["Analyzing lateral movement telemetry (MITRE ATT&CK T1021, T1047, T1569.002)", "Detecting PsExec activity: Service installation (System Event ID 7045) with default service names (`PSEXESVC`) and named pipes", "Detecting WMI remote execution: Process creation of `WmiPrvSE.exe` spawning command interpreters", "Detecting WinRM remoting sessions: Network connections to port 5985/5986 paired with `wsmprovhost.exe` execution", "Detecting Pass-the-Hash: Event ID 4624 Logon Type 9 (NewCredentials)"], "objectives": "Write detection rules for the common network and endpoint signatures generated during lateral movement.", "lab": "Author a Sigma rule that detects remote service creation via Event ID 7045 containing suspicious executable paths; test against lab logs.", "interview_q": "What specific Windows Event ID is generated when a new service is installed on a host, and why is this event critical for catching PsExec?"},
                    {"day_num": 150, "title": "Detection Validation with Atomic Red Team", "topics": ["The detection engineering lifecycle: Hypothesis -> Develop Rule -> Unit Test -> Deploy -> Continuous Validation", "Atomic Red Team framework: Library of scripted, single-technique tests mapped directly to MITRE ATT&CK", "Using `Invoke-AtomicTest` in PowerShell to execute controlled tests", "Validating rule efficacy: Did the Atomic test generate the expected telemetry, and did the SIEM fire an alert?", "Calculating True Positive and False Positive ratios"], "objectives": "Validate detection rules automatically using scripted Atomic Red Team attack simulations.", "lab": "Execute the Atomic test for T1003.001 (LSASS memory dumping) in a controlled VM; verify that your custom detection rule fired as expected.", "interview_q": "How does integrating Atomic Red Team into a CI/CD pipeline ensure that newly developed detection rules do not suffer from regression or breakage over time?"}
                ]
            },
            {
                "week_num": 31,
                "week_id": "week-31-threat-hunting",
                "week_title": "Threat Hunting Methodologies & TTP Investigation",
                "objective": "Execute hypothesis-driven threat hunts, hunt for persistence mechanisms, analyze process ancestry, and uncover periodic beaconing.",
                "tools": ["Velociraptor", "Elasticsearch / Kibana", "PowerShell", "BlueTeam-Tools", "CyberChef", "Python"],
                "major_concepts": ["Hypothesis-Driven Hunting", "Autostart Extensibility Points (ASEPs)", "Process Lineage Analysis", "Network Beaconing Analysis", "Threat Hunting Case Study"],
                "weekly_lab": "Enterprise Threat Hunt Lab: Formulate a hunt hypothesis, query endpoint state using Velociraptor, and identify an emulated threat actor's hidden persistence.",
                "deliverable": "Threat Hunting Report & Query Playbook",
                "days": [
                    {"day_num": 151, "title": "Threat Hunting Core Concepts — Hypotheses, IOCs & IOAs", "topics": ["Threat hunting definition: Proactively searching through networks and endpoints for threats that evaded existing controls", "The Threat Hunting loop: Hypothesis Generation -> Evidence Collection -> Analytics -> Response -> Automation", "Types of hunts: Hypothesis-driven, Intelligence-driven (IOC matching), Entity-driven (high-value asset profiling)", "Indicators of Compromise (IOCs: hashes, IPs) vs Indicators of Attack (IOAs: behaviors, TTPs)", "The Pyramid of Pain: Why hunting for TTPs delivers the highest defensive return"], "objectives": "Formulate testable threat hunting hypotheses based on threat intelligence and adversary TTPs.", "lab": "Draft three formal threat hunting hypotheses targeting credential dumping, DLL search order hijacking, and lateral movement in an enterprise.", "interview_q": "Explain the difference between reactive alert triage in a SOC and proactive threat hunting, referencing the Pyramid of Pain."},
                    {"day_num": 152, "title": "Hunting for Persistence — ASEPs, Registry & Tasks", "topics": ["Autostart Extensibility Points (ASEPs): The hundreds of locations Windows checks for boot-time execution", "Hunting Run/RunOnce keys: Stacking registry values across thousands of endpoints to spot rare outliers", "Scheduled Tasks hunting: Querying XML task definitions for suspicious paths (`C:\\Users\\Public`, `AppData`)", "Service persistence hunting: Looking for non-standard service binpaths and newly registered drivers", "Using Velociraptor VQL to hunt ASEP artifacts across an entire network fleet"], "objectives": "Hunt across endpoint fleets to discover persistent footholds using frequency analysis and anomaly detection.", "lab": "Write a PowerShell / Velociraptor query to aggregate all scheduled task binary paths across lab machines and sort by lowest frequency of occurrence.", "interview_q": "What is 'frequency analysis' (or stacking) in threat hunting, and how does it help unearth a single persistent malware implant among 5,000 corporate machines?"},
                    {"day_num": 153, "title": "Hunting for Living-off-the-Land Activity & Process Ancestry", "topics": ["Parent-child process tree analysis: Building the full lineage from process creation events", "Detecting process masquerading: Legitimate process names executing from illegitimate directories (`C:\\Temp\\svchost.exe`)", "Identifying command-line anomalies: High-entropy command lines, unusual flags, obfuscated variables", "Hunting for LOLBAS usage: Stacking command-line invocations of `wmic`, `powershell`, `mshta`, `cscript`", "Investigating process injection signatures: Looking for unmapped executable memory pages"], "objectives": "Uncover masqueraded processes and anomalous living-off-the-land commands through process tree reconstruction.", "lab": "Query your SIEM for all instances of `cmd.exe` or `powershell.exe` where the parent process is not `explorer.exe` or an administrative console.", "interview_q": "Why is inspecting the execution directory of a process just as important as inspecting its process name during a threat hunt?"},
                    {"day_num": 154, "title": "Network Threat Hunting — Long Connections & Beaconing Analysis", "topics": ["Network threat hunting concepts: Looking for patterns in outbound proxy and firewall logs", "Hunting for persistent connections: Identifying sessions with unusually long duration and steady packet transfer", "Detecting command-and-control beaconing: Extracting connection timestamps, calculating intervals, and plotting delta histograms", "Domain Generation Algorithms (DGA): Detecting DGA domains via character entropy and high NXDOMAIN ratios", "Investigating TLS certificate anomalies: Self-signed certs, rare issuers, mismatched SNIs"], "objectives": "Identify command-and-control communication channels by analyzing network connection timings and domain entropy.", "lab": "Analyze a dataset of 10,000 outbound network connections using Python; calculate the variance in callback intervals to identify an active beacon.", "interview_q": "How do you distinguish between legitimate periodic polling (like Windows Update or software telemetry) and adversary C2 beaconing?"},
                    {"day_num": 155, "title": "Threat Hunting Case Study — Tracking an Advanced Adversary", "topics": ["End-to-end hunting case study: A scenario where an attacker landed via an unknown vector", "Establishing the initial pivot: Starting from a single suspicious artifact and tracing backwards and forwards in time", "Pivoting across identity logs: Tracking compromised user accounts across workstations and cloud applications", "Scoping the full compromise: Compiling the complete timeline of adversary activity", "Transitioning from a threat hunt into an active Incident Response investigation"], "objectives": "Execute a full-scope threat hunt across endpoint, identity, and network logs to reconstruct an adversary's footprint.", "lab": "Perform a guided threat hunt across a synthetic enterprise dataset to reconstruct an attacker's movement from phishing landing to domain compromise.", "interview_q": "At what point during a proactive threat hunt should the hunt be formally converted into an active Incident Response (IR) incident?"}
                ]
            },
            {
                "week_num": 32,
                "week_id": "week-32-incident-response",
                "week_title": "Incident Response Lifecycle & Triage",
                "objective": "Master the incident response lifecycle (PICERL), execute live triage on Windows and Linux systems, implement containment strategies, and document findings.",
                "tools": ["Velociraptor", "KAPE", "FTK Imager", "Volatility 3", "PowerShell", "BlueTeam-Tools"],
                "major_concepts": ["NIST & SANS IR Frameworks", "Live Volatile Data Triage", "Linux & Windows Forensics Triage", "Containment Strategies", "Lessons Learned & Remediation"],
                "weekly_lab": "Deliverable 6 Lab: Triage a compromised system, extract volatile evidence, isolate the host, verify containment, and author the SOC Lab & IR report.",
                "deliverable": "Deliverable 6: SOC & Detection Engineering Lab (SIEM Setup + Sigma Detection Suite + Incident Response Triage Documentation)",
                "days": [
                    {"day_num": 156, "title": "Incident Response Frameworks — NIST SP 800-61 & SANS PICERL", "topics": ["The Incident Response Lifecycle: Preparation, Identification, Containment, Eradication, Recovery, Lessons Learned", "Incident severity classification: Low, Medium, High, Critical criteria", "The Incident Command System (ICS): Roles of the Incident Commander, Lead Investigator, Scribe, and Communications Lead", "Chain of custody and evidence handling legal requirements", "Establishing out-of-band communication channels during active network compromises"], "objectives": "Structure and manage security incidents according to international industry response standards.", "lab": "Draft an Incident Response Plan (IRP) playbook for an enterprise ransomware infection, detailing containment triggers and escalation pathways.", "interview_q": "Walk through the six phases of the SANS PICERL incident response framework, explaining the primary objective of each phase."},
                    {"day_num": 157, "title": "Live Incident Triage on Windows — Volatile Data Collection", "topics": ["The Order of Volatility: CPU registers/cache -> Routing table/process table -> Memory -> Disk -> Remote logs", "Collecting volatile data without contaminating evidence (minimizing memory perturbation)", "Collecting active network connections (`netstat -ano`), running processes, logged-in users", "Rapid triage collection using KAPE (Kroll Artifact Parser and Extractor) and CyLR", "Preserving RAM: Creating physical memory images using FTK Imager / WinPmem"], "objectives": "Collect volatile system state and forensic triage packages from live Windows endpoints.", "lab": "Execute a live triage script on a suspect Windows machine, capturing active connections, open handles, and a RAM image.", "interview_q": "What is the 'Order of Volatility' in digital forensics, and why must RAM be acquired before taking a disk image or powering down a machine?"},
                    {"day_num": 158, "title": "Live Incident Triage on Linux — Host Forensics & Volatile State", "topics": ["Collecting volatile evidence on Linux: Process trees, network connections (`ss -tulpn`), logged-in users (`who`, `w`, `last`)", "Investigating suspicious processes via `/proc`: Recovering deleted malware binaries from `/proc/<PID>/exe`", "Auditing network interfaces for promiscuous mode (packet sniffing detection)", "Checking kernel modules (`lsmod`) for rootkit signatures", "Rapid Linux artifact collection using UAC (Unix-like Artifact Collector)"], "objectives": "Perform rapid forensic triage on compromised Linux servers to identify malicious processes, backdoors, and rootkits.", "lab": "Triage a compromised Linux target: Recover a running malware executable that was deleted from disk by extracting it from `/proc/<PID>/exe`.", "interview_q": "If an attacker deletes a running malware binary from disk on a Linux system, how can an incident responder recover the executable file?"},
                    {"day_num": 159, "title": "Containment Strategies — Host Isolation, Token Revocation & KRBTGT", "topics": ["Containment objectives: Stopping attacker lateral movement and data exfiltration while preserving evidence", "Network isolation: Host-based firewall isolation rules (allowing only EDR/IR management traffic)", "Identity containment: Disabling accounts, revoking active session tokens, forcing password changes", "Active Directory domain-wide containment: The double-reset of the KRBTGT account password to invalidate Golden Tickets", "Eradication and recovery: Rebuilding systems vs restoring from clean backups, verifying patch application"], "objectives": "Execute targeted network and identity containment actions without tipping off the adversary.", "lab": "Implement a network isolation script that locks down all inbound and outbound traffic on an endpoint except for the analyst's management port.", "interview_q": "Why does remediating an Active Directory compromise where a Golden Ticket was used require resetting the KRBTGT password TWICE?"},
                    {"day_num": 160, "title": "Phase 6 Capstone Deliverable — SOC & Detection Lab", "topics": ["Finalizing the complete SOC & Detection Engineering Lab environment", "Verifying all components: Wazuh SIEM Manager + Windows/Linux Agents + Sysmon + Sigma Rules + IR Playbooks", "Documenting end-to-end detection: Executing an attack, capturing it in Wazuh, and triggering automated alerts", "Authoring Deliverable 6 documentation: Lab architecture, Sigma rule catalog, and incident triage runbooks", "Reviewing lessons learned and operational recommendations"], "objectives": "Complete Deliverable 6: A fully functional SOC and Detection Engineering Lab with verified detections and triage procedures.", "lab": "Package all custom Sigma rules, Wazuh decoders, triage scripts, and lab architecture diagrams into Deliverable 6 in `projects/`.", "interview_q": "How do you measure whether a SOC and detection engineering program is actually improving over time? What metrics do you track?"}
                ]
            }
        ]
    },

    # PHASE 7 (Weeks 33-35, Days 161-175)
    {
        "phase_num": 7,
        "phase_id": "phase-07-malware-forensics",
        "phase_title": "Malware Analysis + Digital Forensics",
        "weeks_range": "Weeks 33–35",
        "days_range": "Days 161–175",
        "objective": "Understand malware binary internals (PE/ELF), execute static and dynamic malware triage, disassemble code with Ghidra, craft YARA rules, and conduct memory and filesystem digital forensics.",
        "skills": ["PE & ELF binary anatomy", "Malware sandboxing & behavioral analysis", "Static disassembly with Ghidra", "Writing YARA detection rules", "Memory forensics with Volatility 3", "Forensic artifact timelining (MFT, Prefetch, Shimcache)"],
        "tools": ["Ghidra", "PE-bear", "x64dbg", "Process Monitor (Procmon)", "FakeNet-NG", "YARA", "Volatility 3", "FTK Imager", "Eric Zimmerman Tools"],
        "project_id": "project-07-malware-triage-forensics",
        "project_title": "Malware Triage & Digital Forensics Investigation Report (Sample Dissection + YARA Rule + Memory Reconstruction)",
        "weeks": [
            {
                "week_num": 33,
                "week_id": "week-33-malware-fundamentals",
                "week_title": "Malware Architecture & Fundamentals",
                "objective": "Deconstruct binary file formats (PE/ELF), analyze imports/exports, understand evasion and packing, and build a safe malware analysis lab.",
                "tools": ["PE-bear", "Detect It Easy (DIE)", "FLOSS", "UPX", "Remnux", "FlareVM"],
                "major_concepts": ["Portable Executable (PE) Format", "Import Address Table (IAT)", "ELF Headers & Dynamic Linking", "Packers & Obfuscation", "Air-Gapped Lab Isolation"],
                "weekly_lab": "Binary Structure & Triage Lab: Inspect PE headers of benign and packed binaries in PE-bear, analyze section entropy, and extract obfuscated strings.",
                "deliverable": "Binary Anatomy & Safe Malware Lab Architecture Guide",
                "days": [
                    {"day_num": 161, "title": "Portable Executable (PE) File Format Architecture", "topics": ["The structure of Windows binaries: DOS Header (`IMAGE_DOS_HEADER`), DOS Stub ('This program cannot be run in DOS mode')", "PE File Signature and File Header (`IMAGE_FILE_HEADER`): Machine type, NumberOfSections, TimeDateStamp", "Optional Header (`IMAGE_OPTIONAL_HEADER`): AddressOfEntryPoint, ImageBase, Subsystem (GUI vs CUI)", "Section Headers (`IMAGE_SECTION_HEADER`): Section names, VirtualSize, VirtualAddress, RawData, Characteristics", "Standard sections: `.text` (code), `.data` (initialized data), `.rdata` (read-only/imports), `.rsrc` (resources)"], "objectives": "Navigate and parse Portable Executable (PE) headers manually and using structural viewers.", "lab": "Inspect a Windows executable in PE-bear; locate the ImageBase, AddressOfEntryPoint, and verify section characteristics.", "interview_q": "What is the purpose of the AddressOfEntryPoint and ImageBase fields in the PE Optional Header?"},
                    {"day_num": 162, "title": "PE Imports, Exports & The Import Address Table (IAT)", "topics": ["Dynamic linking in Windows: How executables call Windows APIs located in system DLLs (`kernel32.dll`, `user32.dll`)", "Import Directory, Import Lookup Table (ILT), and Import Address Table (IAT)", "Inspecting imports to infer malware capabilities: Network APIs (`connect`, `InternetOpen`), Process Injection APIs (`VirtualAllocEx`, `WriteProcessMemory`, `CreateRemoteThread`)", "Export Directory: Why DLLs export functions and DLL entry point (`DllMain`)", "Dynamic API resolution: Calling `LoadLibraryA` and `GetProcAddress` to conceal imports from static analysis"], "objectives": "Infer the behavioral capabilities of a binary by analyzing its imported functions and the Import Address Table.", "lab": "Analyze the IAT of a test sample in PE-bear; classify imported functions into Network, File, Memory, and Process capabilities.", "interview_q": "Why do sophisticated malware authors use `LoadLibrary` and `GetProcAddress` to call APIs dynamically rather than declaring them in the Import Table?"},
                    {"day_num": 163, "title": "ELF Binary Structure in Linux & Shared Object Hooking", "topics": ["The Executable and Linkable Format (ELF) structure: ELF Header, Program Header Table, Section Header Table", "Key ELF sections: `.text`, `.rodata`, `.data`, `.bss`, `.dynsym`, `.got` (Global Offset Table), `.plt` (Procedure Linkage Table)", "Shared libraries (`.so`) and dynamic symbol resolution via the GOT/PLT", "Shared object hooking via `LD_PRELOAD`: Intercepting libc functions (e.g. `readdir`, `fopen`) for rootkit hiding", "Analyzing ELF binaries with `readelf`, `objdump`, and `nm`"], "objectives": "Inspect Linux ELF binary headers and understand how dynamic linker hijacking enables Linux user-space rootkits.", "lab": "Use `readelf -h` and `readelf -S` to parse an ELF executable; build a simple LD_PRELOAD shared library that hooks `puts`.", "interview_q": "How does user-space rootkit hiding work in Linux using the `LD_PRELOAD` environment variable and shared library function hooking?"},
                    {"day_num": 164, "title": "Malware Evasion Concepts — Packing, Cryptors & Anti-Analysis", "topics": ["The purpose of packing: Compressing and encrypting the original executable on disk to defeat static signatures", "Anatomy of a packed binary: Packer stub, high section entropy, minimal import table (only LoadLibrary/GetProcAddress)", "Detecting packing using section entropy calculations and Detect It Easy (DIE)", "Unpacking UPX binaries: Using `upx -d` and manual unpacking concepts", "Anti-analysis techniques: Anti-VM checks (checking registry keys, MAC addresses, CPU cores) and Anti-Debugging checks (`IsDebuggerPresent`, PEB BeingDebugged flag)"], "objectives": "Identify packed and obfuscated executables using entropy analysis and understand basic anti-analysis checks.", "lab": "Pack a sample binary with UPX, analyze the entropy increase in Detect It Easy, and unpack it using both command-line and debugger techniques.", "interview_q": "How does calculating section entropy help a malware analyst immediately determine if a binary is packed or encrypted?"},
                    {"day_num": 165, "title": "Designing an Isolated Malware Analysis Lab", "topics": ["Lab isolation architecture: Preventing accidental infection of host or corporate networks", "Hypervisor configuration: Host-Only private networking, disabling shared folders, disabling clipboard sharing", "Deploying analysis guest machines: FlareVM (Windows triage workstation) and REMnux (Linux network simulation)", "Simulating internet services: Using FakeNet-NG and INetSim to handle DNS, HTTP, and SMTP requests safely", "Snapshot management: Creating golden pristine snapshots and establishing clean rollback routines"], "objectives": "Build and verify an air-gapped, isolated multi-OS malware analysis sandbox environment.", "lab": "Configure a FlareVM Windows instance and REMnux instance on an isolated virtual host-only network; verify FakeNet-NG network simulation.", "interview_q": "Why must you strictly disable shared folders, shared clipboards, and bridged networking when building a malware analysis lab?"}
                ]
            },
            {
                "week_num": 34,
                "week_id": "week-34-static-dynamic-analysis",
                "week_title": "Static & Dynamic Malware Analysis",
                "objective": "Execute static analysis, reverse-engineer code with Ghidra, monitor behavioral execution with Procmon and FakeNet-NG, and author YARA detection rules.",
                "tools": ["Ghidra", "YARA", "Process Monitor (Procmon)", "Regshot", "FakeNet-NG", "FLOSS", "Capa"],
                "major_concepts": ["Basic Static Triage", "Ghidra Decompilation", "Behavioral Process Monitoring", "Simulated Network Interactions", "YARA Rule Engineering"],
                "weekly_lab": "Malware Dissection Lab: Perform static disassembly of a suspicious sample in Ghidra, execute in sandbox under Procmon, and author a custom YARA detection rule.",
                "deliverable": "Malware Analysis Report & Custom YARA Rule Repository",
                "days": [
                    {"day_num": 166, "title": "Basic Static Triage — Hashes, Strings & Capability Mapping", "topics": ["Static analysis workflow: Gathering intelligence without executing the binary", "Cryptographic hashing: MD5, SHA256, and fuzzy hashing with SSDEEP (measuring similarity across samples)", "Extracting strings with `strings` and FireEye Labs Obfuscated String Solver (FLOSS) to deobfuscate in-memory strings", "Automated capability mapping with Mandiant `Capa`: Identifying high-level capabilities (e.g. keylogging, injection) mapped to ATT&CK", "Querying VirusTotal, MalShare, and MalwareBazaar via hashes"], "objectives": "Extract indicators of compromise (IOCs), strings, and capability profiles statically from suspect binaries.", "lab": "Run FLOSS and Capa against an unknown malware sample; catalog its cryptographic hashes, extracted URLs, and mapped capabilities.", "interview_q": "How does fuzzy hashing with SSDEEP allow an analyst to identify that two different malware samples belong to the same family even if their SHA256 hashes differ?"},
                    {"day_num": 167, "title": "Advanced Static Analysis with Ghidra — Disassembly & Decompilation", "topics": ["Introduction to Ghidra: Project workspace, CodeBrowser, Symbol Tree, and Listing", "Disassembly (x86/x64 assembly) vs Decompilation (reconstructed C pseudo-code)", "Navigating functions: Identifying `entry`, `main`, and renamed functions", "Analyzing function call graphs, cross-references (XREFs), and strings references", "Reconstructing data structures, variable names, and function signatures to understand core algorithms"], "objectives": "Decompile binary functions in Ghidra to analyze the underlying logic and execution flow of malware.", "lab": "Open a sample binary in Ghidra, locate the main decryption loop via string XREFs, and reconstruct the C pseudo-code logic.", "interview_q": "Explain what a cross-reference (XREF) is in Ghidra and how following an XREF from a suspicious string helps locate malicious logic."},
                    {"day_num": 168, "title": "Writing YARA Rules for Malware Pattern Matching", "topics": ["The YARA rule standard: Pattern matching Swiss army knife for malware researchers", "Rule structure: `rule RuleName { meta: strings: condition: }`", "String definitions: Text strings (`nocase`, `wide`, `ascii`), Hexadecimal strings with wildcards, Regular expressions", "Condition logic: Boolean operators, string counts (`#a > 3`), entrypoint matching, file size limits (`filesize < 5MB`)", "Testing and tuning YARA rules: Scanning directories, measuring false positives against clean system files"], "objectives": "Author and test high-fidelity YARA rules to detect malware families across file systems.", "lab": "Write a custom YARA rule targeting unique byte sequences and string artifacts of a sample; test it against clean system files to verify zero false positives.", "interview_q": "What is the difference between an `ascii` and a `wide` string modifier in a YARA rule, and when must you use `wide`?"},
                    {"day_num": 169, "title": "Basic Dynamic Analysis — Procmon, Regshot & Network Simulation", "topics": ["Dynamic analysis workflow: Safely executing malware in a monitored environment", "Process Monitor (Procmon): Filtering by Process Name, monitoring File System, Registry, Process, and Thread activity", "Regshot: Taking pre-execution and post-execution registry snapshots to identify created autostart keys", "Simulating network services with FakeNet-NG: Intercepting DNS requests, HTTP GET/POST beacons, and SSL connections", "Correlating file drops with registry autostarts"], "objectives": "Capture and analyze all file system modifications, registry changes, and network callbacks produced by live malware.", "lab": "Execute a sample inside the sandbox with Procmon and FakeNet-NG running; identify dropped payload paths, modified Run keys, and C2 URLs.", "interview_q": "What Procmon filter settings are most effective for eliminating background Windows OS noise during a dynamic malware analysis run?"},
                    {"day_num": 170, "title": "Sandbox Triage & Automated Behavioral Analysis", "topics": ["Automated sandbox platforms: CAPEv2, Cuckoo, ANY.RUN, Hybrid Analysis", "Reading automated behavioral analysis reports: Process activity trees, network signatures, dropped files", "Analyzing memory dumps generated by sandboxes: Extracting injected payloads and decrypted configurations", "Extracting C2 configurations: Locating IP addresses, encryption keys, and campaign IDs automatically", "Synthesizing dynamic and static findings into an executive triage report"], "objectives": "Interpret automated sandbox execution graphs and extract command-and-control configuration data.", "lab": "Submit a sample to a local CAPEv2 / ANY.RUN instance; analyze the behavioral process tree and extract the decrypted C2 configuration.", "interview_q": "What are the limitations of automated sandbox reports, and why is manual static or dynamic analysis still necessary for advanced malware?"}
                ]
            },
            {
                "week_num": 35,
                "week_id": "week-35-digital-forensics",
                "week_title": "Digital Forensics & Incident Reconstruction",
                "objective": "Perform memory forensics with Volatility 3, analyze disk artifacts (Prefetch, Shimcache, Amcache, MFT), and reconstruct full attack timelines.",
                "tools": ["Volatility 3", "Eric Zimmerman Tools (PECmd, AppCompatCacheParser, MFTECmd)", "FTK Imager", "CyberChef"],
                "major_concepts": ["Memory Analysis (Volatility 3)", "Code Injection Detection (malfind)", "Windows Execution Artifacts", "Master File Table (MFT) Analysis", "Timeline Reconstruction"],
                "weekly_lab": "Deliverable 7 Lab: Ingest a forensic memory dump and disk image from a compromised machine, reconstruct the incident timeline, and author the Forensic Report.",
                "deliverable": "Deliverable 7: Malware Triage + Forensics Report (Memory Analysis + Disk Artifact Timelines + Incident Reconstruction)",
                "days": [
                    {"day_num": 171, "title": "Memory Forensics with Volatility 3 — Processes & Sockets", "topics": ["Memory forensics fundamentals: Analyzing physical RAM to unearth volatile evidence that leaves no disk trace", "Volatility 3 architecture: Symbols, plugins, and CLI syntax (`vol -f mem.raw <plugin>`)", "Process analysis plugins: `windows.pslist` (active processes), `windows.psscan` (unlinked/hidden processes), `windows.pstree` (parent-child trees)", "Network connection analysis: `windows.netscan` (historical and active TCP/UDP endpoints, sockets)", "Command line extraction: `windows.cmdline`"], "objectives": "Analyze physical memory images to uncover running processes, hidden unlinked processes, and historical network sockets.", "lab": "Run Volatility 3 on a memory dump of an infected system; reconstruct the process tree and identify the parent process of a rogue implant.", "interview_q": "How does `windows.psscan` find processes in memory that are hidden from `windows.pslist`, and what operating system data structure does it scan for?"},
                    {"day_num": 172, "title": "Detecting Memory Injection with Volatility — malfind & VAD", "topics": ["Process memory layout and Virtual Address Descriptors (VAD)", "Detecting injected code using `windows.malfind`: Scanning for memory pages with `PAGE_EXECUTE_READWRITE` (RWX) permissions and MZ/PE headers", "Dumping injected memory regions (`windows.dumpfiles`, `--dump`) for static analysis", "Detecting DLL injection: `windows.dlllist` vs `windows.ldrmodules` (identifying unlinked DLLs)", "Analyzing hollowed and migrated processes in memory"], "objectives": "Identify, locate, and dump injected code and unlinked DLL modules from memory images.", "lab": "Use `windows.malfind` to discover an injected shellcode blob inside `explorer.exe`; dump the memory section and analyze the injected payload in Ghidra.", "interview_q": "What specific memory allocation characteristics (such as memory page permissions) does Volatility's `malfind` plugin look for to identify code injection?"},
                    {"day_num": 173, "title": "Windows Execution Artifacts — Prefetch, Shimcache & Amcache", "topics": ["Proving program execution in digital forensics: Why file existence does not equal execution", "Windows Prefetch files (`.pf`): Proving execution, execution count, last execution timestamp, and referenced files (PECmd)", "Shimcache (AppCompatCache): Tracking executed binary paths, file sizes, and last modified timestamps across reboots", "Amcache (`Amcache.hve`): Recording SHA1 file hashes, execution paths, and install times", "Parsing artifacts with Eric Zimmerman's forensic tools (PECmd, AppCompatCacheParser, AmcacheParser)"], "objectives": "Extract definitive forensic evidence of binary execution from Windows operating system artifacts.", "lab": "Parse a disk image's Prefetch directory and Shimcache using Eric Zimmerman's tools; determine the exact date, time, and execution count of a malicious tool.", "interview_q": "Compare the evidentiary value of Windows Prefetch files versus Shimcache. What information does Prefetch provide that Shimcache does not?"},
                    {"day_num": 174, "title": "Master File Table (MFT) & USN Journal Forensics", "topics": ["NTFS filesystem internals: The Master File Table ($MFT) and metadata records", "The `$STANDARD_INFORMATION` (SI) vs `$FILE_NAME` (FN) attributes: Detecting timestomping through timestamp discrepancies", "The Update Sequence Number (USN) Change Journal (`$UsnJrnl`): Tracking file creations, deletions, and renames", "LNK file and Shellbags analysis: Tracking user folder navigation and external drive connections", "Parsing MFT records with `MFTECmd` to build a chronological file system timeline"], "objectives": "Parse the NTFS Master File Table and USN journal to track file system creations, modifications, and timestomping.", "lab": "Extract and parse `$MFT` from a forensic disk image using `MFTECmd`; identify files created within a 15-minute attack window and detect timestomping.", "interview_q": "How does comparing the `$STANDARD_INFORMATION` and `$FILE_NAME` attributes in an MFT record allow an investigator to detect timestomping?"},
                    {"day_num": 175, "title": "Phase 7 Capstone Deliverable — Malware Triage & Forensics Report", "topics": ["Consolidating memory artifacts, disk execution evidence, and static/dynamic malware analysis", "Reconstructing the comprehensive incident chronological timeline (down to the second)", "Documenting Indicators of Compromise (IOCs): Hashes, domains, IPs, registry keys, YARA signatures", "Authoring Deliverable 7: Executive Summary, Incident Overview, Technical Forensic Analysis, Malware Capabilities, Remediation Steps", "Ensuring courtroom and legal readiness: Evidence handling documentation and objectivity"], "objectives": "Author and finalize Deliverable 7: A complete Malware Triage & Digital Forensics Investigation Report.", "lab": "Compile memory dumps, MFT timelines, Ghidra decompilation notes, and YARA rules into Deliverable 7 in `projects/`.", "interview_q": "How do you present forensic evidence in a technical investigation report so that it withstands legal scrutiny and proves continuity of evidence?"}
                ]
            }
        ]
    },

    # PHASE 8 (Weeks 36-38, Days 176-190)
    {
        "phase_num": 8,
        "phase_id": "phase-08-security-programming",
        "phase_title": "Security Programming + Rust + Tool Development",
        "weeks_range": "Weeks 36–38",
        "days_range": "Days 176–190",
        "objective": "Master modern systems programming in Rust tailored for security engineering: Ownership, borrowing, concurrency, building asynchronous security tools, line-speed parsers, and low-level memory/Windows API interaction.",
        "skills": ["Rust ownership & borrow checker mechanics", "Structs, Enums, and pattern matching", "Asynchronous programming with Tokio", "Building ultra-fast multi-threaded port scanners in Rust", "High-speed HTTP probing & log parsing", "Unsafe Rust, FFI, and Win32 API interaction"],
        "tools": ["Rust", "Cargo", "Tokio", "Reqwest", "Clap", "Black Hat Rust", "Python 3"],
        "project_id": "project-08-personal-security-toolkit",
        "project_title": "Personal Security Toolkit (High-Performance Async Port Scanner + HTTP Prober + Custom Log Parser in Rust)",
        "weeks": [
            {
                "week_num": 36,
                "week_id": "week-36-rust-fundamentals",
                "week_title": "Rust Fundamentals for Security Practitioners",
                "objective": "Master core Rust syntax, memory safety without garbage collection, the ownership/borrowing model, and safe multi-threaded concurrency.",
                "tools": ["Rust (rustc, cargo)", "rust-analyzer", "Black Hat Rust"],
                "major_concepts": ["Cargo Project Architecture", "Ownership & Move Semantics", "Borrow Checker (& and &mut)", "Structs & Enums (Result/Option)", "Thread Spawning & Mutexes"],
                "weekly_lab": "Rust Systems Programming Lab: Implement a concurrent TCP banner grabber using threads and crossbeam channels with comprehensive error handling.",
                "deliverable": "Rust Core Systems Programming Reference & Exercise Suite",
                "days": [
                    {"day_num": 176, "title": "Introduction to Rust — Cargo Tooling, Types & Immutability", "topics": ["Why Rust for security engineering: Memory safety guarantees, zero-cost abstractions, C-level performance without memory corruption", "Cargo tooling: `cargo new`, `cargo build --release`, `cargo test`, `cargo clippy`", "Variables and mutability: Default immutability, `mut` keyword, shadowing", "Primitive data types: Integers (signed/unsigned), floating point, booleans, characters, tuples, arrays", "Functions, expressions vs statements, and basic control flow (`if`, `loop`, `while`, `for`)"], "objectives": "Set up a modern Rust development environment and understand immutability by default.", "lab": "Initialize a new Cargo binary project; implement a CLI utility that calculates subnets and formats IP address representations.", "interview_q": "Why is Rust increasingly favored over C and C++ for both offensive security tooling and critical defensive infrastructure?"},
                    {"day_num": 177, "title": "Memory Safety Without Garbage Collection — Ownership & Borrowing", "topics": ["The Ownership Model: Each value has an owner, only one owner at a time, value dropped when owner goes out of scope", "Move semantics vs Copy trait: What happens when passing strings and vectors to functions", "References and Borrowing: Immutable references (`&T`) vs Mutable references (`&mut T`)", "The Borrow Checker rules: Multiple immutable references OR exactly one mutable reference (preventing data races)", "Lifetimes primer: Ensuring references do not outlive the data they point to"], "objectives": "Master the Rust borrow checker and understand how compile-time checks eliminate use-after-free and data races.", "lab": "Write code demonstrating ownership transfer; resolve borrow checker compile errors and create safe functions operating on borrowed string slices (`&str`).", "interview_q": "Explain the two fundamental rules enforced by the Rust borrow checker regarding immutable and mutable references."},
                    {"day_num": 178, "title": "Data Structures & Composition — Structs, Enums & Error Handling", "topics": ["Defining and instantiating Structs: Named-field structs, tuple structs", "Implementing methods and associated functions (`impl` blocks)", "Enums and algebraic data types: Defining rich state models", "The `Option<T>` enum: Replacing null pointers with `Some(T)` and `None`", "The `Result<T, E>` enum and idiomatic error handling with the `?` operator", "Pattern matching with `match` and `if let` constructs"], "objectives": "Model security entities (packets, hosts, credentials) using Structs and Enums while handling errors gracefully without panicking.", "lab": "Define a `NetworkPacket` struct and an `IpProtocol` enum; implement a method that parses raw bytes into the struct and returns a `Result`.", "interview_q": "How does Rust's `Option<T>` and `Result<T, E>` type system eliminate null pointer exceptions and unhandled runtime exceptions at compile time?"},
                    {"day_num": 179, "title": "Traits, Generics & Standard Library Collections", "topics": ["Common collections: `Vec<T>`, `HashMap<K, V>`, `HashSet<T>`, `String` vs `&str`", "Defining and implementing Traits: Rust's interface abstraction model", "Standard traits: `Display`, `Debug`, `Clone`, `Default`, `From` / `Into`", "Generics: Writing reusable functions and data structures operating across multiple types", "Iterators and closures: Transforming collections with `map`, `filter`, `fold`, `collect`"], "objectives": "Leverage collections, traits, and iterators to process and filter large datasets efficiently.", "lab": "Build an in-memory credential storage and lookup engine using a `HashMap` implementing custom serialization traits.", "interview_q": "What is a Trait in Rust, and how does implementing the `From` trait simplify custom error type conversions?"},
                    {"day_num": 180, "title": "Concurrency in Rust — Safe Multi-Threading & Channels", "topics": ["Concurrency safety in Rust: The `Send` and `Sync` marker traits", "Spawning OS threads with `std::thread::spawn` and joining handles", "Message passing concurrency: Using multi-producer, single-consumer channels (`std::sync::mpsc`)", "Shared state concurrency: `Arc<T>` (Atomic Reference Counting) and `Mutex<T>` (Mutual Exclusion)", "Eliminating deadlocks and race conditions through compiler enforcement"], "objectives": "Write multi-threaded security tools that safely share data and pass messages across threads without data races.", "lab": "Build a multi-threaded TCP banner grabber that spawns a thread pool, dispatches target IPs via channels, and writes collected banners to a shared vector.", "interview_q": "Why is `Arc<Mutex<T>>` a common idiom for sharing state across threads in Rust, and what role does `Arc` play compared to `Mutex`?"}
                ]
            },
            {
                "week_num": 37,
                "week_id": "week-37-security-tool-engineering",
                "week_title": "Security Tool Engineering in Rust",
                "objective": "Build high-performance, asynchronous networking tools in Rust: Async port scanners with Tokio, HTTP probers with reqwest, and fast parsers with clap.",
                "tools": ["Rust", "Tokio", "Reqwest", "Clap", "Serde", "Black Hat Rust"],
                "major_concepts": ["Async Runtimes (Tokio)", "Non-Blocking Network Sockets", "Asynchronous HTTP Clients", "CLI Design with Clap", "High-Throughput Log Parsing"],
                "weekly_lab": "Async Scanner Engineering Lab: Build a compiled, multi-threaded asynchronous port scanner in Rust capable of scanning 1,000 ports per second.",
                "deliverable": "Compiled Rust Security Utility Binaries & Source Repository",
                "days": [
                    {"day_num": 181, "title": "Async Programming in Rust — The Tokio Runtime & Async/Await", "topics": ["Synchronous blocking I/O vs Asynchronous non-blocking I/O", "The `Future` trait in Rust: How asynchronous tasks are polled to completion", "The Tokio asynchronous runtime: Multi-threaded task scheduler and reactor", "Async/await syntax: Writing non-blocking code that reads like synchronous code", "Spawning async tasks with `tokio::spawn` and managing concurrency limits with `Semaphore`"], "objectives": "Architect high-throughput asynchronous applications using the Tokio runtime.", "lab": "Write an asynchronous script that connects to 100 network ports concurrently using Tokio without spawning 100 heavy OS threads.", "interview_q": "How does an asynchronous runtime like Tokio handle thousands of concurrent network connections using only a small pool of worker threads?"},
                    {"day_num": 182, "title": "Building an Ultra-Fast Port Scanner in Rust", "topics": ["Designing a high-speed port scanner: Architecture, packet crafting, and connection timeouts", "Implementing asynchronous TCP connect probes using `tokio::net::TcpStream`", "Managing rate limiting: Using `tokio::sync::Semaphore` to limit maximum concurrent file descriptors / sockets", "Parsing target specifications: Handling single IPs, hostnames, and CIDR ranges (`ipnet` crate)", "Benchmarking scanner performance against Nmap and Masscan"], "objectives": "Develop a functional, compiled asynchronous TCP port scanner in Rust with configurable concurrency and timeouts.", "lab": "Build and compile `rust-port-scan`: A CLI tool that scans a /24 subnet across the top 1,000 ports in under 10 seconds.", "interview_q": "What operating system limits (such as `ulimit -n` on Linux or socket handles on Windows) must an engineer account for when writing high-speed port scanners?"},
                    {"day_num": 183, "title": "Building an Asynchronous HTTP Prober & Subdomain Filter", "topics": ["Asynchronous HTTP client engineering with `reqwest`", "Configuring custom headers, User-Agents, redirects, and SSL verification options", "Handling thousands of URLs: Asynchronous streaming of domains and concurrency pipelines", "Extracting title tags, status codes, content lengths, and response times", "Filtering out wildcard DNS responses and web server sinkholes"], "objectives": "Build a fast asynchronous HTTP prober in Rust that takes a list of subdomains and returns live web endpoints with status codes.", "lab": "Develop `rust-http-probe`: An async utility taking a file of 1,000 subdomains and filtering out dead hosts in parallel using reqwest.", "interview_q": "Why is client connection pooling and disabling keep-alive important when designing an HTTP prober intended to hit thousands of distinct servers?"},
                    {"day_num": 184, "title": "Line-Speed Log & Data Parsing in Rust with Serde", "topics": ["High-performance data serialization and deserialization with `serde` and `serde_json`", "Zero-copy deserialization: Using borrowed references (`&'a str`) to avoid memory allocations during parsing", "Parsing line-delimited JSON (NDJSON) security logs at line speed", "Regex parsing vs state-machine parsing for performance optimization", "Benchmarking and profiling Rust code with `criterion` and `flamegraph`"], "objectives": "Process gigabytes of structured security logs per second using zero-copy deserialization in Rust.", "lab": "Write a Rust utility that ingests a 1GB raw JSON web access log file, parses entries with Serde, and aggregates IP status code metrics in under 3 seconds.", "interview_q": "What is 'zero-copy deserialization' in Serde, and why does it drastically reduce CPU and memory overhead during high-volume log parsing?"},
                    {"day_num": 185, "title": "CLI Engineering — Crafting Professional Security Tools with Clap", "topics": ["Command-line interface design standards for security tools: Intuitive flags, help menus, colorized outputs", "The `clap` crate (derive API): Building type-safe command-line arguments using Rust structs", "Implementing subcommands (e.g. `scan`, `probe`, `parse`) within a unified security toolkit binary", "Adding colorized output and spinners with `colored` and `indicatif`", "Building cross-platform release binaries for Windows and Linux"], "objectives": "Structure your Rust security utilities into a cohesive, professional command-line suite using `clap`.", "lab": "Integrate your port scanner and HTTP prober into a single unified CLI utility called `sec-tool` with subcommands, help menus, and progress bars.", "interview_q": "Why is using a declarative derive-based CLI framework like `clap` preferable to manual argument parsing when building complex security tools?"}
                ]
            },
            {
                "week_num": 38,
                "week_id": "week-38-low-level-security",
                "week_title": "Low-Level Security Concepts & Binary Tooling",
                "objective": "Understand unsafe Rust, raw pointer manipulation, Foreign Function Interface (FFI) with Windows Win32 APIs, raw packet crafting, and memory injection.",
                "tools": ["Rust", "windows-sys crate", "pnet crate", "Black Hat Rust", "x64dbg"],
                "major_concepts": ["Unsafe Rust Mechanics", "Win32 API Interaction via FFI", "Raw Sockets & Packet Crafting", "Process Injection in Rust", "Compiling Minimal Binaries"],
                "weekly_lab": "Deliverable 8 Lab: Build, compile, and document your Personal Security Toolkit (Fast Async Scanner + Raw Socket Tool + Win32 Injector) in Rust.",
                "deliverable": "Deliverable 8: Personal Security Toolkit (Compiled Rust & Python Utilities + Source Code + Performance Benchmarks)",
                "days": [
                    {"day_num": 186, "title": "Unsafe Rust & Low-Level Memory Manipulation", "topics": ["The `unsafe` keyword: Dereferencing raw pointers (`*const T`, `*mut T`), calling unsafe functions", "Why unsafe exists: Interfacing with hardware, OS syscalls, and foreign language code", "Raw memory allocation: Allocating and freeing unmanaged memory buffers", "Transmuting types: `std::mem::transmute` risks and mechanics", "Encapsulating unsafe code within safe abstractions"], "objectives": "Work directly with raw pointers and unmanaged memory safely inside controlled Rust wrappers.", "lab": "Write an unsafe Rust module that manipulates a raw byte buffer, applies a byte-level XOR transformation, and verifies memory integrity.", "interview_q": "What five specific capabilities does the `unsafe` keyword unlock in Rust, and why does unsafe Rust not turn off the borrow checker for safe code?"},
                    {"day_num": 187, "title": "Foreign Function Interface (FFI) & Win32 API Interaction", "topics": ["Foreign Function Interface (FFI) fundamentals: Calling C functions and operating system libraries from Rust", "Interfacing with the Windows API: The `windows-sys` and `windows` crates", "Calling `kernel32.dll` APIs: `GetCurrentProcessId`, `OpenProcess`, `VirtualAlloc`", "Calling Linux `libc` APIs: System calls, memory mapping (`mmap`)", "Marshaling data types across language boundaries: C strings vs Rust strings"], "objectives": "Invoke native Windows Win32 and Linux libc APIs directly from Rust code using FFI.", "lab": "Write a Rust program that uses FFI to call Windows `GetCurrentProcessId` and `VirtualAlloc` to allocate an executable memory page.", "interview_q": "What safety responsibilities fall on the software engineer when passing data pointers across an FFI boundary to a native C library?"},
                    {"day_num": 188, "title": "Raw Sockets & Packet Crafting in Rust (`pnet`)", "topics": ["Raw socket programming: Bypassing the OS transport layer to craft arbitrary Layer 2/3 packets", "The `pnet` (packet network) crate: Parsing and constructing Ethernet, IPv4, TCP, and UDP packets", "Calculating IP and TCP checksums in software", "Crafting custom TCP SYN packets for raw scanning", "Operating system permissions and raw socket capabilities (`cap_net_raw` on Linux)"], "objectives": "Craft and transmit custom Layer 3/4 network packets programmatically using raw sockets in Rust.", "lab": "Use the `pnet` crate to construct a custom TCP SYN packet with specific sequence numbers and send it over a raw socket to a lab target.", "interview_q": "Why does sending custom raw TCP packets require administrative / root privileges on both Windows and Linux operating systems?"},
                    {"day_num": 189, "title": "Windows Process Injection Primer in Rust", "topics": ["Implementing classic process injection in Rust using Win32 API FFI", "The injection workflow: `OpenProcess` -> `VirtualAllocEx` -> `WriteProcessMemory` -> `CreateRemoteThread`", "Defining Windows API types, constants, and function pointers in Rust", "Handling shellcode execution: Testing benign shellcode (e.g. launching calc.exe)", "Compiling minimal, dependency-free Rust binaries (stripping symbols, disabling unwinding, LTO)"], "objectives": "Develop a compiled Windows process injector in Rust that allocates memory and executes shellcode in a remote process.", "lab": "Build a Rust utility that injects benign shellcode into a target process (e.g. `notepad.exe`) using Win32 API calls; analyze resulting process handles in Process Hacker.", "interview_q": "Walk through the four core Win32 API calls used in classic remote thread injection and explain what each call accomplishes."},
                    {"day_num": 190, "title": "Phase 8 Capstone Deliverable — Personal Security Toolkit", "topics": ["Finalizing the Personal Security Toolkit repository in `projects/project-08-personal-security-toolkit`", "Packaging compiled binaries: `rust-port-scan`, `rust-http-probe`, and `rust-log-parser`", "Configuring automated cross-compilation with `cross` (targeting x86_64-pc-windows-msvc and x86_64-unknown-linux-gnu)", "Writing comprehensive documentation: Usage instructions, CLI help text, performance benchmarks against existing tools", "Publishing clean, idiomatic, and documented open-source code"], "objectives": "Complete Deliverable 8: A high-performance, documented Personal Security Toolkit written in Rust and Python.", "lab": "Benchmark your compiled Rust port scanner against Nmap on a local subnet; record performance metrics, document source code, and finalize Deliverable 8.", "interview_q": "How does writing your own custom security tooling in Rust improve both your offensive edge and your understanding of defensive detection?"}
                ]
            }
        ]
    },

    # PHASE 9 (Weeks 39-40, Days 191-200)
    {
        "phase_num": 9,
        "phase_id": "phase-09-purple-team",
        "phase_title": "Purple Team + Automation + Capstone",
        "weeks_range": "Weeks 39–40",
        "days_range": "Days 191–200",
        "objective": "Integrate offensive execution with defensive engineering into a unified Purple Team feedback loop, automate adversary simulations, and complete the comprehensive enterprise Capstone project.",
        "skills": ["Purple team exercise orchestration (PTEF)", "Attack -> Telemetry -> Detection -> Retest loop", "Adversary emulation automation (Caldera / Atomic)", "Detection coverage matrix mapping with ATT&CK Navigator", "Full-scale enterprise hybrid lab compromise and defense", "Executive & technical security portfolio documentation"],
        "tools": ["MITRE Caldera", "Atomic Red Team", "VECTR", "ATT&CK Navigator", "Wazuh", "Sliver", "BloodHound", "Sysmon"],
        "project_id": "project-09-purple-team-platform",
        "project_title": "Purple Team Security Operations Platform (Full Enterprise Hybrid Lab Simulation, Automated Attack Matrix, Telemetry Engineering & Defense Portfolio)",
        "weeks": [
            {
                "week_num": 39,
                "week_id": "week-39-purple-team-integration",
                "week_title": "Purple Team Integration & Continuous Retesting",
                "objective": "Execute collaborative purple team exercises, bridge offensive and defensive disciplines, map detection matrices, and automate continuous testing.",
                "tools": ["MITRE ATT&CK Navigator", "VECTR", "Atomic Red Team", "Caldera", "Wazuh"],
                "major_concepts": ["Purple Team Feedback Loop", "PTEF Framework", "Threat Matrix Mapping", "Automated Adversary Emulation", "Collaborative Remediation"],
                "weekly_lab": "Purple Team Exercise Lab: Execute a 10-technique attack plan collaboratively; verify telemetry; tune SIEM rules; retest to confirm detection.",
                "deliverable": "Purple Team Exercise Matrix & Detection Tuning Playbook",
                "days": [
                    {"day_num": 191, "title": "The Purple Team Philosophy — Bridging Offense & Defense", "topics": ["The traditional silos between Red Teams (offensive testing) and Blue Teams (defensive operations)", "Purple Teaming definition: Collaborative, transparent security testing aimed at measurably improving detection and response", "The Purple Team Exercise Framework (PTEF by Scythe / SANS)", "Roles in a Purple Team exercise: Red operator, Blue defender, Exercise coordinator, Technology owners", "Fostering a blameless culture focused on detection engineering validation"], "objectives": "Explain the collaborative methodology and operational value of Purple Team engagements.", "lab": "Establish a Purple Team exercise charter for a test environment, specifying 5 target techniques, participants, and scoring criteria.", "interview_q": "Why do traditional annual penetration tests often fail to improve an organization's SOC detection capabilities compared to recurring Purple Team exercises?"},
                    {"day_num": 192, "title": "The Purple Team Feedback Loop: Attack → Telemetry → Detection → Retest", "topics": ["The 6-step Purple Team technical execution loop: 1. Attack Execution -> 2. Telemetry Verification -> 3. Alert Validation -> 4. Rule Tuning -> 5. Retest -> 6. Documentation", "Verifying the difference between log generation (telemetry exists) and alert generation (SIEM fired)", "Tuning detection rules in real-time during live exercise execution", "Measuring time-to-detect and quality of contextual alert data for analysts", "Validating that rule tuning does not introduce unacceptable false positive noise"], "objectives": "Execute the live technical feedback loop: Run an attack, inspect logs, write/tune detection rules, and retest until detection succeeds.", "lab": "Execute an unquoted service path exploit; observe that Sysmon logged the event but Wazuh did not alert; write a custom Wazuh rule and retest to confirm alert.", "interview_q": "Walk through an example of the Purple Team feedback loop starting from an un-detected Kerberoasting attack to a validated high-fidelity SIEM alert."},
                    {"day_num": 193, "title": "Threat Modeling & Detection Coverage Matrices (ATT&CK Navigator)", "topics": ["Visualizing security posture using the MITRE ATT&CK Navigator", "Creating customized layer files: Color-coding techniques by visibility (Green = Detected, Yellow = Telemetry Only, Red = Blind)", "Heatmap scoring: Weighting techniques by threat intelligence relevance to the organization's industry", "Tracking historical coverage improvements across consecutive exercise cycles", "Identifying enterprise architectural blind spots across the matrix"], "objectives": "Build and manipulate MITRE ATT&CK Navigator heatmaps to track detection coverage improvements.", "lab": "Create an ATT&CK Navigator JSON layer mapping 30 common adversary techniques, scored by your current lab detection capabilities.", "interview_q": "How does an ATT&CK Navigator heatmap help C-suite executives visualize an enterprise's true threat detection coverage?"},
                    {"day_num": 194, "title": "Adversary Emulation Automation — Caldera & Scripted Chains", "topics": ["Automating purple team exercises: Eliminating manual repetition through scripted attack playbooks", "MITRE Caldera architecture: Server, Agents, Abilities, Adversary Profiles, Operations", "Orchestrating automated multi-step attack chains with Caldera", "Writing custom Caldera abilities in YAML using PowerShell, Bash, and Python", "Continuous security validation: Running automated adversary emulation daily to guard against detection drift"], "objectives": "Deploy MITRE Caldera and execute automated adversary emulation operations against lab endpoints.", "lab": "Deploy MITRE Caldera, configure an agent on Windows, and execute an automated discovery and credential access adversary profile.", "interview_q": "What is 'detection drift', and how does continuous automated adversary emulation prevent detection rules from silently failing over time?"},
                    {"day_num": 195, "title": "Authoring Actionable Purple Team Remediation & Engineering Plans", "topics": ["Translating exercise findings into engineering roadmaps: Tactical vs Strategic improvements", "Tactical fixes: Deploying new Sigma rules, modifying Sysmon configs, fixing file ACLs", "Strategic fixes: Migrating to gMSAs, deploying tiered administrative models, network segmentation", "Documenting remediation with exact code snippets, GPO paths, and architecture diagrams", "Calculating quantitative detection posture improvement metrics"], "objectives": "Write actionable, technically detailed engineering remediation guides based on Purple Team findings.", "lab": "Draft a formal Purple Team Remediation Plan detailing exact GPO modifications and detection rule deployments for 5 exploited weaknesses.", "interview_q": "How do you prioritize remediation actions when an exercise reveals both critical configuration weaknesses and complete detection blind spots?"}
                ]
            },
            {
                "week_num": 40,
                "week_id": "week-40-final-capstone",
                "week_title": "Final Capstone Project & Security Operations Platform",
                "objective": "Execute the comprehensive end-to-end Capstone simulation across enterprise hybrid infrastructure, engineer the complete defense detection suite, and finalize your professional portfolio.",
                "tools": ["All curriculum tools", "Wazuh", "Sliver", "BloodHound", "Sysmon", "Ghidra", "Rust Toolkit", "Markdown"],
                "major_concepts": ["Enterprise Capstone Scenario", "Full Kill-Chain Attack Simulation", "Telemetry & Detection Suite", "Incident Reconstruction", "Master Security Portfolio"],
                "weekly_lab": "Final Capstone Deliverable Lab: Execute full hybrid enterprise compromise, capture all forensic telemetry, deploy custom detections, and finalize the complete portfolio.",
                "deliverable": "Final Deliverable: 'Purple Team Security Operations Platform' (Full Enterprise Simulation, Detection Suite, Architecture & Master Portfolio)",
                "days": [
                    {"day_num": 196, "title": "Capstone Architecture: Enterprise Scenario Design & Infrastructure", "topics": ["The Final Capstone Scenario: A realistic hybrid enterprise environment (Public Web, DMZ Linux, Internal Windows AD, Workstations, Database)", "Deploying and verifying all infrastructure components, networking, and routing", "Configuring target vulnerabilities across each tier: Web injection -> Local PrivEsc -> AD lateral movement -> Cloud/DB objective", "Verifying baseline telemetry collection across all endpoints (Wazuh, Sysmon, Auditd, Zeek)", "Establishing the simulation timeline and evaluation rubric"], "objectives": "Architect and initialize the full enterprise multi-tier infrastructure for the final Capstone simulation.", "lab": "Deploy the complete Capstone multi-machine lab topology; verify connectivity, baseline logging, and attack path viability.", "interview_q": "How do you architect a multi-tier enterprise lab to realistically mirror a corporate network while maintaining absolute containment?"},
                    {"day_num": 197, "title": "Executing Authorized Multi-Vector Attack Simulation", "topics": ["Executing the full offensive operation from external recon to ultimate enterprise objective", "Phase 1: External reconnaissance and web application exploitation", "Phase 2: Initial foothold establishment and local privilege escalation on beachhead", "Phase 3: Active Directory enumeration and BloodHound attack path identification", "Phase 4: Lateral movement across network tiers to Domain Controller and crown jewel objective", "Recording exact microsecond timestamps for every action taken"], "objectives": "Execute a full-scope, multi-stage adversary simulation across the enterprise lab, capturing all flags.", "lab": "Execute the end-to-end attack chain in the lab from external web exploit to Domain Controller takeover, logging all timestamps and artifacts.", "interview_q": "During a multi-stage attack simulation, how do you ensure your offensive actions leave clear, traceable footprints for defensive correlation?"},
                    {"day_num": 198, "title": "Engineering Custom Detections & Mitigations for All Vectors", "topics": ["Reviewing the defensive telemetry captured across the SIEM during yesterday's attack simulation", "Engineering custom Sigma detection rules for every single attack phase that went undetected", "Deploying and testing newly developed Wazuh decoders and rules", "Hardening system configurations: Disabling vulnerable AD CS templates, enforcing SMB signing, restricting tokens", "Validating that all attack techniques are now actively alerted in real-time"], "objectives": "Engineer and deploy a comprehensive detection rule suite that covers every technique executed in the simulation.", "lab": "Author and deploy 10 new custom detection rules in your SIEM covering each step of the simulation; re-run attack scripts to verify 100% detection.", "interview_q": "How do you ensure that newly written detection rules are resilient against simple adversary evasion (like changing binary names or command flags)?"},
                    {"day_num": 199, "title": "Digital Forensics & Comprehensive Timeline Reconstruction", "topics": ["Conducting post-incident forensic analysis on the compromised Capstone systems", "Extracting memory dumps and analyzing with Volatility 3: Identifying the injected beacon and dumped credentials", "Parsing MFT, Prefetch, and Shimcache to reconstruct the exact forensic execution timeline", "Reconstructing the complete attack narrative with matching forensic evidence for each milestone", "Documenting defensive lessons learned and architectural improvements"], "objectives": "Perform deep forensic analysis on simulated target artifacts to reconstruct the attack timeline with forensic evidence.", "lab": "Extract forensic artifacts from the compromised Domain Controller and workstations; verify that forensic timelines match the red team execution log.", "interview_q": "How does combining live SIEM telemetry with dead-box disk and memory forensics provide a complete picture of an incident?"},
                    {"day_num": 200, "title": "Final Capstone Deliverable — Purple Team Security Platform", "topics": ["Consolidating all 40 weeks, 200 days, 8 deliverables, and Capstone results into the master portfolio", "Authoring the Final Deliverable: 'Purple Team Security Operations Platform' in `projects/project-09-purple-team-platform/`", "Assembling the professional GitHub portfolio: Architecture diagrams, attack narratives, detection suites, Rust toolkits, and reports", "Verifying all links, daily journals, checklists, and progress markers across the repository", "Conducting a comprehensive self-assessment and preparing for advanced security practitioner / purple team technical interviews"], "objectives": "Finalize and publish the complete, professional CYBERSECURITY-MASTER-JOURNAL repository and Capstone platform.", "lab": "Review and verify all 200 daily journals, run progress calculation scripts, compile Deliverable 9 documentation, and push the complete portfolio to Git.", "interview_q": "Reflecting on this entire 200-day journey from networking fundamentals to purple teaming and Rust development, how has your perspective on cybersecurity engineering evolved?"}
                ]
            }
        ]
    }
]

print(f"[*] Defined Phases 6 through 9 ({len(phases_6_9)} phases).")

