"""
Curriculum Generator Part 3:
Defines Phase 4 (Vulnerability Research) and Phase 5 (Red Team Operations).
"""

phases_4_5 = [
    # PHASE 4 (Weeks 19-21, Days 91-105)
    {
        "phase_num": 4,
        "phase_id": "phase-04-cve-research",
        "phase_title": "Vulnerability Research + CVE Intelligence",
        "weeks_range": "Weeks 19–21",
        "days_range": "Days 091–105",
        "objective": "Understand the vulnerability discovery lifecycle, scoring metrics (CVSS/EPSS), safe proof-of-concept research and sandboxed reproduction, and building automated CVE intelligence pipelines.",
        "skills": ["CVE/CWE/NVD lifecycle", "CVSS v3.1/v4.0 & EPSS scoring", "PoC code auditing & safety verification", "Docker sandbox exploit reproduction", "Root cause analysis & patch diffing", "Building automated CVE ingestion & triage pipelines"],
        "tools": ["trickest/cve", "NVD API", "CISA KEV", "GitHub Advisory Database", "Docker Compose", "Python 3", "Ghidra / diffing tools"],
        "project_id": "project-04-cve-intelligence-pipeline",
        "project_title": "CVE Research & Intelligence Pipeline (Feed Ingestion + Version Matching + PoC Discovery + Alerting)",
        "weeks": [
            {
                "week_num": 19,
                "week_id": "week-19-vulnerability-fundamentals",
                "week_title": "Vulnerability Fundamentals & Scoring",
                "objective": "Master the vulnerability taxonomy, CVE assigning authorities, CVSS calculation metrics, EPSS probabilities, and root-cause classification.",
                "tools": ["NVD Calculator", "EPSS API", "CWE Taxonomy", "CISA KEV Catalog"],
                "major_concepts": ["CVE Lifecycle", "CNA Assigning Authorities", "CVSS v3.1 / v4.0 Metrics", "EPSS Exploit Prediction", "Root Cause Taxonomy", "Patch Diffing"],
                "weekly_lab": "Vulnerability Scoring & Taxonomy Lab: Score five diverse CVEs across CVSS v3.1, calculate EPSS percentiles, and categorize CWE root causes.",
                "deliverable": "Vulnerability Taxonomy & Severity Scoring Guidebook",
                "days": [
                    {"day_num": 91, "title": "The Vulnerability Lifecycle — CVE IDs, NVD & MITRE CNA Process", "topics": ["The birth of a vulnerability: Responsible disclosure vs zero-day discovery", "MITRE CVE program: CVE Identifiers, syntax, and allocation rules", "CVE Numbering Authorities (CNAs): Vendors, researchers, third-party coordinators", "The National Vulnerability Database (NVD) enrichment process: Adding CPEs, CVSS, and references", "CISA Known Exploited Vulnerabilities (KEV) catalog and binding operational directives"], "objectives": "Understand how vulnerabilities are tracked, assigned identifiers, and published globally.", "lab": "Query the NVD REST API using Python to retrieve full metadata, references, and CPE dictionaries for recent critical CVEs.", "interview_q": "What is the role of a CVE Numbering Authority (CNA), and why is inclusion in CISA's KEV catalog critical for vulnerability prioritization?"},
                    {"day_num": 92, "title": "Common Weakness Enumeration (CWE) Taxonomy & Software Flaws", "topics": ["CWE hierarchy: Pillars, Classes, Base weaknesses, and Variants", "Top 25 Most Dangerous Software Weaknesses (OWASP / CWE Top 25)", "Memory corruption CWEs: Buffer Overflows (CWE-119), Use-After-Free (CWE-416)", "Input validation CWEs: SQL Injection (CWE-89), OS Command Injection (CWE-78), Path Traversal (CWE-22)", "Logic and design flaws: Improper Authentication (CWE-287), Missing Authorization (CWE-862)"], "objectives": "Categorize software vulnerabilities into standardized CWE weaknesses to determine fundamental architectural flaws.", "lab": "Map a set of ten recent CVE advisories to their underlying CWE classifications and examine the shared flaw patterns.", "interview_q": "Explain the difference between a CVE and a CWE, and how understanding CWEs helps software engineering teams build secure code."},
                    {"day_num": 93, "title": "Vulnerability Scoring Metrics — CVSS v3.1 / v4.0 & EPSS", "topics": ["CVSS v3.1 Base Score metrics: AV (Attack Vector), AC (Complexity), PR (Privileges), UI (User Interaction), S (Scope), CIA", "CVSS v4.0 updates: Threat metrics, Environmental metrics, and granularity", "The Exploit Prediction Scoring System (EPSS): Statistical probability of real-world exploitation in 30 days", "EPSS vs CVSS: Why high CVSS scores without exploitability can distort remediation priorities", "Calculating dual CVSS/EPSS risk matrices for enterprise triage"], "objectives": "Calculate CVSS base scores accurately and integrate EPSS exploit probability scores into triage decisions.", "lab": "Calculate CVSS v3.1 and v4.0 vector strings for a remote unauthenticated RCE and contrast with an authenticated local DoS; query EPSS API scores.", "interview_q": "How does EPSS differ from CVSS, and why might an organization patch an EPSS 0.85 / CVSS 6.5 flaw before a CVSS 9.8 flaw with EPSS 0.01?"},
                    {"day_num": 94, "title": "Root Cause Analysis — Memory Safety vs Logic Flaws vs Injection", "topics": ["Root cause analysis methodology: Isolating the exact commit, function, and variable responsible for failure", "Memory safety violations in C/C++: Out-of-bounds reads/writes, null pointer dereferences, race conditions", "Type confusion and integer overflow vulnerabilities", "Logic flaws: Missing validation checks, state desynchronization, flawed cryptographic implementations", "Writing structured Root Cause Analysis (RCA) documents"], "objectives": "Perform root cause analysis on documented software defects to understand exactly why and how an exploit triggers.", "lab": "Analyze the source code patch of a real open-source vulnerability (e.g. an injection or memory flaw) to identify the specific bug and fix.", "interview_q": "When conducting root cause analysis, why is identifying the CWE category more valuable for long-term software security than simply describing the exploit?"},
                    {"day_num": 95, "title": "Attack Surface Modeling & Patch Diffing Fundamentals", "topics": ["Attack surface identification: Entry points, trust boundaries, data flows, and protocols", "Patch diffing methodology: Comparing pre-patch and post-patch source code or compiled binaries", "Source code diffing tools: git diff, difftastic, meld", "Binary diffing tools: Ghidra Version Tracking, BinDiff, Diaphora overview", "Identifying security patches in vendor changelogs when CVE details are withheld (silent patching)"], "objectives": "Analyze code diffs between software versions to pinpoint newly introduced or patched security flaws.", "lab": "Perform a git diff on a vulnerable open-source library repository (e.g. Log4j or a Node package) to identify the patch logic and trigger conditions.", "interview_q": "What is 'patch diffing', and how do security researchers reverse-engineer security advisories when vendors do not publish exploit details?"}
                ]
            },
            {
                "week_num": 20,
                "week_id": "week-20-cve-poc-research",
                "week_title": "CVE / PoC Research & Safe Lab Reproduction",
                "objective": "Discover public proof-of-concept exploits, audit exploit code for safety, reproduce vulnerabilities in isolated sandboxes, and verify patches.",
                "tools": ["trickest/cve", "Exploit-DB", "GitHub Advisories", "Docker Compose", "Wireshark", "Python"],
                "major_concepts": ["PoC Discovery", "Malicious Exploit Screening", "Sandbox Isolation", "Exploit Trigger Analysis", "Patch Verification"],
                "weekly_lab": "Vulnerability Reproduction Lab: Build an isolated Docker container with a vulnerable software release, audit a public PoC, execute it safely, and verify the patch.",
                "deliverable": "CVE Safe Reproduction & Patch Verification Dossier",
                "days": [
                    {"day_num": 96, "title": "Discovering & Triaging Public Proof-of-Concepts (PoCs)", "topics": ["Public PoC repositories: `trickest/cve` repository, Exploit-DB, Packet Storm, GitHub Advisories", "Monitoring zero-day and n-day releases on Twitter / InfoSec mastodon and RSS feeds", "Evaluating PoC quality: Theoretical PoCs vs Dos vs Weaponized Remote Code Execution", "Assessing weaponization speed: Time-to-exploit metrics from disclosure to mass scanning", "Structuring a local PoC research archive"], "objectives": "Find and triage public exploit code from reputable security research sources.", "lab": "Clone and navigate the `trickest/cve` repository structure using CLI tools to extract verified PoC links for a targeted software package.", "interview_q": "What indicators in a newly released GitHub repository claiming to be a zero-day PoC should alert you that it might be fake or malicious?"},
                    {"day_num": 97, "title": "Auditing PoC Code Safety & Malicious Exploit Detection", "topics": ["The rise of weaponized fake PoCs targeting security researchers (infostealers, backdoors in PoCs)", "Static code analysis of exploit scripts (Python, C, Bash) before execution", "Detecting obfuscated base64 payloads, eval() statements, and unexpected network callbacks", "Checking compiled binary PoCs: Sandboxed static string extraction and disassembly", "Rules for safe handling: Never run untrusted PoCs on bare metal or production host systems"], "objectives": "Audit public exploit scripts to ensure they are safe and do not contain backdoors or malicious secondary payloads.", "lab": "Deconstruct a suspicious Python exploit script containing encoded payloads; safely extract and decode its strings without execution.", "interview_q": "What steps do you take to audit and safely verify a public exploit script found on GitHub before running it against a test target?"},
                    {"day_num": 98, "title": "Reproducing CVEs in Isolated Sandbox Environments", "topics": ["Building reproducible target environments with Docker and Docker Compose", "Pinning vulnerable software package versions and dependencies", "Configuring isolated container networks: Disabling external internet access during exploit tests", "Vagrant and Hyper-V for complex multi-tier application setups", "Capturing baseline snapshots before testing"], "objectives": "Spin up isolated, version-pinned test containers to safely reproduce vulnerabilities.", "lab": "Create a `docker-compose.yml` file deploying a vulnerable web server version (e.g. vulnerable Apache/Spring/Tomcat) on an internal-only network.", "interview_q": "Why is Docker containerization ideal for reproducing web application CVEs, and what limitations does containerization have when testing kernel CVEs?"},
                    {"day_num": 99, "title": "Deconstructing Exploit Triggers & Network Payloads", "topics": ["Dissecting the exploit payload byte-by-byte: Headers, parameters, magic bytes, shellcode", "Tracing the exploit packet execution flow in Wireshark", "Observing target server logs during successful and unsuccessful exploitation attempts", "Modifying PoC payloads to carry harmless non-destructive markers (e.g. `echo 'vuln_verified' > /tmp/proof`)", "Understanding crash vs execution vs memory leak responses"], "objectives": "Analyze the exact network packets that trigger a vulnerability and replace weaponized payloads with benign verification markers.", "lab": "Intercept a public exploit script's HTTP traffic in Burp Suite, inspect the malformed payload, and modify it to execute a benign verification command.", "interview_q": "How do you modify a public Remote Code Execution PoC to prove vulnerability existence to a client without creating operational stability risks?"},
                    {"day_num": 100, "title": "Patch Analysis & Remediation Verification in Labs", "topics": ["Applying official vendor patches in the sandbox environment", "Rerunning the exploit payload against the patched service to confirm remediation", "Analyzing defensive error handling: Does the application reject, sanitize, or drop the input?", "Checking for bypasses: Did the patch fix the root cause or merely filter specific characters?", "Drafting actionable remediation advisories for engineering teams"], "objectives": "Verify that applying software updates or configuration mitigations completely neutralizes the exploit trigger.", "lab": "Upgrade the vulnerable Docker container to the patched release, re-execute the exploit script, and verify that the request is safely rejected.", "interview_q": "What is the difference between a workaround (such as a WAF rule) and an official vendor patch, and why are workarounds often bypassed?"}
                ]
            },
            {
                "week_num": 21,
                "week_id": "week-21-vulnerability-intelligence",
                "week_title": "Automated Vulnerability Intelligence Pipeline",
                "objective": "Build an automated Python vulnerability intelligence pipeline that ingests CVE feeds, matches company asset inventories, and alerts on actionable threats.",
                "tools": ["Python 3", "NVD REST API", "trickest/cve", "CISA KEV", "GitHub API", "SQLite / JSON"],
                "major_concepts": ["API Feed Ingestion", "CPE / SemVer Matching", "Threat Enrichment", "Triage Automation", "Remediation Ticket Mapping"],
                "weekly_lab": "Deliverable 4 Lab: Build and run a Python script that polls NVD/CISA feeds, matches assets in an inventory, enriches with EPSS/PoCs, and exports a markdown report.",
                "deliverable": "Deliverable 4: CVE Research & Intelligence Pipeline (Source code, sample ingested data, version matcher, and automated advisory)",
                "days": [
                    {"day_num": 101, "title": "Ingesting CVE Feeds — NVD, CISA KEV & GitHub Advisory APIs", "topics": ["Designing automated vulnerability ingestion pipelines", "Interfacing with the NVD 2.0 REST API (handling API keys, rate limits, pagination)", "Consuming the CISA Known Exploited Vulnerabilities (KEV) JSON feed", "Querying GitHub Security Advisories GraphQL/REST endpoints", "Storing raw vulnerability telemetry in structured local databases (SQLite/JSON)"], "objectives": "Write Python scripts to periodically poll and ingest vulnerability feeds from authoritative global repositories.", "lab": "Write a Python script to ingest the latest 50 CVEs from the NVD API and CISA KEV feed and store them in an SQLite database.", "interview_q": "Why is polling the CISA KEV catalog crucial for enterprise vulnerability management compared to relying solely on NVD CVSS scores?"},
                    {"day_num": 102, "title": "Automated Asset Matching & Version Comparison Logic", "topics": ["Common Platform Enumeration (CPE) 2.3 format breakdown (part, vendor, product, version, update)", "Semantic Versioning (SemVer) comparison algorithms in Python", "Building a mock corporate asset inventory (servers, installed packages, versions)", "Matching ingested CVE vulnerable ranges against active asset inventory versions", "Handling complex version ranges (e.g. `>= 2.0.0, < 2.4.12`)"], "objectives": "Implement algorithmic version comparison logic to match new CVE disclosures against deployed software assets.", "lab": "Implement a Python function that parses CPE version ranges and determines whether software version `2.4.5` is vulnerable to a specified CVE range.", "interview_q": "What challenges arise when attempting to automatically match software product names and versions from scanner outputs against NVD CPE strings?"},
                    {"day_num": 103, "title": "Enriching Vulnerability Data with Exploit Intelligence", "topics": ["Integrating FIRST EPSS API to pull real-time exploitation probability scores", "Cross-referencing GitHub PoC availability using `trickest/cve` index and GitHub search", "Assigning operational risk tiers: Tier 1 (KEV listed + High EPSS + Public PoC), Tier 2 (High CVSS + PoC), Tier 3 (Theoretical)", "Detecting ransomware and APT threat group weaponization tags", "Data normalization across multiple intelligence sources"], "objectives": "Enrich raw CVE entries with real-world threat context, exploit availability, and EPSS metrics.", "lab": "Enhance the Python pipeline to automatically fetch EPSS scores and verify whether public PoCs exist on GitHub for flagged assets.", "interview_q": "How does enriching a vulnerability with exploit intelligence (such as public PoC availability) change the remediation priority for security operations?"},
                    {"day_num": 104, "title": "Designing Automated Security Alerts & Remediation Mapping", "topics": ["Defining alerting thresholds: Alerting on Critical assets + Active Exploitation indicators", "Formatting automated notifications: Markdown summaries, Slack/Teams webhook integration", "Mapping vulnerabilities to concrete remediation steps: Patch download links, configuration workarounds", "Generating standardized Jira / ServiceNow remediation ticket payloads via JSON", "Preventing alert fatigue: Deduplication and state tracking"], "objectives": "Format and deliver actionable, prioritized vulnerability alerts containing technical remediation guidance.", "lab": "Write an alerting module that formats high-priority matches into clean Markdown reports and generates simulated Jira ticket JSON payloads.", "interview_q": "What information must be included in an automated vulnerability alert to enable software engineers to apply patches immediately?"},
                    {"day_num": 105, "title": "Phase 4 Capstone Deliverable — CVE Intelligence Pipeline", "topics": ["Finalizing the automated Python vulnerability intelligence pipeline", "Testing end-to-end execution: Feed Ingestion -> Asset Matching -> Threat Enrichment -> Report Output", "Authoring complete Deliverable 4 documentation: Architecture diagram, API setup guide, sample dataset", "Validating pipeline output with known historical CVEs against mock server inventories", "Packaging the pipeline as a standalone reusable security engineering tool"], "objectives": "Complete Deliverable 4: A functional, documented Python CVE Research & Intelligence Pipeline.", "lab": "Execute the full pipeline script against a test asset inventory of 20 systems; generate Deliverable 4 markdown report and commit code to `projects/`.", "interview_q": "How would you scale this vulnerability intelligence pipeline to monitor thousands of container images and cloud instances across an enterprise?"}
                ]
            }
        ]
    },

    # PHASE 5 (Weeks 22-27, Days 106-135)
    {
        "phase_num": 5,
        "phase_id": "phase-05-red-team",
        "phase_title": "Red Team Operations + Adversary Emulation",
        "weeks_range": "Weeks 22–27",
        "days_range": "Days 106–135",
        "objective": "Plan and execute enterprise-grade adversary emulation engagements, implement tiered C2 infrastructure, weaponize payloads, maintain OPSEC, and conduct full authorized multi-phase attack simulations.",
        "skills": ["Red team scoping & Rules of Engagement (RoE)", "Tiered C2 architecture (Long Haul / Short Haul / Interactive)", "Payload weaponization & AMSI/EDR evasion concepts", "Sliver C2 operations (Listeners, Beacons, Transports)", "Internal network pivoting & SOCKS proxy tunneling", "Full kill-chain execution & detection gap reporting"],
        "tools": ["Red-Team-Playbooks", "RedTeam-Tools", "Sliver", "Havoc", "Ligolo-ng", "Ghostwriter", "SysReptor", "BloodHound", "Impacket", "Rubeus"],
        "project_id": "project-05-red-team-engagement-report",
        "project_title": "Full Authorized Red Team Engagement Report (Executive Summary + Cyber Kill Chain Narrative + MITRE ATT&CK Matrix + Blue Team Deconfliction)",
        "weeks": [
            {
                "week_num": 22,
                "week_id": "week-22-red-team-methodology",
                "week_title": "Red Team Methodology & OPSEC Architecture",
                "objective": "Understand red teaming versus penetration testing, define ROE, design tiered C2 infrastructure, and enforce operational security.",
                "tools": ["Red-Team-Playbooks", "Ghostwriter", "Nginx", "WireGuard", "AWS / VPS"],
                "major_concepts": ["Red Team vs Pentesting", "Rules of Engagement (RoE)", "Tiered C2 Infrastructure", "Functional Segregation", "Redirectors", "OPSEC Golden Rules"],
                "weekly_lab": "C2 Infrastructure Architecture Lab: Design and diagram a 3-tiered C2 architecture with redirectors, payload servers, and operational separation.",
                "deliverable": "Red Team Standard Operating Procedure (SOP) & Infrastructure Architecture Blueprint",
                "days": [
                    {"day_num": 106, "title": "Red Team Operations vs Penetration Testing — Goals, Scope & Threat Emulation", "topics": ["Differentiating penetration testing (broad vulnerability identification) from red teaming (adversary emulation)", "Measuring people, process, and technology: Testing blue team detection and response capabilities", "Threat actor profiling: Emulating specific APT tactics, techniques, and procedures (TTPs)", "Scoping an engagement: White carding, flags, objectives, and success criteria", "The Unified Cyber Kill Chain and MITRE ATT&CK enterprise matrix"], "objectives": "Articulate the unique objectives, philosophy, and measurement criteria of enterprise red teaming engagements.", "lab": "Draft an adversary emulation plan targeting a mock financial institution, specifying threat actor profile, objective flags, and attack constraints.", "interview_q": "How do you explain the difference between a penetration test and a red team engagement to an executive who believes they are identical?"},
                    {"day_num": 107, "title": "Pre-Engagement Scoping, Rules of Engagement (RoE) & Trusted Agents", "topics": ["The Kickoff meeting structure: Stakeholders, emergency escalation pathways, and operational boundaries", "Rules of Engagement (RoE) document drafting: In-scope vs out-of-scope assets, test windows, permitted attack types", "Account lockout policies: Safe password spraying thresholds and observation windows", "Role of Trusted Agents (White Cell): Deconfliction point of contact and handling real incidents", "Drop devices / Penetration Testing Kits (PTK) onsite deployment logistics"], "objectives": "Draft an enterprise Rules of Engagement document and establish safe deconfliction channels.", "lab": "Author a complete Rules of Engagement (RoE) agreement for an enterprise simulation including safe lockout thresholds and emergency stop contacts.", "interview_q": "What is the purpose of a 'Trusted Agent' during a red team exercise, and what immediate actions do you take if a real security incident occurs during testing?"},
                    {"day_num": 108, "title": "Tiered Command & Control (C2) Architecture Design", "topics": ["The multi-tiered C2 architecture model: Managing risk across different operational phases", "Tier 3: Interactive operations (high callback frequency, active keyboard sessions, highest burn risk)", "Tier 2: Short Haul (1–24 hour callbacks, backup session re-establishment)", "Tier 1: Long Haul (24–48+ hour callbacks, deeply blended persistence, high value)", "Handing sessions down the tier model but never up", "Functional segregation: Phishing SMTP, payload staging, long-term C2, short-term C2"], "objectives": "Design an enterprise-grade, resilient, multi-tiered C2 network architecture.", "lab": "Create an architecture diagram of a 3-tier C2 deployment detailing domain categorization, transport channels, and callback intervals.", "interview_q": "Why should a red team operator never run noisy operational commands from a Tier 1 (Long Haul) C2 session?"},
                    {"day_num": 109, "title": "Functional Segregation, Redirectors & Egress Filtering", "topics": ["Role of redirectors: Concealing the true backend C2 team server IP addresses", "HTTP/S reverse proxy redirectors using Nginx and Apache mod_rewrite", "Filtering unauthorized traffic: Redirecting blue team IR and automated scanners to benign websites", "DNS redirectors and DNS-over-HTTPS (DoH) egress", "Domain categorization: Aging domains, establishing reputation, and checking categories (finance, healthcare)"], "objectives": "Configure reverse proxy redirectors that route legitimate beacon traffic to the C2 server while deflecting inspection.", "lab": "Configure an Nginx reverse proxy redirector with regex header filtering to forward valid beacon requests and redirect all others to a benign decoy.", "interview_q": "How does an Nginx mod_rewrite or reverse proxy redirector protect the backend C2 server from being discovered by blue team analysts?"},
                    {"day_num": 110, "title": "Operational Security (OPSEC) Discipline & The Golden Rules", "topics": ["Golden Rules of Red Teaming: Slow and steady, confidence over speed, avoiding CTF-style commands", "Why `nmap -A -T4` or `whoami /all` burns access immediately in mature environments", "Living-off-the-land first: Using existing native binaries before dropping custom tools", "Timestamp manipulation and anti-forensic considerations", "Cleaning up operational artifacts: Tracking every dropped file, registry modification, and user account"], "objectives": "Internalize and practice strict operational security habits to evade detection and preserve engagement longevity.", "lab": "Conduct a mock host landing simulation comparing noisy commands with stealthy native Windows alternatives while reviewing generated logs.", "interview_q": "Why is running native PowerShell commands often more noisy than running unmanaged PowerShell or C# binaries in modern Windows environments?"}
                ]
            },
            {
                "week_num": 23,
                "week_id": "week-23-weaponization-evasion",
                "week_title": "Initial Access & Weaponization Tradecraft",
                "objective": "Master password spraying discipline, payload generation, stagers vs stageless binaries, AMSI/EDR evasion concepts, and delivery vectors.",
                "tools": ["RedTeam-Tools", "msfvenom", "Freeze", "Shellter", "Chimera", "CUPP", "TREVORspray"],
                "major_concepts": ["Password Spraying Strategy", "Stagers vs Stageless Payloads", "AMSI Architecture & Memory Patching", "EDR User-Mode Hooking", "HTML Smuggling"],
                "weekly_lab": "Payload Evasion Lab: Generate shellcode, implement an AMSI bypass in memory, test HTML smuggling delivery, and analyze antivirus detection.",
                "deliverable": "Offensive Weaponization & Evasion Tradecraft Reference",
                "days": [
                    {"day_num": 111, "title": "Password Spraying Strategies & Account Lockout Avoidance", "topics": ["Password spraying theory: Testing one common password against many accounts over time", "Account lockout policies: Thresholds, durations, observation windows, and buffer margins", "Targeting external authentication portals: Office 365, Okta, VPN endpoints, ADFS", "Tools: TREVORspray, CredMaster, SprayingToolkit", "Mitigating proxy IP bans: Rotating egress IPs via AWS API Gateway"], "objectives": "Execute calculated, low-and-slow password spraying campaigns without triggering account lockouts.", "lab": "Simulate a password spraying campaign in an authorized lab with TREVORspray, adhering to strict lockout delay timers.", "interview_q": "How do you calculate safe password spraying intervals if a domain's lockout policy is 5 attempts within a 30-minute observation window?"},
                    {"day_num": 112, "title": "Payload Generation & Encoding — Stagers vs Stageless Binaries", "topics": ["Shellcode fundamentals: Architecture-specific machine code, position-independent code (PIC)", "Staged payloads (small payload fetching larger stage) vs Stageless payloads (self-contained)", "Operational pros and cons: Stager network signatures vs stageless payload size", "Shellcode encodings: XOR, AES encryption, UUID strings, IPv4/IPv6 string encoding", "Tools: msfvenom, Donut (.NET to shellcode converter), Freeze"], "objectives": "Generate and cryptographically protect shellcode payloads to evade static signature detection.", "lab": "Convert a .NET assembly into encrypted shellcode using Donut and embed it within a custom C loader template.", "interview_q": "Explain the architectural difference between a staged and a stageless payload, and why modern red teams strongly prefer stageless implants."},
                    {"day_num": 113, "title": "Defense Evasion Concepts — AMSI Bypass & Process Injection", "topics": ["Antimalware Scan Interface (AMSI) architecture: `amsi.dll` in user processes and `AmsiScanBuffer`", "AMSI memory patching: Patching the beginning of `AmsiScanBuffer` to return `AMSI_RESULT_CLEAN`", "Event Tracing for Windows (ETW) architecture and ETW patching (`EtwEventWrite`)", "EDR user-mode hooking: How EDR DLLs hook `ntdll.dll` syscalls in user space", "Syscalls and indirect syscalls concepts for bypassing hooked APIs"], "objectives": "Understand how endpoint defenses monitor user-space memory and how in-memory patching neutralizes inspection.", "lab": "Examine the bytes of `AmsiScanBuffer` in memory using a debugger, apply an in-memory patch in PowerShell, and verify that blocked strings now run.", "interview_q": "How does AMSI inspect scripts running in PowerShell, and how does in-memory byte patching of `AmsiScanBuffer` disable scanning?"},
                    {"day_num": 114, "title": "Living-off-the-Land Binaries and Scripts (LOLBAS) Execution", "topics": ["The LOLBAS project catalog and philosophy: Using Microsoft-signed binaries for execution and download", "Binary execution proxies: `rundll32.exe`, `regsvr32.exe` (Squiblydoo), `msiexec.exe`, `installutil.exe`", "Living-off-the-land downloaders: `certutil.exe -urlcache -split -f`, `bitsadmin.exe`, PowerShell `System.Net.WebClient`", "Bypassing application whitelisting (AppLocker / WDAC) via LOLBAS", "Defensive monitoring of suspicious LOLBAS parent-child process relationships"], "objectives": "Execute payloads and download stages using pre-installed, trusted operating system utilities.", "lab": "Execute a test payload using `rundll32.exe` and `regsvr32.exe`; download a test file via `certutil` and examine Sysmon event logs generated.", "interview_q": "Why do attackers utilize signed Microsoft binaries like `certutil.exe` or `regsvr32.exe` instead of downloading custom binary tools?"},
                    {"day_num": 115, "title": "Delivery Vectors — HTML Smuggling & Client-Side Payloads", "topics": ["HTML Smuggling mechanics: Assembling file payloads dynamically in JavaScript using Blobs and `window.URL.createObjectURL`", "Bypassing perimeter email gateways and proxy file inspections with HTML smuggling", "Adding anti-sandbox evasion: Mouse move event listeners (Qakbot technique) to delay execution", "Office document macros (VBA) and Mark of the Web (MOTW) protections", "Packaging payloads in ISO and VHD container files to bypass MOTW"], "objectives": "Construct advanced HTML smuggling delivery pages with user-interaction sandbox evasions.", "lab": "Build an HTML smuggling delivery page that requires user mouse movement before constructing and downloading a test payload.", "interview_q": "How does HTML smuggling bypass traditional network boundary security inspection devices like web proxies and email filters?"}
                ]
            },
            {
                "week_num": 24,
                "week_id": "week-24-c2-architecture-sliver",
                "week_title": "Command & Control Architecture with Sliver",
                "objective": "Deploy and operate the open-source Sliver C2 framework, configure diverse transport listeners, generate implants, and manage beacons.",
                "tools": ["Sliver C2", "WireGuard", "mTLS", "DNS", "Go", "Python"],
                "major_concepts": ["Sliver Multiplayer Architecture", "mTLS & WireGuard Transports", "Beacons vs Interactive Sessions", "Jitter & Sleep Timing", "In-Memory Extension Execution"],
                "weekly_lab": "Sliver C2 Deployment Lab: Deploy Sliver server, configure mTLS and HTTP listeners, generate cross-platform implants, and execute in-memory tasks.",
                "deliverable": "Sliver C2 Operator Playbook & Configuration Reference",
                "days": [
                    {"day_num": 116, "title": "Sliver C2 Architecture — Server, Daemon & Multiplayer Client", "topics": ["Sliver architecture: Golang-based open-source adversary emulation framework", "Server daemon configuration, secure operator profile generation (`sliver-server operator --name`)", "Multiplayer console connection over mutual TLS", "Sliver client CLI navigation, syntax, and session management", "Comparing Sliver with Cobalt Strike, Mythic, and Havoc"], "objectives": "Deploy a multi-operator Sliver C2 server and connect securely using operator profiles.", "lab": "Install and start the Sliver server daemon in Kali; generate an operator config file and connect using the `sliver` multiplayer client.", "interview_q": "What advantages does an asynchronous C2 architecture like Sliver offer during distributed team engagements compared to single-user tools like Metasploit?"},
                    {"day_num": 117, "title": "Sliver Transports — mTLS, WireGuard, HTTP/S & DNS Listeners", "topics": ["Transport protocols supported by Sliver: Mutual TLS (mTLS), WireGuard, HTTP/S, and DNS", "Configuring mTLS listeners (`mtls --lport 8888`): High security and encrypted control", "Configuring HTTP/S listeners with custom C2 profiles and HTTP headers", "DNS tunneling transport (`dns --domains ...`): Slow, high-resilience egress via recursive DNS", "Selecting transports based on target egress filtering restrictions"], "objectives": "Configure diverse transport listeners in Sliver to accommodate different network egress scenarios.", "lab": "Configure both an mTLS listener and an HTTP/S listener in Sliver; test client connectivity and inspect network traffic in Wireshark.", "interview_q": "Why is DNS tunneling considered one of the most reliable C2 egress channels in heavily firewalled environments?"},
                    {"day_num": 118, "title": "Generating Sliver Implants — Stagers, Stageless & Formats", "topics": ["Generating implants: `generate --mtls <ip> --os windows --arch amd64`", "Stageless executables (.exe) vs Dynamic Link Libraries (.dll) vs Shellcode (.bin)", "Session implants (real-time interactive connection) vs Beacon implants (periodic asynchronous check-in)", "Embedding canary domains for burn detection", "Compiling obfuscated implants with garble"], "objectives": "Compile tailored Sliver implants across multiple formats and operating systems.", "lab": "Generate a Windows 64-bit mTLS beacon implant and a raw shellcode binary; analyze their file sizes and static properties.", "interview_q": "What is the difference between a Beacon implant and a Session implant in Sliver, and when should you use each?"},
                    {"day_num": 119, "title": "Beacon Management — Tuning Jitter, Sleep Intervals & Tasks", "topics": ["Beacon callback mechanics: Interval (seconds) and Jitter percentage", "Why jitter is essential for evading automated periodic network detection algorithms", "Interacting with beacons (`use <beacon_id>`): Queueing tasks, viewing output, cancelling jobs", "Upgrading a beacon to an interactive real-time session (`interactive`)", "Handling dead beacons, re-connection logic, and kill dates"], "objectives": "Manage asynchronous beacons, queue post-exploitation tasks, and tune timing profiles to evade detection.", "lab": "Deploy a beacon on a Windows target with 60-second sleep and 25% jitter; queue system enumeration tasks and observe callback intervals.", "interview_q": "Explain how jitter works in C2 beaconing and why uniform callback intervals (e.g. exactly every 60 seconds) are trivial for defenders to detect."},
                    {"day_num": 120, "title": "In-Memory Assembly & Extension Execution in Sliver", "topics": ["Executing .NET assemblies in memory without writing to disk: `execute-assembly`", "Sliver Extensions: Installing and running community extensions (Armory)", "Running SharpHound, Seatbelt, and Rubeus directly through Sliver implants", "Process injection options: Choosing spawn-and-inject processes", "OPSEC risks of unmanaged assembly injection (Event ID 7 / Image Loads)"], "objectives": "Execute offensive post-exploitation assemblies in-memory through Sliver without triggering disk-based security controls.", "lab": "Install an extension from the Sliver Armory; execute a C# host reconnaissance assembly in memory and review the returned telemetry.", "interview_q": "How does `execute-assembly` work under the hood, and what Windows APIs are involved in hosting the .NET Common Language Runtime (CLR) inside an unmanaged process?"}
                ]
            },
            {
                "week_num": 25,
                "week_id": "week-25-c2-pivoting-traffic",
                "week_title": "Advanced C2 Operations, Pivoting & Traffic Analysis",
                "objective": "Establish internal network pivots via SOCKS proxies, execute process injection, analyze C2 network signatures, and maintain operational logs.",
                "tools": ["Sliver", "Ligolo-ng", "Proxychains", "Wireshark", "Sysmon", "Ghostwriter"],
                "major_concepts": ["Internal Network Pivoting", "SOCKS5 Over C2", "Process Migration Mechanics", "C2 Beacon Telemetry", "Operational Deconfliction"],
                "weekly_lab": "Pivoting & Network Tunneling Lab: Route traffic through a compromised Windows host into an internal isolated subnet using Sliver socks and Ligolo-ng.",
                "deliverable": "Adversary Pivoting & Network Tunneling Operational Guide",
                "days": [
                    {"day_num": 121, "title": "Internal Network Pivoting — SOCKS5 Proxies & Ligolo-ng", "topics": ["Pivoting concepts: Using a compromised dual-homed machine as a gateway into internal subnets", "Sliver built-in SOCKS proxy: `socks start` and routing through `proxychains`", "Modern high-performance tunneling with Ligolo-ng (TUN interface tunneling)", "Port forwarding: Local port forwards vs remote reverse port forwards", "Scanning through pivots: Tuning nmap and tools to avoid dropping connections over SOCKS"], "objectives": "Pivot through a compromised host to discover and exploit systems on unreachable internal subnets.", "lab": "Establish a SOCKS5 tunnel through a Sliver beacon, configure proxychains, and scan an isolated internal network host.", "interview_q": "Why does Ligolo-ng achieve significantly higher performance and stability for internal network pivoting compared to traditional SOCKS4/5 proxychains?"},
                    {"day_num": 122, "title": "Process Injection & Migration Tradecraft in Windows", "topics": ["Process injection motivations: Evading process termination, blending into legitimate system binaries", "Classic DLL injection: `VirtualAllocEx`, `WriteProcessMemory`, `CreateRemoteThread`", "Process Hollowing: Creating a process in suspended state, unmapping memory, writing payload, resuming thread", "Early Bird APC injection and QueueUserAPC injection", "Defensive indicators: Process access masks (0x1F0FFF), cross-process memory allocations"], "objectives": "Understand how process injection techniques work and migrate C2 execution into stable system processes.", "lab": "Execute a process migration task in Sliver to migrate an implant into `explorer.exe`; inspect Sysmon Event ID 8 and Event ID 10 generated.", "interview_q": "Explain the difference between Classic Remote Thread Injection and Process Hollowing. Which is harder for an EDR to detect and why?"},
                    {"day_num": 123, "title": "C2 Traffic Profiling & Network Telemetry Analysis", "topics": ["Analyzing C2 beacon traffic from a network defender's perspective", "TLS certificate signatures: Default certificates vs spoofed valid certificates", "HTTP request/response characteristics: URI patterns, header ordering, user-agent consistency", "Detecting beaconing via mathematical variance in connection timestamps (Jitter analysis)", "Sniffing C2 sessions with Zeek / Suricata to identify indicators of compromise (IOCs)"], "objectives": "Profile offensive C2 communications using network analysis tools to identify detection signatures.", "lab": "Capture 30 minutes of Sliver beacon traffic in Wireshark, calculate inter-arrival times in Python, and graph the beaconing signature.", "interview_q": "What statistical methods do network threat hunters use to identify periodic C2 beaconing traffic hidden among normal corporate web traffic?"},
                    {"day_num": 124, "title": "Maintaining Persistence via C2 — Tasks, Services & WMI", "topics": ["Installing C2 persistence: Scheduled tasks running on user idle or system startup", "Windows Service persistence: Installing custom services running C2 implants", "WMI Event Subscriptions: `__EventFilter`, `__EventConsumer`, `__FilterToConsumerBinding` for fileless persistence", "Registry autostart keys with living-off-the-land proxies", "Testing persistence survival across full machine reboots"], "objectives": "Deploy durable persistence mechanisms that automatically re-establish C2 beacon sessions upon reboot.", "lab": "Deploy a WMI Event Subscription persistence mechanism via Sliver; restart the target VM and verify automatic beacon re-connection.", "interview_q": "How does WMI Event Subscription persistence work, and why is it considered more stealthy than standard Registry Run keys?"},
                    {"day_num": 125, "title": "Red Team Operational Logging & Activity Tracking", "topics": ["The critical importance of exact operational logs: Every command, timestamp, target IP, and operator ID", "Collaborative engagement platforms: Ghostwriter and SysReptor integration", "Deconfliction logs: Preparing timestamped activity logs for blue team verification", "Tracking indicators of compromise (IOCs): Implant SHA256 hashes, C2 IPs, dropped file paths", "Post-engagement cleanup checklists"], "objectives": "Maintain exhaustive, auditable operational records of all red team actions during an operation.", "lab": "Configure Ghostwriter or a structured markdown engagement log to document actions, command outputs, timestamps, and artifacts generated during testing.", "interview_q": "Why is meticulous, second-by-second activity logging legally and operationally critical during an authorized red team engagement?"}
                ]
            },
            {
                "week_num": 26,
                "week_id": "week-26-adversary-simulation-1",
                "week_title": "Full Authorized Adversary Emulation Exercise — Part 1",
                "objective": "Execute the first half of an authorized adversary emulation: Reconnaissance, initial access, beachhead triage, internal discovery, and privilege escalation.",
                "tools": ["Sliver", "Nmap", "BloodHound", "Seatbelt", "WinPEAS", "Ghostwriter"],
                "major_concepts": ["Exercise Scenario Kickoff", "Initial Compromise Execution", "Beachhead Triage", "Active Directory Mapping", "Host Privilege Escalation"],
                "weekly_lab": "Simulation Part 1 Lab: Execute authorized external recon, gain beachhead foothold via simulated initial access, and elevate privileges on workstation.",
                "deliverable": "Simulation Phase 1 Operations Log & Intermediate Finding Briefing",
                "days": [
                    {"day_num": 126, "title": "Exercise Phase 1: Target Reconnaissance & Plan of Action", "topics": ["Reviewing engagement Rules of Engagement (RoE) and target objective flags", "External reconnaissance execution: Mapping external perimeter IPs, subdomains, and staff emails", "Selecting the initial access vector based on recon findings", "Staging C2 infrastructure: Spin up redirectors, verify listener health, test payload delivery", "Documenting the pre-attack threat model"], "objectives": "Conduct authorized reconnaissance and finalize the operational attack execution plan.", "lab": "Execute the reconnaissance plan against the authorized target enterprise lab environment and finalize the weaponization package.", "interview_q": "Before executing initial access, what final verification checks must the red team lead perform regarding scope and system readiness?"},
                    {"day_num": 127, "title": "Exercise Phase 2: Initial Foothold Establishment & Beachhead Triage", "topics": ["Executing initial access: Triggering the delivery vector (simulated phishing / external service exploit)", "Receiving the first callback in Sliver: Establishing the beachhead beacon session", "Initial situational awareness: Current user (`whoami`), domain membership, hostname, privileges", "Checking for security controls: Installed EDR/AV products, firewall status", "Tuning beacon sleep and jitter for operational stealth"], "objectives": "Establish an initial C2 foothold on the target network and perform safe situational awareness.", "lab": "Execute the initial access exploit in the lab, catch the callback in Sliver, and perform initial non-invasive host triage.", "interview_q": "What are the first five checks a red team operator should perform after landing on an initial beachhead machine?"},
                    {"day_num": 128, "title": "Exercise Phase 3: Local Situational Awareness & Privilege Escalation", "topics": ["In-depth host enumeration: Unquoted service paths, modifiable files, token privileges", "Checking credential stores: Browser history, saved credentials, memory dumps", "Executing local privilege escalation: Elevating from standard domain user to local SYSTEM", "Migrating into a resilient system-level process", "Securing the local foothold with low-profile persistence"], "objectives": "Escalate privileges on the initial beachhead workstation from unprivileged domain user to local SYSTEM.", "lab": "Exploit a service permission flaw on the beachhead workstation to gain SYSTEM privileges; migrate into a long-running system service.", "interview_q": "Why is it important to elevate to local SYSTEM on a beachhead host before attempting internal domain privilege escalation?"},
                    {"day_num": 129, "title": "Exercise Phase 4: Internal Active Directory Enumeration & BloodHound", "topics": ["Running SharpHound in memory via Sliver `execute-assembly`", "Exfiltrating SharpHound zip archives covertly", "Ingesting data into BloodHound and mapping shortest attack paths to Domain Admins", "Identifying intermediate stepping stones: Delegations, local admin rights, shared credentials", "Formulating the lateral movement route"], "objectives": "Collect Active Directory topology data and identify the optimal multi-hop attack path to domain objectives.", "lab": "Execute SharpHound through Sliver without touching disk, exfiltrate the archive, and identify the attack path to domain dominance in BloodHound.", "interview_q": "How do you minimize network noise and LDAP query spikes when collecting Active Directory data with SharpHound during an operation?"},
                    {"day_num": 130, "title": "Exercise Phase 5: Lateral Movement Execution & Secondary Foothold", "topics": ["Harvesting credentials from the local host: Extracting NTLM hashes via Mimikatz / nanodump", "Pivoting to secondary host: Authenticating via Pass-the-Hash over WMI or WinRM", "Deploying a secondary beacon on the internal server", "Establishing a SOCKS tunnel into the internal server subnet", "Verifying reachability to high-value infrastructure (Domain Controllers, File Servers)"], "objectives": "Move laterally from the initial beachhead workstation to a secondary internal tier-1 server.", "lab": "Extract credentials from the compromised workstation, execute lateral movement to an internal member server, and establish a secondary C2 beacon.", "interview_q": "What factors determine whether you should use Pass-the-Hash, Pass-the-Ticket, or overpass-the-hash for lateral movement in a specific target network?"}
                ]
            },
            {
                "week_num": 27,
                "week_id": "week-27-adversary-simulation-2",
                "week_title": "Full Authorized Adversary Emulation Exercise — Part 2 & Reporting",
                "objective": "Execute the second half of the simulation: Domain dominance, actions on objectives, data staging, cleanup, blue team deconfliction, and reporting.",
                "tools": ["Sliver", "Impacket", "Rubeus", "Ghostwriter", "SysReptor", "Markdown"],
                "major_concepts": ["Domain Compromise Execution", "Actions on Objectives", "Covert Exfiltration", "Operational Cleanup", "Deconfliction Meeting", "Red Team Reporting"],
                "weekly_lab": "Deliverable 5 Lab: Execute DCSync, capture objective flags, conduct thorough artifact cleanup, and author the complete Red Team Engagement Report.",
                "deliverable": "Deliverable 5: Full Red Team Engagement Report (Executive Summary + Attack Narrative + MITRE ATT&CK Matrix + Blue Team Deconfliction)",
                "days": [
                    {"day_num": 131, "title": "Exercise Phase 6: Domain Compromise Execution & Objective Attainment", "topics": ["Executing the final privilege escalation attack: Abusing AD CS ESC1 / Kerberos Delegation / DCSync", "Compromising the Domain Controller and obtaining Domain Administrator access", "Accessing the predefined objective flags (e.g. mock customer database, financial records)", "Documenting cryptographic proof of access (hashes, timestamps, non-sensitive sample records)", "Notifying the Trusted Agent / White Cell of flag capture"], "objectives": "Achieve the primary engagement objectives and capture predefined target flags.", "lab": "Execute a DCSync attack to compromise domain credentials and access the designated high-value target objective share.", "interview_q": "Once a red team reaches the ultimate objective (e.g. Domain Admin or sensitive database), what immediate precautions must be taken regarding data access?"},
                    {"day_num": 132, "title": "Exercise Phase 7: Post-Exploitation Actions & Simulated Exfiltration", "topics": ["Simulating realistic adversary exfiltration behavior without moving actual sensitive customer data", "Data staging: Compressing and encrypting mock test data files", "Exfiltration channels: Testing egress via HTTPS, DNS tunneling, and cloud storage uploads", "Measuring egress bandwidth and detection thresholds", "Recording exact exfiltration packet timestamps for defensive correlation"], "objectives": "Simulate covert data exfiltration and test network boundary data loss prevention (DLP) controls.", "lab": "Stage and encrypt a mock test archive and exfiltrate it over an encrypted C2 channel, recording the exact transfer parameters.", "interview_q": "How can a red team safely demonstrate data exfiltration impact without violating privacy regulations or moving sensitive client data across boundaries?"},
                    {"day_num": 133, "title": "Exercise Phase 8: Operational Cleanup & Remediation Verification", "topics": ["The cleanup phase: Reverting all changes made to client systems", "Terminating active C2 beacons and deleting dropped binaries and scripts", "Removing persistence mechanisms: Deleting scheduled tasks, services, registry keys, and WMI subscriptions", "Deleting created local or domain test accounts", "Verifying target systems have returned to clean baseline state"], "objectives": "Completely remove all implants, persistence mechanisms, and artifacts installed during the exercise.", "lab": "Execute the comprehensive cleanup script: Terminate all Sliver beacons, delete dropped payloads, remove persistence tasks, and verify system integrity.", "interview_q": "What risks are introduced if a red team fails to clean up an operational implant or persistence mechanism after an engagement?"},
                    {"day_num": 134, "title": "Exercise Phase 9: Blue Team Deconfliction & Timeline Correlation", "topics": ["Conducting the deconfliction meeting with SOC leads and incident responders", "Comparing red team activity timestamps with blue team SIEM alerts and telemetry", "Identifying detection gaps: Which techniques were detected, which generated alerts, which were completely missed?", "Analyzing Mean Time to Detect (MTTD) and Mean Time to Respond (MTTR)", "Documenting missed detection opportunities across the MITRE ATT&CK matrix"], "objectives": "Lead a collaborative deconfliction session with defenders to analyze detection performance across every attack phase.", "lab": "Align the red team operational timeline against target system Event Logs; document which attack steps generated alerts and which went undetected.", "interview_q": "Why is the timeline deconfliction meeting considered one of the highest-value deliverables of an adversary emulation exercise?"},
                    {"day_num": 135, "title": "Phase 5 Capstone Deliverable — Full Red Team Engagement Report", "topics": ["Authoring the final comprehensive Red Team Engagement Report", "Structuring the deliverable: Executive Summary, Engagement Overview, Narrative Walkthrough, Timeline Table, MITRE ATT&CK Heatmap, Tactical & Strategic Recommendations", "Writing compelling executive narratives that justify security investments", "Providing concrete detection engineering rules (Sigma, Yara) for missed attacks", "Delivering the formal report presentation to leadership and technical teams"], "objectives": "Author and finalize Deliverable 5: A complete, professional Red Team Engagement Report.", "lab": "Compile all operational notes, timelines, screenshots, and remediation guidance into Deliverable 5 in the `projects/` directory.", "interview_q": "How do you present a critical security finding to an executive board in a way that is constructive rather than adversarial?"}
                ]
            }
        ]
    }
]

print(f"[*] Defined Phases 4 and 5 ({len(phases_4_5)} phases). Proceeding to Phases 6-9...")
